async () => {
 const P=window.PARITY,T=P.THREE,results=[];
 const copy=x=>JSON.parse(JSON.stringify(x));
 const assert=(c,m)=>{if(!c)throw Error(m);};
 const maxError=(a,b)=>{assert(a.length===b.length,'buffer length mismatch');let m=0;for(let i=0;i<a.length;i++){assert(Number.isFinite(a[i])&&Number.isFinite(b[i]),'nonfinite component '+i);m=Math.max(m,Math.abs(a[i]-b[i]));}return m;};
 const exact=(a,b)=>assert(JSON.stringify(a)===JSON.stringify(b),'independent source values differ');
 function seeded(fn){const old=Math.random;let seed=19337;Math.random=()=>((seed=Math.imul(seed,1664525)+1013904223)>>>0)/4294967296;try{return fn();}finally{Math.random=old;}}
 async function test(id,fn){console.log('PARITY '+id);try{results.push({id,ok:true,evidence:await fn()});}catch(e){results.push({id,ok:false,error:e.stack});}}
 function canvas(){const c=document.createElement('canvas');c.width=640;c.height=480;c.style.cssText='width:640px;height:480px';document.body.append(c);return c;}
 function construct(Type,cfg,hosted){const raf=window.requestAnimationFrame;window.requestAnimationFrame=()=>0;try{return seeded(()=>new Type(canvas(),copy(cfg),hosted));}finally{window.requestAnimationFrame=raf;}}
 function dispose(e){e.destroy();e.canvas.remove();}
 function config(patch={}){let c=copy(P.migrate({...P.referenceConfig,particleCount:512,...patch}));c.entities=[P.referenceFormation({id:'oracle-formation',shape:{kind:'glyph',text:'O'},scale:1.37,sequence:{...P.referenceConfig.entities[0].sequence,advance:'off',impulse:0,links:[{id:'a',shape:{kind:'glyph',text:'O'}},{id:'b',shape:{kind:'glyph',text:'I'}}]}})];c.material=undefined;c.fluid.timeScale=1;c.fluid.zConfinement=0;c.cymatics.enabled=false;c.relational.enabled=false;c.toroidalMorph.enabled=false;c.morphProgress=.37;c.automations=[];return c;}
 function read(e,target){const s=e.simulator,out=new Float32Array(s.texWidth*s.texHeight*4);e.renderer.readRenderTargetPixels(target,0,0,s.texWidth,s.texHeight,out);return out;}
 function normalize(e,cfg){e.config=copy(cfg);e.simTime=0;e.torPhaseAcc=0;e.polPhaseAcc=0;e.lastDrive=null;e.morphProgress=cfg.morphProgress;e.sweepAccum=0;e.cymaticFreqCurrent=cfg.cymatics.frequencyHz;e.cymaticResonator=null;e.resonatorActive=false;e.initEntities(false);e.entities.bakeSig.clear();e.entities.candidateCache.clear();seeded(()=>e.entities.update(e.config.entities,e.config.composition,0,0,e.morphProgress,e.config.toroidalMorph.holdRatio,e.config.fontFamily,e.config.fontWeight));e.simulator.setTargetTextures(e.entities.textureA,e.entities.textureB,e.entities.fieldCentre(),e.entities.noiseTexture);e.simulator.setEntityState(e.entities.uniforms);}
 function targets(e){const rt=e.entities,u=rt.uniforms,src=rt.textureA.image.data,out=new Float32Array(src.length),norm=u.normalized,noise=rt.noiseTexture?.image.data;for(let i=0;i<e.simulator.particleCount;i++){let k=0;while(k<u.count-1&&i>=u.bounds[k])k++;const o=i*4,centre=u.centers[k];let x=src[o],y=src[o+1],z=src[o+2];if(noise){const horizontal=e.config.composition.plane==='horizontal';let a=x,b=horizontal?-z:y;const tr=u.transforms[k],n=norm[k];a=(a+noise[o]*n)*tr.x;b=(b+noise[o+1]*n)*tr.y;const cx=a*Math.cos(tr.z)-b*Math.sin(tr.z)+noise[o]*(1-n),cy=a*Math.sin(tr.z)+b*Math.cos(tr.z)+noise[o+1]*(1-n);x=cx;if(horizontal){z=-cy;y*=u.depthScales[k];}else{y=cy;z*=u.depthScales[k];}}out[o]=x+centre.x;out[o+1]=y+centre.y;out[o+2]=z+centre.z;out[o+3]=src[o+3];}return out;}
 const cases=[['glyph',c=>{}],['scale-depth',c=>{c.entities[0].scale=2.13;c.entities[0].shape={kind:'cymatic',frequencyHz:396};c.entities[0].sequence.links=[];}],['horizontal',c=>c.composition.plane='horizontal'],['relational-orbital',c=>c.relational.enabled=true],['relational-chaos',c=>{c.relational.enabled=true;c.relational.mode='chaos';}],['relational-nbody',c=>{c.relational.enabled=true;c.relational.mode='nbody';}],['toroidalHopf',c=>{c.toroidalMorph.enabled=true;c.toroidalMorph.trajectory='toroidalHopf';}],['vortexSpiral',c=>{c.toroidalMorph.enabled=true;c.toroidalMorph.trajectory='vortexSpiral';}],['quantumInterference',c=>{c.toroidalMorph.enabled=true;c.toroidalMorph.trajectory='quantumInterference';}],['resonator-64',c=>{c.cymatics.enabled=true;c.cymatics.modeCount=64;c.cymatics.dominance=.6;}]];
 for(const [name,change] of cases)await test('GPU-REFERENCE:'+name,()=>{const c=config();change(c);const reference=construct(P.RefEngine,c,false),hosted=construct(P.Engine,P.toNativeConfig(P.nativeSnapshotToJourney({schemaVersion:4,config:copy(c)}).scenes[0]),true);try{
  if(name==='scale-depth')for(const e of [reference,hosted])e.entities.setCustomCandidates(c.entities[0].id,[{x:43.7,y:-62.3,z:81.4,density:.8},{x:-15,y:29,z:-74,density:.7}]);
  normalize(reference,c);normalize(hosted,c);const tr=targets(reference),th=targets(hosted),targetError=maxError(tr,th);assert(targetError<=.00013,'target error '+targetError);
  const seed=new Float32Array(tr);for(let i=0;i<seed.length;i+=4){seed[i]+=Math.sin(i*.17)*13;seed[i+1]+=Math.cos(i*.23)*11;seed[i+2]+=Math.sin(i*.031)*7;}
  reference.simulator.seedInitialState(seed);hosted.simulator.seedInitialState(seed);
  let positionError=0,velocityError=0;for(let i=1;i<=4;i++){reference.simTime=i/60;seeded(()=>reference.tickFrame(1/60,i/60));seeded(()=>hosted.advance(1/60));positionError=Math.max(positionError,maxError(read(reference,reference.simulator.currentPosTarget),read(hosted,hosted.simulator.currentPosTarget)));velocityError=Math.max(velocityError,maxError(read(reference,reference.simulator.currentVelTarget),read(hosted,hosted.simulator.currentVelTarget)));}
  assert(positionError<=.00025&&velocityError<=.001,JSON.stringify({positionError,velocityError}));return{particles:512,steps:4,targetError,positionError,velocityError};
 }finally{dispose(reference);dispose(hosted);}});
 await test('GPU-LAW-IDENTICAL-TARGETS',()=>{let cases=0,largestError=0;
  for(const trajectory of ['linear','toroidalHopf','vortexSpiral','quantumInterference']){
   const c=config();c.toroidalMorph.enabled=true;c.toroidalMorph.trajectory=trajectory;
   const a=construct(P.RefEngine,c,false),b=construct(P.Engine,c,true);
   try{normalize(a,c);normalize(b,c);const ar=a.entities,br=b.entities;
    br.textureA.image.data.set(ar.textureA.image.data);br.textureB.image.data.set(ar.textureB.image.data);br.textureA.needsUpdate=true;br.textureB.needsUpdate=true;br.noiseTexture.image.data.fill(0);br.noiseTexture.needsUpdate=true;
    br.uniforms.transforms.forEach(v=>v.set(1,1,0));br.uniforms.depthScales.fill(1);br.uniforms.normalized.fill(0);b.simulator.setEntityState(br.uniforms);
    const seed=targets(a);for(let i=0;i<seed.length;i+=4){seed[i]+=13;seed[i+1]-=7;seed[i+2]=5;}
    a.simulator.seedInitialState(seed);b.simulator.seedInitialState(seed);
    for(let i=1;i<=4;i++){for(const e of [a,b]){e.simulator.setMorphPhases(i*.018,i*.014);e.simulator.step(1/60,i/60,c,.37,new T.Vector2(-99999,-99999),new T.Vector2());}
     largestError=Math.max(largestError,maxError(read(a,a.simulator.currentPosTarget),read(b,b.simulator.currentPosTarget)),maxError(read(a,a.simulator.currentVelTarget),read(b,b.simulator.currentVelTarget)));
    }cases++;
   }finally{dispose(a);dispose(b);}
  }assert(largestError===0,'Identical-input force law differs: '+largestError);return{cases,stepsEach:4,maxError:largestError,equality:'exact float32 GPU buffers'};
 });
 await test('PUBLIC-NATIVE-API-RUNTIME',()=>{const c=config(),a=construct(P.RefEngine,c,false),b=construct(P.Engine,c,false);try{
  for(const e of [a,b]){e.setActiveEntity(c.entities[0].id);assert(e.getActiveEntity()===c.entities[0].id,'active identity');assert(e.getEntityCentre(c.entities[0].id),'entity centre');e.setGridMode('axis');assert(e.getGridMode()==='axis','axis');e.setGridVisible(true);assert(e.getGridVisible()&&e.getGridMode()==='grid','grid compatibility');e.setGridMode('off');e.setPanMode(true);assert(e.getPanMode(),'pan mode');e.setPanMode(false);}
  for(const e of [a,b]){e.setCameraState({pitch:.2,yaw:.3,zoom:1.2,panX:23,panY:-17});e.setCameraOrbit(.35,-.25);e.setCameraPan(14,25);e.setCameraZoom(1.7);}
  exact(a.getCameraState(),b.getCameraState());let called=0;b.setOnCameraChange(()=>called++);b.resetCamera('flat');assert(called===2,'camera callback');b.setOnCameraChange(null);a.resetCamera('flat');
  b.setCameraState(a.getCameraState());b.camera.copy(a.camera);a.camera.updateMatrixWorld();b.camera.updateMatrixWorld();
  const ap=a.projectWorldToScreen(40,20,0),bp=b.projectWorldToScreen(40,20,0);assert(Math.hypot(ap.x-bp.x,ap.y-bp.y)<1e-9,'public projection');
  const pin={id:'api-pin',x:40,y:20,z:0,radius:100,strength:1,mode:'attract',active:true};b.setPinMarkers([pin],pin.id,null);assert(b.pickPin(bp.x,bp.y,[pin])===pin.id,'native pin picking');b.setPinMarkers([],null,null);
  let morph=null,automation=null,composition=null;b.setOnMorphUpdate(t=>morph=t);b.setOnAutomationUpdate(t=>automation=t);b.setOnCompositionUpdate(t=>composition=t);b.advance(.1);assert(morph&&automation&&composition&&composition.simTime===b.inspectState().simTime,'native telemetry callbacks');
  b.setOnMorphUpdate(null);b.setOnAutomationUpdate(null);b.setOnCompositionUpdate(null);b.setMorphProgress(.23);assert(b.getMorphProgress()===.23,'manual morph setter');b.resetMorphPhases();b.advance(0);assert(b.getMorphDrive().theta===0,'phase reset');
  return{cameraAndPinAPI:true,telemetryCallbacks:true,manualMorph:true,gridCompatibility:true};
 }finally{dispose(a);dispose(b);}});
 await test('RENDER-NATIVE-CLASSIC-MATRIX',()=>{const c=config();c.entities[0].scale=1;const a=construct(P.RefEngine,c,false),b=construct(P.Engine,c,true);try{
  normalize(a,c);normalize(b,c);const seed=targets(a);for(let i=0;i<seed.length;i+=4){seed[i]=((i/4)%32-16)*9;seed[i+1]=(Math.floor(i/4/32)-8)*9;seed[i+2]=0;seed[i+3]=.8;}
  a.simulator.seedInitialState(seed);b.simulator.seedInitialState(seed);const target=new T.WebGLRenderTarget(640,480,{format:T.RGBAFormat,type:T.UnsignedByteType,depthBuffer:false});let cases=0,totalMarked=0;
  function pixels(e){e.particleMaterial.uniforms.uPositionTexture.value=e.simulator.currentPosTarget.texture;e.particleMaterial.uniforms.uVelocityTexture.value=e.simulator.currentVelTarget.texture;e.particleMaterial.uniforms.uTime.value=0;e.renderer.setRenderTarget(target);e.renderer.clear();e.renderer.render(e.scene,e.camera);const bytes=new Uint8Array(640*480*4);e.renderer.readRenderTargetPixels(target,0,0,640,480,bytes);e.renderer.setRenderTarget(null);return bytes;}
  for(const mode of ['monochrome','linearGradient','radialGradient','angularSweep','velocityThermal','densityDepth','waveInterference','rainbowSpectral'])for(const style of ['stipple','halftone'])for(const dotShape of ['circle','square'])for(const enabled of [false,true]){
   const cfg=copy(c);cfg.style=style;cfg.dotShape=dotShape;cfg.particleSize={min:3,max:5};cfg.color={...cfg.color,mode,enabled};a.updateConfig(cfg);b.replaceConfig(cfg);b.camera.copy(a.camera);a.camera.updateMatrixWorld();b.camera.updateMatrixWorld();b.syncLiveMaterialUniforms();
   const pa=pixels(a),pb=pixels(b);let differing=0,marked=0;for(let i=0;i<pa.length;i++){if(pa[i]!==pb[i])differing++;if(i%4===3&&pa[i])marked++;}assert(differing===0,mode+'/'+style+'/'+dotShape+'/'+enabled+' differing channels '+differing);assert(marked>100,'empty render');totalMarked+=marked;cases++;
  }target.dispose();return{cases,pixelEquality:'exact RGBA',totalMarkedPixels:totalMarked};
 }finally{dispose(a);dispose(b);}});
 await test('SAMPLER-ALL-YANTRAS-TEMPLATES',()=>{const a=new P.RefSampler(),b=new P.Sampler();try{let yantras=0,templates=0;for(const node of P.chakras){exact(seeded(()=>a.rasterizeSpatialNode(node,'yantra','Arial',900,'yantraA')),seeded(()=>b.rasterizeSpatialNode(node,'yantra','Arial',900,'yantraA')));yantras++;for(const geometry of ['square','circular','volumetric3D']){const dimension=geometry==='volumetric3D'?'3D':'2D';exact(seeded(()=>a.sampleCymaticNode(node,geometry,dimension,1,0,node.frequencyHz)),seeded(()=>b.sampleCymaticNode(node,geometry,dimension,1,0,node.frequencyHz)));templates++;}}return{yantras,templates,equality:'exact candidate coordinates/density'};}finally{a.destroy();b.destroy();}});
 await test('SAMPLER-RASTER-AND-ASCII-BASELINE',()=>{const a=new P.RefSampler(),b=new P.Sampler();try{const image=new ImageData(48,48);for(let y=0;y<48;y++)for(let x=0;x<48;x++){const i=(y*48+x)*4;image.data[i]=x*5;image.data[i+1]=y*5;image.data[i+2]=((x+y)%10)*25;image.data[i+3]=(x+y)%7?255:0;}let raster=0,ascii=0;for(const mode of ['luminance','edgeSobel','silhouette'])for(const threshold of [.1,.4,.8])for(const invert of [false,true])for(const scale of [.3,1,2]){exact(seeded(()=>a.rasterizeCustomImage(image,{mode,threshold,invert,scale})),seeded(()=>b.rasterizeCustomImage(image,{mode,threshold,invert,scale})));raster++;}for(const text of ['O','I','O:I','*&*','/\\\n\\/','@ @\n @ ','x---x','12345','...\n.:.\n...']){exact(seeded(()=>a.rasterizeAscii(text)),seeded(()=>b.rasterizeAscii(text)));ascii++;}return{raster,ascii,equality:'exact native candidate data'};}finally{a.destroy();b.destroy();}});
 await test('FIX-SPARSE-GPU-MODES',()=>{const c=config();Object.assign(c.fluid,{returnSpeed:0,turbulence:0,vortexStrength:0,dispersion:0,viscosity:1});const e=construct(P.Engine,c,true);try{const sim=e.simulator,seed=targets(e);for(let i=0;i<seed.length;i+=4){seed[i]=47;seed[i+1]=63;seed[i+2]=0;}sim.seedInitialState(seed);const re=new Float32Array(64),im=new Float32Array(64);re[27]=3;sim.setResonatorState(true,1,re,im,700,1,0,0,1,1);sim.setResonatorDominance(1);sim.step(1/60,0,c,0,new T.Vector2(-99999,-99999),new T.Vector2());const v=read(e,sim.currentVelTarget);assert(Math.hypot(v[0],v[1])>1e-7,'addressed mode beyond prefix has no force');return{addressedSlot:27,modeBudget:1,velocity:Array.from(v.slice(0,3))};}finally{dispose(e);}});
 await test('FIX-IDENTICAL-LINK-SOURCE-OWNERSHIP',()=>{const c=config();c.entities[0].sequence.links[1].shape={kind:'glyph',text:'O'};const e=construct(P.Engine,c,true);try{e.loadAsciiArt('A',{},c.entities[0].id);e.advance(0);const rt=e.entities,first=Array.from(rt.textureA.image.data),second=Array.from(rt.textureB.image.data);assert(maxError(first,second)>1,'custom first link incorrectly overrides later identical glyph');return{firstLinkOnly:true};}finally{dispose(e);}});
 return results;
}
