import * as THREE from 'three';
import {PointCloudField as RefEngine,DEFAULT_CONFIG as referenceConfig} from '../../.parity-reference/master/src/engine/PointCloudField';
import {GlyphSampler as RefSampler} from '../../.parity-reference/master/src/engine/GlyphSampler';
import {makeFormation as referenceFormation,COMPOSITION_PRESETS as compositions} from '../../.parity-reference/master/src/engine/fieldModel';
import {CANONICAL_CHAKRAS as chakras} from '../../.parity-reference/master/src/engine/chakraSystem';
import {migrateConfig as migrate} from '../../.parity-reference/master/src/engine/configMigration';
import {FACTORY_PRESETS as presets} from '../../.parity-reference/master/src/engine/factoryPresets';
import {PointCloudField as Engine} from '../../src/engine/PointCloudField';
import {GlyphSampler as Sampler} from '../../src/engine/GlyphSampler';
import {ProductionAdapter} from '../../field-studies-journeys/src/production';
import {nativeSnapshotToJourney,toNativeConfig} from '../../field-studies-journeys/src/nativeBridge';
import {defaultCamera} from '../../field-studies-journeys/src/camera';
(window as any).PARITY={THREE,RefEngine,RefSampler,Engine,Sampler,ProductionAdapter,referenceConfig,referenceFormation,compositions,presets,migrate,chakras,nativeSnapshotToJourney,toNativeConfig,defaultCamera};
