/** Source-indexed parity ledger. Verification is admitted only after every required
 * result file from the clean acceptance run passes; source presence is not proof. */
import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
import ts from 'typescript';
import {PARAM_REGISTRY as originalRegistry} from '../../.parity-reference/master/src/engine/paramRegistry';
import {PARAM_REGISTRY,entityParamDefs} from '../../src/engine/paramRegistry';
import {NATIVE_BINDINGS} from '../../field-studies-journeys/src/nativeParameters';
import {PARAMETERS} from '../../field-studies-journeys/src/registry';
import {COLOR_PALETTES,BACKGROUND_THEMES} from '../../src/engine/colorPalettes';
import {CHAIN_PRESETS,GLYPH_CATEGORIES} from '../../src/engine/glyphLibrary';
import {FACTORY_PRESETS} from '../../src/engine/factoryPresets';
import {COMPOSITION_PRESETS} from '../../src/engine/fieldModel';

const dir='field-studies-journeys/docs/parity',evidence='field-studies-journeys/evidence-native';
fs.mkdirSync(dir,{recursive:true});
const verify=process.argv.includes('--verify');
const dormant:Record<string,string>={autoMorphDuration:'The entity runtime superseded this timer with sequence and phase controls.', 'toroidalMorph.progress':'The current entity runtime uses morphProgress or the shared drive; this older field is no longer consumed.'};
const home=(group:string)=>group==='Morph'?'Motion / Morph':group==='Composition'?'Motion / Focus':`Field / ${group}`;
function consumer(p:string){
 if(p==='particleCount')return 'PointCloudField.applyConfig → rebuildParticleSystem / GPGPUSimulator constructor';
 if(p.startsWith('particleSize.')||p.startsWith('material.')||p.startsWith('color.'))return 'PointCloudField.initParticlePipeline / syncLiveMaterialUniforms → shaders/particleShaders';
 if(p.startsWith('background')||p==='paperGrain')return 'paper.paintPaper → live paper and clean capture';
 if(p==='fluid.timeScale')return 'PointCloudField.advance (one authoritative clock)';
 if(p.startsWith('fluid.')||p.startsWith('interaction.'))return 'GPGPUSimulator.step → shaders/simulationShaders';
 if(p.startsWith('relational.'))return 'PointCloudField.tickFrame dynamic centres → GPGPUSimulator.step → simulationShaders';
 if(p.startsWith('cymatics.'))return 'PointCloudField.tickCymaticMedium → CymaticResonator / GPGPUSimulator';
 if(p.startsWith('composition.'))return 'fieldModel.resolveFocus / EntityRuntime.update → particle tints and station driver';
 return 'PointCloudField.computeMorphDrive / advanceMorphOscillator → EntityRuntime / GPGPUSimulator';
}
const rows:any[]=[];
for(const p of PARAM_REGISTRY){
 const b=NATIVE_BINDINGS.find(b=>b.path===p.path);assert.ok(b,'Missing native binding '+p.path);
 rows.push({id:'NUM:'+p.path,capability:p.label,nativeSource:'src/engine/paramRegistry.ts',nativePath:p.path,nativeConsumer:consumer(p.path),owner:p.group,scope:'field',
  nativeBounds:{slider:[p.min,p.max],typed:[p.hardMin,p.hardMax],step:p.step,unit:p.unit??'native scalar'},authoringHome:home(p.group),authoringPath:b!.bind,conversion:{nativePerAuthoringUnit:b!.factor},
  reset:p.path==='particleCount'?'Explicit allocation/reseed; all other config preserved':'No particle reseed; owning native driver/target/render state changes',
  authority:originalRegistry.some(x=>x.path===p.path)?'pinned native':'approved authoring extension or previously unregistered native owner',
  implementation:dormant[p.path]?'retained-unconsumed':'connected',reason:dormant[p.path],
  verification:dormant[p.path]?['PAR-CONFIG','UI-ALL-NATIVE-NUMERIC-HOMES']:['PAR-NUMERIC','UI-ALL-NATIVE-NUMERIC-HOMES',p.group==='Color'||p.group==='Particles'?'RENDER-NATIVE-CLASSIC-MATRIX':'GPU-REFERENCE'],
  status:verify?(dormant[p.path]?'declared-unconsumed':'verified-in-recorded-matrices'):'implemented-awaiting-clean-run'});
}
for(const p of entityParamDefs(0,{name:'Selected formation'}))rows.push({id:'ENTITY:'+p.path.replace('entities.0.',''),capability:p.label,nativeSource:'src/engine/fieldModel.ts / entityRuntime.ts',nativeConsumer:'EntityRuntime.update → native partition uniforms / fieldModel.resolveSequence',owner:'entity',scope:'selected stable entity ID',nativeBounds:{slider:[p.min,p.max],typed:[p.hardMin,p.hardMax],unit:p.unit??'native scalar'},authoringHome:p.path.includes('sequence.')?'Motion / selected entity sequence':'Objects / selected entity',conversion:['x','y','z','forces.radius'].some(k=>p.path==='entities.0.'+k)?400:1,reset:'No reseed; target changes rebake only affected geometry',verification:['PAR-UNREGISTERED-LANES-REORDER','PAR-SEQUENCE','GPU external clock/uniform movement','native editor browser workflows'],status:verify?'verified-in-recorded-matrices':'implemented-awaiting-clean-run'});
function feature(id:string,capability:string,source:string,scope:string,location:string,variants:any,tests:string[],notes=''){
 rows.push({id,capability,nativeSource:source,nativeConsumer:source,owner:scope,scope,authoringHome:location,variants,reset:'Document changes preserve running particles except explicit allocation/reset/context recovery',implementation:'connected',verification:tests,notes,status:verify?'verified-in-recorded-matrices':'implemented-awaiting-clean-run'});
}
feature('MARKS','Native stipple/halftone, circle/square, palette off/on','src/engine/shaders/particleShaders.ts','field','Field / Mark profile',{styles:2,shapes:2,colourEnabled:2},['RENDER-NATIVE-CLASSIC-MATRIX']);
feature('PALETTES','Native palette catalogue and recommended dynamics','src/engine/colorPalettes.ts','field','Field / Palette and paper',COLOR_PALETTES.map(p=>p.id),['PAR-CATALOGUES','UI-NATIVE-PALETTES']);
feature('PALETTE-EDIT','Two–eight editable stops; invert and random native palette','src/components/ColorSystemPanel.tsx','field','Field / Palette and paper',[2,3,4,5,6,7,8],['UI-EIGHT-STOPS-NATIVE-RESTORE']);
feature('PAPERS','Background themes, atmosphere, inversion and harmonization','src/engine/colorPalettes.ts / src/components/ColorSystemPanel.tsx','field','Field / Palette and paper',{themes:BACKGROUND_THEMES.map(p=>p.id),atmospheres:['solid','vignette','ambientGlow','adaptive']},['UI-NATIVE-PAPERS']);
feature('COLOUR-DISTRIBUTION','All native colour distributions','src/engine/types.ts / shaders/particleShaders.ts','field','Field / Palette and paper',['monochrome','linearGradient','radialGradient','angularSweep','velocityThermal','densityDepth','waveInterference','rainbowSpectral'],['RENDER-NATIVE-CLASSIC-MATRIX']);
feature('GLYPHS','Glyph library, free text, fonts and all nine native weights','src/engine/glyphLibrary.ts / GlyphSampler.ts','entity / field font','Objects / Formation; Field / Glyph sampling',{categories:GLYPH_CATEGORIES.map(p=>p.id??p.name),glyphCount:GLYPH_CATEGORIES.reduce((n,c)=>n+c.items.length,0),fontWeights:[100,200,300,400,500,600,700,800,900]},['PAR-CATALOGUES','UI-GLYPH-CATALOGUE','UI-NATIVE-ENUMS-AND-FONTS']);
feature('YANTRAS','Seven canonical yantra samplers','src/engine/GlyphSampler.ts','entity','Objects / Formation',7,['SAMPLER-ALL-YANTRAS-TEMPLATES']);
feature('TEMPLATES','Native authored cymatic geometry and sampling dimension','src/engine/GlyphSampler.ts / cymatics.ts','entity with field defaults','Objects / Formation; Field / Template geometry',{geometry:['square','circular','volumetric3D'],dimension:['2D','3D']},['SAMPLER-ALL-YANTRAS-TEMPLATES','UI-TEMPLATE-GEOMETRIES'],'Authored geometry, not three alternative continuous media. D09 records the prior hardcoded square-target defect.');
feature('RASTER','Embedded PNG/JPEG/WebP, sampler mode, threshold, inversion, scale','src/engine/GlyphSampler.ts','entity first link','Objects / Image source',{formats:['png','jpeg','webp'],modes:['luminance','edgeSobel','silhouette']},['SAMPLER-RASTER-AND-ASCII-BASELINE','UI-RASTER-PORTABLE-ASSETS','FIX-IDENTICAL-LINK-SOURCE-OWNERSHIP']);
feature('ASCII','Native ASCII drawing, font family/size and inversion','src/engine/GlyphSampler.ts','entity first link','Objects / ASCII source',['text','fontFamily','fontSize','invert'],['SAMPLER-RASTER-AND-ASCII-BASELINE','UI-ASCII'],'Default sampling matches the oracle; formerly ignored font/invert options are declared corrections.');
feature('ENTITIES','Formations and force-only pins, names, enable/lock, shares and transforms','src/engine/fieldModel.ts / entityRuntime.ts','entity','Canvas / Objects',{formations:10,pins:8,forceModes:['none','attract','repel','vortex']},['GPU pin force suite','GPU external clock/uniform movement','native editor browser workflows'],'Editing lock differs from runtime enable. Native share floor and integer allocation are disclosed.');
feature('SPATIAL','Placement, selection, drag, radius handle, numeric depth, nudging and undo','field-studies-journeys/src/app.ts / camera.ts','authoring command / input','Canvas / Objects',['XY','XZ','YZ','snap','grid','depth'],['native editor browser workflows','workspace browser workflows','UI-LIVE-DRAG-BEFORE-RELEASE'],'One input owner; camera, working plane, layout plane and physics plane stay separate.');
feature('LAYOUTS','Original numeric layouts and approved fitted arrangements','src/engine/layouts.ts / src/components/CompositionPanel.tsx','selected unlocked entities','Objects / Arrangement',['ring','line','column','grid','spiral'],['PAR-NATIVE-LAYOUTS','UI-NATIVE-LAYOUTS'],'Native spacing is distinct from fitted authoring layouts; no hidden mode continues to modify entities.');
feature('RELATIONAL','Dynamic native attractor laws','src/engine/PointCloudField.ts / GPGPUSimulator.ts','field','Field / Relational',['orbital','chaos','nbody'],['GPU-REFERENCE','UI-NATIVE-ENUMS-AND-FONTS'],'Native nbody label denotes its implemented figure-eight centre motion, not a newly introduced many-body solver.');
feature('SEQUENCES','Local links, seconds/morph/manual, order, easing, jitter, impulse, offsets and rates','src/engine/fieldModel.ts','entity / link','Motion / Sequence',{advance:['off','time','morphCycle'],order:['loop','pingpong','random'],easing:['linear','smoothstep','kineticSnap','whip']},['PAR-SEQUENCE','UI-NATIVE-CHAINS','combined sequences/focus/resonance GPU suite']);
feature('CHAIN-PRESETS','Every original chain and rising-seed spatial route','src/engine/glyphLibrary.ts / chakraSystem.ts','entity','Motion / Native sequence presets',CHAIN_PRESETS.map(c=>c.id),['PAR-CHAIN-CATALOGUE','PAR-NATIVE-KUNDALINI-LINKS','UI-NATIVE-CHAINS']);
feature('MORPH','Dual-phase drive, trajectories, waveforms and interference laws','src/engine/PointCloudField.ts / simulationShaders.ts','field clock','Motion / Morph',{trajectories:['linear','toroidalHopf','vortexSpiral','quantumInterference'],waves:['sine','triangle','smooth','pulse'],interference:['toroidalOnly','product','sum','beat']},['PAR-PHASE','GPU-LAW-IDENTICAL-TARGETS','GPU-REFERENCE','UI-NATIVE-ENUMS-AND-FONTS']);
feature('FOCUS','Travelling focus route and tint/station contributions','src/engine/fieldModel.ts / PointCloudField.ts','composition','Motion / Focus',['parallel','focus','listed','reverse','pingpong'],['PAR-FOCUS','combined sequences/focus/resonance GPU suite','native editor browser workflows']);
feature('RESONANCE','One driven square modal plate, live stations, sweeps and blend','src/engine/cymaticResonator.ts / PointCloudField.ts / simulationShaders.ts','field','Field / Continuous resonance',{drivers:['manual','focus','automation'],sweeps:['ascent','descent','pingpong'],slots:64},['GPU-REFERENCE:resonator-64','FIX-SPARSE-GPU-MODES','FIX-PAUSED-RESONATOR','UI-NATIVE-ENUMS-AND-FONTS']);
feature('AUTOMATION','LFOs, ramps, easing, loop modes, ordering, firing and bypass','src/engine/automation.ts','field / entity / stable link','Parameter wave icon → Motion / Automation',{waves:6,easings:6,blends:['replace','add','multiply'],loops:['none','restart','pingpong']},['PAR-AUTOMATION','PAR-WIDE-SIGNED-AUTOMATION','PAR-UNREGISTERED-LANES-REORDER','native editor browser workflows']);
feature('MODES','Complete native factory/composition and approved material starts','src/engine/factoryPresets.ts / fieldModel.ts','expression','Modes / Library',{factory:FACTORY_PRESETS.map(p=>p.id),composition:COMPOSITION_PRESETS.map(p=>p.id),approvedStudies:8},['PAR-CONFIG','UI-ALL-STARTING-MODES-NATIVE-COUNTS'],'Native factory defaults retain 200,000 particles; no hidden reduction to shell allocation.');
feature('RUNTIME','Disperse, reset particles, reset phases and fire lanes','src/engine/PointCloudField.ts','runtime command','Field / Runtime actions; Motion / Morph',['disperse','resetField','resetMorphPhases','fireAutomation'],['UI-DISPERSE','UI-RESET-PHASES','PUBLIC-NATIVE-API-RUNTIME','native GPU reset suite']);
feature('PERSISTENCE','Native schema migration, lossless projection, unknown fields and safe imports','src/engine/configMigration.ts / field-studies-journeys/src/nativeDelta.ts','document','Library / import/export',['native schema 4','legacy migrations','oi.journey/1'],['PAR-CONFIG','PAR-EDIT','PAR-SAFE-IMPORT','PAR-LEGACY-EXPRESSION-ENVELOPE','UI-RASTER-PORTABLE-ASSETS']);
feature('LIBRARY','Expressions gallery, forks, metadata, save/delete and recovery','field-studies-journeys/src/store.ts / expressions.ts','document / storage','Library',['save','import','fork','delete','export','about'],['workspace browser workflows','UI-DELETE-ACTIVE-SAVED-COPY']);
feature('CAPTURE','Native-resolution PNG, silent live video, editable portable HTML','field-studies-journeys/src/capture.ts / PointCloudField.renderImage','capture','Canvas icons / Library exports',['PNG','browser-supported MediaRecorder codecs','HTML','JSON'],['native GPU clean capture suite','native editor decoded PNG/video/export workflows','module-acceptance'],'No checkpoint, audio, deterministic offline replay or seamless-loop claim.');
feature('CAMERA','Approved orbital controls and native public camera API','field-studies-journeys/src/orbitControl.ts / camera.ts / PointCloudField.ts','view only','Bottom-left orbital instrument',['orbit','pan','zoom','axis views','numeric/keyboard alternatives'],['workspace browser workflows','native projection GPU suite','PUBLIC-NATIVE-API-RUNTIME']);
feature('LIFECYCLE','Pause, visibility, library suspension, resizing, disposal and GPU recovery','field-studies-journeys/src/production.ts / app.ts','host / native runtime','Canvas / recovery panel',['pause','resize','dispose','explicit context recovery'],['DEFAULT-62000-LIVE','REAL-WEBGL-LOSS-RECOVERY','workspace browser workflows']);
feature('SCAFFOLDS','Native axis/grid/off and independent construction-plane guides','src/engine/PointCloudField.ts','view overlay','Scene / Scene view',['off','axis','grid'],['UI-NATIVE-SCAFFOLD','PUBLIC-NATIVE-API-RUNTIME']);
const nativeFile='.parity-reference/master/src/engine/PointCloudField.ts',source=fs.readFileSync(nativeFile,'utf8'),ast=ts.createSourceFile(nativeFile,source,ts.ScriptTarget.Latest,true);
const cls=ast.statements.find(s=>ts.isClassDeclaration(s)&&s.name?.text==='PointCloudField') as ts.ClassDeclaration;
for(const member of cls.members)if(ts.isMethodDeclaration(member)&&!member.modifiers?.some(m=>m.kind===ts.SyntaxKind.PrivateKeyword)){
 const name=member.name.getText(ast);rows.push({id:'API:'+name,capability:name,nativeSource:`src/engine/PointCloudField.ts:${ast.getLineAndCharacterOfPosition(member.getStart()).line+1} (pinned reference)`,nativeConsumer:'Public PointCloudField / unchanged PointCloudComponent embedding contract',owner:'native runtime or native view',scope:'embedding API',authoringHome:'Native API preserved; host commands / contextual UI are separate consumers',reset:/resetField/.test(name)?'Explicit native reset':'Native method contract retained',verification:['PAR-PUBLIC-API-SURFACE','PUBLIC-NATIVE-API-RUNTIME','source-specific GPU/browser suites'],status:verify?'api-preserved-and-exercised-by-group':'implemented-awaiting-clean-run'});
}
for(const p of PARAMETERS.filter(p=>p.group==='retained'))rows.push({id:'PREVIEW:'+p.key,capability:p.label,scope:'historical preview only',authoringHome:'Field / Retained preview values',implementation:'not-a-native-capability',reason:p.inactive,status:'explicitly-unavailable'});
const files=['parity-independent.json','parity-gpu.json','parity-workflows.json','parity-lifecycle.json','gpu-acceptance.json','browser-acceptance.json','workspace-acceptance.json','module-acceptance.json','reference-apps.json'];
const receipts:any[]=[];
if(verify)for(const f of files){const result=JSON.parse(fs.readFileSync(path.join(evidence,f),'utf8'));assert.ok(!result.failed, f+' failures');assert.ok(!(result.browserErrors?.length),f+' browser errors');const outcomes=result.results??[];assert.ok(outcomes.every((r:any)=>r.ok!==false),f+' failed case');if(f==='module-acceptance.json')assert.ok(result.moduleArtifactExport&&result.particleCount===62000&&!result.externalRequests.length);receipts.push({file:f,cases:outcomes.length,passed:true});}
const ledger={nativeReference:'63e650d26a04447b973f73dded6b5046a0829e84',historicalReference:'040627d0ea40032fe7c7b8c98be9a246be9db7f6',approvedShell:'9bf229dfeddfcacc3839f68662ec65e82afbd48b',stage:verify?'clean-run-verified':'implementation-index',finiteEvidenceNotUniversalProof:true,recordCount:rows.length,rows,receipts};
fs.writeFileSync(path.join(dir,'FEATURE_PARITY.json'),JSON.stringify(ledger,null,2)+'\n');
if(verify)fs.writeFileSync(path.join(evidence,'parity-closure.json'),JSON.stringify({passed:true,records:rows.length,receipts,note:'Verified recorded matrices and declared differences, not every possible input/device.'},null,2));
console.log(`${verify?'Verified':'Indexed'} ${rows.length} source-indexed capability/API records.`);
