import {test,expect} from '@playwright/test';
import {execFileSync} from 'node:child_process';
import {writeFileSync} from 'node:fs';
import {fieldStudies} from '../../field-studies-journeys/build/model.js';
test('master Expressions captures, scene provenance, desktop library, and production overlay',async({page,request})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 const expression=fieldStudies();expression.name='Physis master fixture';expression.scenes.forEach(s=>s.field.params.count=2048);
 await page.addInitScript(doc=>{(window as any).__JOURNEY__=doc;},expression);
 await page.goto('/');
 await page.waitForFunction(()=>!!(window as any).__FIELD_STUDIES__?.inspect());
 expect(await page.evaluate(()=>(window as any).__FIELD_STUDIES__.capabilities.kind)).toBe('production');
 expect(await page.evaluate(()=>(window as any).__FIELD_STUDIES__.inspect().particleCount)).toBe(2048);
 await expect(page.getByRole('button',{name:'Physis desktop',exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Capture image',exact:true}).click();
 await expect(page.getByRole('status')).toHaveText('Image saved to the Physis library.',{timeout:15000});
 let media=await (await request.get('/api/media')).json();
 const opaque=media.find((m:any)=>m.kind==='images');
 const inspect=async(url:string)=>page.evaluate(async url=>{const img=new Image();img.src=url;await img.decode();const c=document.createElement('canvas');c.width=img.width;c.height=img.height;const ctx=c.getContext('2d')!;ctx.drawImage(img,0,0);const p=ctx.getImageData(0,0,c.width,c.height).data;let zero=0,solid=0;for(let i=3;i<p.length;i+=4){if(p[i]===0)zero++;if(p[i]===255)solid++;}return{width:c.width,height:c.height,zero,solid};},url);
 const opaqueInfo=await inspect(opaque.url);expect(opaqueInfo.width).toBe(1440);expect(opaqueInfo.zero).toBe(0);
 await page.getByRole('button',{name:'Capture options',exact:true}).click();
 await page.locator('#capture-transparent').check();
 await page.getByRole('button',{name:'Capture image',exact:true}).click();
 await expect(page.getByRole('status')).toHaveText('Image saved to the Physis library.',{timeout:15000});
 await expect.poll(async()=>(await (await request.get('/api/media')).json()).length).toBeGreaterThan(media.length);
 media=await (await request.get('/api/media')).json();
 const alpha=await inspect(media[0].url);expect(alpha.zero).toBeGreaterThan(10000);expect(alpha.zero).toBeLessThan(alpha.width*alpha.height);
 await page.getByRole('button',{name:'Record video',exact:true}).click();
 await expect(page.locator('#recording-badge')).toBeVisible();
 await page.waitForFunction(()=>parseInt(document.querySelector('#record-time')!.textContent!.split(':')[1])>=4);
 await page.locator('#record-button').click();
 await expect(page.getByRole('dialog',{name:'Review recording'})).toBeVisible();
 await page.getByRole('button',{name:'Save recording',exact:true}).click();
 await expect(page.getByRole('status')).toHaveText('Video saved to the Physis library and screensaver.',{timeout:15000});
 media=await (await request.get('/api/media')).json();const video=media.find((m:any)=>m.kind==='videos');expect(video.captureSettings).toBeTruthy();
 const bytes=await (await request.get(video.url)).body();writeFileSync('/tmp/physis-master-test.webm',bytes);
 const info=JSON.parse(execFileSync('ffprobe',['-v','error','-show_streams','-of','json','/tmp/physis-master-test.webm'],{encoding:'utf8'}));expect(info.streams[0].width).toBe(1280);
 const hashes=execFileSync('ffmpeg',['-v','error','-i','/tmp/physis-master-test.webm','-vf','fps=1','-f','framemd5','-'],{encoding:'utf8'}).split('\n').filter(line=>line&&!line.startsWith('#')).map(line=>line.split(',').at(-1));expect(new Set(hashes).size).toBeGreaterThan(1);
 await page.getByRole('button',{name:'Return to the field',exact:true}).click();
 await page.getByRole('button',{name:'Physis desktop',exact:true}).click();
 await page.getByRole('button',{name:'Save expression to disk',exact:true}).click();
 await expect(page.getByRole('status')).toHaveText('Expression saved to the Physis directory.');
 const scenes=await (await request.get('/api/scenes')).json();const saved=scenes[0];expect(saved.version).toBe(2);expect(saved.expression.name).toBe(expression.name);expect(saved.expression.scenes.length).toBe(expression.scenes.length);
 await page.getByLabel('Physis saved expressions').selectOption(saved.id);
 await expect(page.getByRole('status')).toHaveText('Expression loaded from the Physis directory.');
 await page.screenshot({path:'build/master-studio-verified.png'});
 await request.post('/api/overlay',{headers:{'X-Physis-Client':'1'},data:{sceneId:saved.id,particleLimit:2048}});
 const ready=page.waitForEvent('console',msg=>msg.text()==='PHYSIS_ENGINE_READY');await page.goto('/render');await ready;
 expect(await page.locator('canvas').evaluate(c=>getComputedStyle(c).backgroundColor)).toBe('rgba(0, 0, 0, 0)');
 await page.screenshot({path:'build/master-overlay-verified.png',omitBackground:true});
 expect(errors).toEqual([]);
});
