import {test,expect} from '@playwright/test';
import {execFileSync} from 'node:child_process';
import {writeFileSync} from 'node:fs';
test('scene, opaque/transparent PNG, playable animation, and overlay rendering',async({page,request})=>{
 const errors:string[]=[];page.on('pageerror',e=>{errors.push(e.message);console.error(e.message);});
 const seeded=await (await request.post('/api/scenes',{headers:{'X-Physis-Client':'1'},data:{name:'Small render fixture',config:{glyph:['O','I'],particleCount:4096}}})).json();
 await page.addInitScript(()=>localStorage.setItem('physis:working-config',JSON.stringify({glyph:['O','I'],particleCount:4096})));
 await page.goto('/');
 await expect(page.getByRole('button',{name:'Image',exact:true})).toBeEnabled({timeout:20000});
 await page.getByRole('button',{name:/PHYSIS/}).click();
 await page.getByLabel('Load saved scene').selectOption(seeded.id);
 await page.getByLabel('Scene name').fill('Physis integration scene');
 await page.getByRole('button',{name:'Save scene',exact:true}).click();
 await expect(page.getByRole('status')).toHaveText('Scene saved to your library.');
 const scenes=await (await request.get('/api/scenes')).json();expect(scenes[0].config.glyph).toBeTruthy();
 await page.getByRole('button',{name:'Image',exact:true}).click();
 await expect(page.getByRole('status')).toHaveText('PNG saved to your library.',{timeout:20000});
 let media=await (await request.get('/api/media')).json();
 const opaque=media.find((m:any)=>m.kind==='images');
 const inspect=async(url:string)=>page.evaluate(async url=>{const img=new Image();img.src=url;await img.decode();const c=document.createElement('canvas');c.width=img.width;c.height=img.height;const ctx=c.getContext('2d')!;ctx.drawImage(img,0,0);const p=ctx.getImageData(0,0,c.width,c.height).data;let zero=0,solid=0;for(let i=3;i<p.length;i+=4){if(p[i]===0)zero++;if(p[i]===255)solid++;}return{width:c.width,height:c.height,zero,solid};},url);
 expect(await inspect(opaque.url)).toMatchObject({width:1280,height:800,zero:0,solid:1280*800});
 await page.getByLabel('Transparent PNG').check();
 await page.getByRole('button',{name:'Image',exact:true}).click();
 await expect(page.getByRole('status')).toHaveText('PNG saved to your library.',{timeout:20000});
 media=await (await request.get('/api/media')).json();
 const alpha=await inspect(media[0].url);expect(alpha.zero).toBeGreaterThan(100000);expect(alpha.zero).toBeLessThan(1280*800);
 await page.getByLabel('Video length').selectOption('5');
 await page.getByRole('button',{name:'Record',exact:true}).click();
 await expect(page.getByRole('button',{name:'Stop',exact:true})).toBeVisible();
 await expect(page.getByRole('status')).toContainText('Video saved.',{timeout:25000});
 media=await (await request.get('/api/media')).json();const video=media.find((m:any)=>m.kind==='videos');expect(video).toBeTruthy();
 const bytes=await (await request.get(video.url)).body();writeFileSync('/tmp/physis-browser-test.webm',bytes);
 const info=JSON.parse(execFileSync('ffprobe',['-v','error','-show_streams','-of','json','/tmp/physis-browser-test.webm'],{encoding:'utf8'}));
 expect(info.streams[0].width).toBe(1280);expect(info.streams[0].height).toBe(800);
 const hashes=execFileSync('ffmpeg',['-v','error','-i','/tmp/physis-browser-test.webm','-vf','fps=1','-f','framemd5','-'],{encoding:'utf8'}).split('\n').filter(line=>line&&!line.startsWith('#')).map(line=>line.split(',').at(-1));
 expect(hashes.length).toBeGreaterThanOrEqual(3);expect(new Set(hashes).size).toBeGreaterThan(1);
 await page.screenshot({path:'build/studio-verified.png'});
 const ready=page.waitForEvent('console',msg=>msg.text()==='PHYSIS_ENGINE_READY');await request.post('/api/overlay',{headers:{'X-Physis-Client':'1'},data:{sceneId:seeded.id,particleLimit:4096}});await page.goto('/render');await ready;
 expect(await page.locator('canvas').evaluate(c=>getComputedStyle(c).backgroundColor)).toBe('rgba(0, 0, 0, 0)');
 await page.screenshot({path:'build/overlay-verified.png',omitBackground:true});
 expect(errors).toEqual([]);
});
