import {Scene} from './model';
import {automationTarget,baseValue} from './nativeParameters';
import {automationGroups,automationLeader} from './automationLinks';
import {esc,icon} from './icons';
export type MonitorMode='cycle'|'live';
function cycleHTML(s:Scene,id:string){const lane=s.automation.find(l=>l.id===id)??s.automation[0];const leader=lane?automationLeader(s.automation,lane):null,groups=automationGroups(s.automation),group=leader?groups.find(g=>g.leader.id===leader.id)!:undefined;
 return `<div class="cycle-dial"><svg viewBox="0 0 64 64" aria-hidden="true"><circle cx="32" cy="32" r="25"/><circle class="cycle-progress" cx="32" cy="32" r="25" pathLength="100"/><line data-cycle-hand x1="32" y1="32" x2="32" y2="9"/><circle cx="32" cy="32" r="2"/></svg><span data-cycle-phase>0%</span></div><div class="cycle-info"><select id="monitor-lane" aria-label="Monitored automation">${groups.map(({leader:g,targets},i)=>`<option value="${esc(g.id)}" ${g.id===leader?.id?'selected':''}>${g.type==='ramp'?'One-shot':g.wave==='morph'?'Morph drive':'Cycle'} ${i+1} · ${targets.length} parameters</option>`).join('')}</select><div class="cycle-targets">${(group?.targets??[]).map(l=>`<div><span>${esc(automationTarget(s,l.target)?.label??l.target)}</span><output data-live-target="${esc(l.target)}">—</output></div>`).join('')}</div><div class="cycle-actions"><button data-action="toggle-monitored" data-id="${esc(leader?.id??'')}" aria-label="${leader?.enabled?'Pause':'Enable'} automation group">${icon(leader?.enabled?'pause':'play')}</button>${leader?.type==='ramp'?`<button data-action="fire-lane" data-id="${esc(leader.id)}" aria-label="Restart linked ramps">${icon('history')}</button>`:''}<button data-action="edit-monitored" data-id="${esc(leader?.id??'')}">Edit</button><button data-action="choose-group-target" data-id="${esc(leader?.id??'')}" aria-label="Add parameter to monitored automation">${icon('plus')}</button></div></div>`;}
/** Live surface: operate the monitored target directly, plus top-level formation moves. */
function liveHTML(s:Scene,id:string){const lane=s.automation.find(l=>l.id===id)??s.automation[0];const leader=lane?automationLeader(s.automation,lane):null;const target=lane?automationTarget(s,lane.target):undefined;
 const formations=s.entities.filter(e=>e.kind==='formation'),selected=formations[0];
 const bind=target&&!target.target.startsWith('field.')?target.bind:target?.bind??'';
 const entityId=target?.entityId??'';
 const range=target?`<div class="monitor-range" ${entityId?`data-entity-id="${esc(entityId)}"`:''}><input aria-label="${esc(target.label)}" type="range" data-bind="${esc(bind)}" value="${baseValue(s,target.key??'')}" min="${target.hardMin}" max="${target.hardMax}" step="${Math.max(target.step,.001)}" ${target.target.startsWith('field.')?'':`data-entity-scope="${esc(entityId)}"`}><output data-live-target="${esc(target.target)}">—</output></div>`:'<p class="control-note">Choose an automation to operate.</p>';
 return `<div class="monitor-live"><div class="cycle-actions monitor-tabs-row"><button data-action="toggle-monitored" data-id="${esc(leader?.id??'')}" aria-label="${leader?.enabled?'Pause':'Enable'} automation group">${icon(leader?.enabled?'pause':'play')}</button>${leader?.type==='ramp'?`<button data-action="fire-lane" data-id="${esc(leader.id)}" aria-label="Restart ramp">${icon('history')}</button>`:''}<button data-action="take-manual" data-target="${esc(lane?.target??'')}">Take manual</button></div>
 ${range}
 <div class="monitor-ops"><label><span>Glyph</span><select data-action="monitor-formation">${formations.map(f=>`<option value="${esc(f.id)}" ${f.id===selected?.id?'selected':''}>${esc(f.name)}</option>`).join('')}</select></label><label><span>Sequence</span><select data-action="sequence-mode" data-entity-id="${esc(selected?.id??'')}"><option value="play" ${selected?.sequence.enabled?'selected':''}>Play</option><option value="hold" ${!selected?.sequence.enabled&&!selected?.sequence.manual?'selected':''}>Hold</option><option value="manual" ${selected?.sequence.manual?'selected':''}>Manual blend</option></select></label><button data-action="monitor-add-glyph">${icon('plus')} Glyph</button></div></div>`;}
export function monitorHTML(s:Scene,id:string,mode:MonitorMode='cycle'){const lane=s.automation.find(l=>l.id===id)??s.automation[0];if(!lane)return '';
 const head=`<div class="monitor-head"><div class="monitor-tabs" role="tablist">${(['cycle','live'] as const).map(m=>`<button role="tab" data-action="monitor-mode" data-value="${m}" aria-selected="${m===mode}">${m==='cycle'?'Cycle':'Live'}</button>`).join('')}</div><button class="icon-button monitor-dock" data-action="monitor-dock" aria-label="Dock this instrument into the toolbelt" title="Dock into the toolbelt">${icon('collapse')}</button></div>`;
 const body=mode==='live'?liveHTML(s,id):cycleHTML(s,id);
 return head+`<div class="monitor-body">${body}</div>`;}
