import type {AutomationLane} from './model';
export function automationLeader(lanes:AutomationLane[],lane:AutomationLane):AutomationLane{const seen=new Set<string>();let current=lane;while(current.syncWith){if(seen.has(current.id))throw new Error('Automation links cannot form a cycle.');seen.add(current.id);const parent=lanes.find(l=>l.id===current.syncWith);if(!parent)throw new Error('Linked automation is missing.');current=parent;}if(seen.has(current.id))throw new Error('Automation links cannot form a cycle.');return current;}
export function resolvedAutomation(lanes:AutomationLane[],lane:AutomationLane):AutomationLane{const leader=automationLeader(lanes,lane);if(leader===lane)return lane;return {...lane,type:leader.type,wave:leader.wave,rate:leader.rate,phase:leader.phase,duration:leader.duration,delay:leader.delay,loop:leader.loop,easing:leader.easing,firedAt:leader.firedAt,enabled:lane.enabled&&leader.enabled};}
export function linkAutomation(lanes:AutomationLane[],id:string,parentId:string){const lane=lanes.find(l=>l.id===id);if(!lane)throw new Error('Automation no longer exists.');const before=lane.syncWith;if(!parentId){const resolved=resolvedAutomation(lanes,lane);Object.assign(lane,resolved);delete lane.syncWith;delete lane.clockId;return;}lane.syncWith=parentId;try{automationLeader(lanes,lane);}catch(error){lane.syncWith=before;throw error;}}
export function removeAutomation(lanes:AutomationLane[],id:string){for(const lane of lanes.filter(l=>l.syncWith===id))linkAutomation(lanes,lane.id,'');return lanes.filter(l=>l.id!==id);}
export function validateAutomationLinks(lanes:AutomationLane[]){const ids=new Set<string>();for(const lane of lanes){if(ids.has(lane.id))throw new Error('Duplicate automation id.');ids.add(lane.id);if(lane.clockId!==undefined&&(typeof lane.clockId!=='string'||!lane.clockId))throw new Error('Invalid automation clock.');if(lane.syncWith!==undefined&&typeof lane.syncWith!=='string')throw new Error('Invalid automation link.');automationLeader(lanes,lane);}}
export function automationGroups(lanes:AutomationLane[]){return lanes.filter(l=>!l.syncWith).map(leader=>({leader,targets:lanes.filter(l=>automationLeader(lanes,l).id===leader.id)}));}
/** Removing the first target promotes another target without splitting the group. */
export function removeGroupTarget(lanes:AutomationLane[],id:string){const lane=lanes.find(l=>l.id===id);if(!lane)return lanes;const leader=automationLeader(lanes,lane);if(leader.id!==id)return lanes.filter(l=>l.id!==id);const targets=lanes.filter(l=>l.id!==id&&automationLeader(lanes,l).id===id),next=targets[0];if(next){Object.assign(next,resolvedAutomation(lanes,next));delete next.syncWith;next.clockId=leader.clockId??leader.nativeId??leader.id;for(const target of targets.slice(1))target.syncWith=next.id;}return lanes.filter(l=>l.id!==id);}
/** Direct manipulation offsets a replacing target's range without stopping its oscillator. */
export function offsetAutomatedTarget(lanes:AutomationLane[],target:string,delta:number){const lane=lanes.filter(l=>l.target===target&&resolvedAutomation(lanes,l).enabled).at(-1);if(!lane||lane.blend!=='replace'||!Number.isFinite(delta))return false;lane.min+=delta;lane.max+=delta;return true;}
