import {Scene} from './model';
import {stateSource,stateLabel} from './sourceState';
import {esc,icon} from './icons';
import {select,range,toggle,area,text} from './inspector';
export function imageSuiteHTML(s:Scene,entityId:string|undefined,index:number){
 const e=s.entities.find(e=>e.id===entityId&&e.kind==='formation')??s.entities.find(e=>e.kind==='formation');
 if(!e)return '<p class="control-note">Create a formation to turn an image or ASCII drawing into particles.</p><button class="secondary" data-action="source-new">New image / ASCII formation</button>';
 const k=e.sequence.steps[index]??e.sequence.steps[0],i=e.sequence.steps.indexOf(k),source=stateSource(e,i);
 return `<section class="image-suite" data-entity-id="${esc(e.id)}"><div class="two-col"><label class="control"><span>Formation</span><select data-action="source-entity" aria-label="Image suite formation">${s.entities.filter(v=>v.kind==='formation').map(v=>`<option value="${esc(v.id)}" ${v.id===e.id?'selected':''}>${esc(v.name)}</option>`).join('')}</select></label><label class="control"><span>Sequence state</span><select data-action="source-step" aria-label="Image suite sequence state">${e.sequence.steps.map((v,n)=>`<option value="${n}" ${i===n?'selected':''}>${n+1} · ${esc(stateLabel({...v,source:stateSource(e,n)}))}</option>`).join('')}</select></label></div><div class="button-row"><button class="secondary" data-action="source-new">New formation</button><button class="secondary" data-action="source-add" ${e.locked||e.sequence.steps.length>=32?'disabled':''}>Add state</button></div><fieldset ${e.locked?'disabled':''}><label class="control"><span>Build this state from</span><select data-action="source-kind" aria-label="Build this state from"><option value="none" ${!source?'selected':''}>Glyph / geometry</option><option value="image" ${source?.kind==='image'?'selected':''}>Image</option><option value="ascii" ${source?.kind==='ascii'?'selected':''}>ASCII drawing</option></select></label>
 ${source?`${text('State name','step.name',stateLabel({...k,source}),'maxlength="500"')}<figure class="source-preview-card"><img data-source-preview="${esc(e.id)}" data-source-step="${i}" alt="${esc(stateLabel({...k,source}))} sampling preview"></figure><p class="control-note" data-source-analysis="${esc(e.id)}">Sampling preview…</p>`:'<p class="control-note">Choose Image to sample a photograph or mask, or ASCII drawing to type or paste a text picture. Each becomes a state in this formation’s sequence. With the true 3D body on (Studio → 3D body &amp; depth), the sampled mark extrudes like a letterform.</p>'}
 ${source?.kind==='image'?`<button class="secondary" data-action="source-image">${icon('upload')} Choose PNG, JPEG or WebP</button><p class="control-note">${esc(source.image.name??'No image chosen')}</p>${select('Read as','step.source.image.mode',source.image.mode,[['luminance','Ink luminance'],['silhouette','Silhouette cutout'],['edgeSobel','Sobel edges']])}${range('Ink threshold','step.source.image.threshold',source.image.threshold,0,1,.01)}${range('Source scale','step.source.image.scale',source.image.scale,.1,3,.05)}${toggle('Force dark ink on light paper','step.source.image.invert',!!source.image.invert)}`:source?.kind==='ascii'?`${area('ASCII drawing','step.source.ascii.text',source.ascii.text,'maxlength="50000"')}${text('Monospace font','step.source.ascii.fontFamily',source.ascii.fontFamily??'monospace','maxlength="200"')}${range('Font size ceiling','step.source.ascii.fontSize',source.ascii.fontSize??32,8,256,1)}${toggle('Sample negative space','step.source.ascii.invert',!!source.ascii.invert)}<p class="control-note">The preview updates when an edit is applied; resume motion to let particles follow it. The complete drawing fits automatically. Line breaks, spaces and aspect ratio are preserved.</p>`:''}</fieldset><button class="secondary" data-action="source-sequence">Open formation sequence</button></section>`;
}
