import {Scene,Journey,Entity,Tool} from './model.js';
import {PARAMETERS,Parameter} from './registry.js';
import {esc,icon} from './icons.js';
export interface InspectorContext {scene:Scene;journey:Journey;selected:string[];textId:string|null;tab:'scene'|'objects'|'field'|'motion';motionTab:'sequence'|'morph'|'focus'|'automation';stepIndex:number;preview:boolean;search:string}
const button=(action:string,label:string,ico?:string,extra='')=>`<button class="secondary" data-action="${action}" ${extra}>${ico?icon(ico):''}${label}</button>`;
const heading=(s:string,sub='')=>`<div class="section-heading"><h3>${s}</h3>${sub?`<span>${sub}</span>`:''}</div>`;
const text=(label:string,path:string,value:string,options='')=>`<label class="control"><span>${label}</span><input type="text" data-bind="${path}" value="${esc(value)}" ${options}></label>`;
const area=(label:string,path:string,value:string)=>`<label class="control"><span>${label}</span><textarea data-bind="${path}" rows="3">${esc(value)}</textarea></label>`;
const numeric=(label:string,path:string,value:number,min:number,max:number,step=.1)=>`<label class="number-field"><span>${label}</span><input type="number" data-bind="${path}" value="${Math.round(value*1000)/1000}" min="${min}" max="${max}" step="${step}"></label>`;
const toggle=(label:string,path:string,value:boolean,sub='')=>`<label class="toggle-row"><span>${label}${sub?`<small>${sub}</small>`:''}</span><input type="checkbox" data-bind="${path}" ${value?'checked':''}><i aria-hidden="true"></i></label>`;
const select=(label:string,path:string,value:string,options:[string,string][])=>`<label class="control"><span>${label}</span><select data-bind="${path}">${options.map(([v,l])=>`<option value="${esc(v)}" ${v===value?'selected':''}>${esc(l)}</option>`).join('')}</select></label>`;
function range(label:string,path:string,value:number,min:number,max:number,step=.01,extra='',disabled=false){return `<div class="range-control ${disabled?'engine-required':''}"><div class="range-label"><label for="${path}">${label}</label><span class="number-wrap"><input aria-label="${label} value" type="number" data-bind="${path}" value="${Math.round(value*1000)/1000}" min="${min}" max="${max}" step="${step}" ${disabled?'disabled':''}>${extra}</span></div><input id="${path}" aria-label="${label}" type="range" data-bind="${path}" value="${value}" min="${min}" max="${max}" step="${step}" style="--fill:${(value-min)/(max-min)*100}%" ${disabled?'disabled':''}></div>`;}
function paramControl(p:Parameter,s:Scene,preview:boolean){const lanes=s.automation.filter(a=>a.enabled&&a.target==='field.'+p.key);const auto=(!preview||p.preview)?`<button class="automate-mini ${lanes.length?'has-driver':''}" data-action="automate" data-key="${p.key}" aria-label="Automate ${p.label}" title="${lanes.length?'Open its automation':'Automate this parameter'}">${icon('wave')}</button>`:'';return range(p.label,'field.params.'+p.key,s.field.params[p.key],p.min,p.max,p.step,auto,preview&&!p.preview)+(lanes.length?`<div class="driver-note">Base / <span data-live-param="${p.key}"></span> live · ${lanes.length} lane${lanes.length>1?'s':''}</div>`:'')+(p.note?`<p class="control-note">${p.note}</p>`:'');}
function group(name:string,content:string,open=false,id=name){return `<details class="control-group" data-detail="${id}" ${open?'open':''}><summary>${name}${icon('plus')}</summary><div class="group-content">${content}</div></details>`;}
const shapeOptions:[string,string][]=[['text','Glyph or word'],['ring','Ring'],['disc','Disc'],['triangle','Triangle'],['square','Plane']];
export function inspectorHTML(c:InspectorContext){const s=c.scene,e=s.entities.find(e=>e.id===c.selected[0]);
 if(c.search.trim()){const matches=PARAMETERS.filter(p=>(p.label+' '+p.group).toLowerCase().includes(c.search.toLowerCase()));return heading('Find a control',`${matches.length} results`)+matches.map(p=>`<button class="search-result" data-action="reveal-param" data-key="${p.key}"><strong>${p.label}</strong><small>Field / ${p.group}${c.preview&&!p.preview?' · engine required':''}</small>${icon('arrowRight')}</button>`).join('');}
 if(c.tab==='scene'){const t=s.text.find(t=>t.id===c.textId)??s.text[0];return `
 ${heading('Scene settings','Scene '+(c.journey.scenes.indexOf(s)+1))}
 ${text('Scene name','name',s.name,'maxlength="160"')}
 ${area('Character','character',s.character)}
 <div class="two-col">${numeric('Duration (seconds)','duration',s.duration,1,3600,1)}${numeric('Transition (seconds)','transition',s.transition,0,30,.1)}</div>
 <p class="control-note">The scene name belongs to the whole composition. Duration includes transition timing; field, objects, motion and text stay together.</p>
 ${group('Text layers',`
 <div class="text-layer-list">${s.text.map(t=>`<button data-action="select-text" data-id="${t.id}" class="layer-choice ${t.id===(c.textId??s.text[0]?.id)?'active':''}">${icon('text')} ${esc(t.title||'Text block')}${!t.visible?' · hidden':''}</button>`).join('')}</div>
 ${t?`${toggle('Show this text block','text.visible',t.visible)}${text('Small heading','text.kicker',t.kicker,'maxlength="300"')}${text('Title','text.title',t.title,'maxlength="300"')}${text('Italic line','text.italic',t.italic,'maxlength="300"')}${area('Supporting text','text.body',t.body)}
 <div class="two-col">${numeric('Type size','text.size',t.size,14,150,1)}${numeric('Block width','text.width',t.width,60,1000,5)}</div>
 ${select('Alignment','text.align',t.align,[['left','Left'],['center','Centre'],['right','Right']])}
 <div class="two-col">${numeric('Page X · 0–1','text.x',t.x,-.5,1.5,.01)}${numeric('Page Y · 0–1','text.y',t.y,-.5,1.5,.01)}</div>
 <div class="button-row">${button('move-text','Position on stage','pointer')}${button('delete-text','Remove','trash')}</div>`:''}
 ${button('add-text','Add a text block','plus')}
 <p class="control-note">Text is part of the scene, not the editor chrome. It can remain visible in presentations and captures.</p>`,true,'page-text')}
 ${group('Scene view',`<p class="control-note">Store this camera setup for this scene only. Working planes and guides stay editor-only.</p><div class="button-row">${button('keep-view','Set scene view','check')}${button('restore-view','Reset scene view','undo')}</div>`)}
 ${group('Journey settings',`${text('Journey title','journey.name',c.journey.name,'maxlength="160"')}${area('Description','journey.description',c.journey.description)}${toggle('Loop the journey','journey.loop',c.journey.loop)}<div class="button-row">${button('open-timeline','Scene strip','layers')}${button('new-scene','Add scene','plus')}</div>`,false,'journey')}
 `;}
 if(c.tab==='objects')return objects(c,e);
 if(c.tab==='motion')return motion(c,e);
 const keys=(...keys:string[])=>PARAMETERS.filter(p=>keys.includes(p.key)).map(p=>paramControl(p,s,c.preview)).join('');
 return `${heading('Field settings')}
 <div class="material-cards">${(['ink','print','round']as const).map(m=>`<button data-action="material" data-value="${m}" class="material-card ${s.field.material===m?'active':''}"><span class="grain-swatch ${m}"></span>${m==='ink'?'Ink':m==='print'?'Print':'Rounded'}</button>`).join('')}</div>
 ${keys('size','opacity','dispersion')}
 ${group('Palette and paper',`<div class="colour-swatches">${s.field.palette.map((col,i)=>`<label title="Palette stop ${i+1}"><input aria-label="Palette stop ${i+1}" type="color" value="${col}" data-palette="${i}"><span>${String(i+1).padStart(2,'0')}</span></label>`).join('')}${s.field.palette.length<8?button('add-palette','+'):''}${s.field.palette.length>2?button('remove-palette','−'):''}</div><label class="colour-field"><span>Paper / background</span><input type="color" data-bind="field.background" value="${s.field.background}"></label>${keys('grain')}<p class="control-note">Field palette → entity tint → travelling focus. Editing the palette never changes a station.</p>`,true,'palette')}
 ${group('Grain profile',keys('count','sizeBias','roundness','softness','irregularity','elongation','orientation','jitter'))}
 ${group('Density and form edges',keys('contrast','densityScale','densityPhase','edgeWeight','halo','thickness','warp'))}
 ${group('Motion and pointer',keys('speed','circulation','turbulence','turbulenceScale','depth','pointerStrength','pointerRadius'))}
 ${group('Physics',`<div class="engine-note">${icon('layers')}<p>${c.preview?'These settings belong to your production engine. They are retained in the contract, not imitated by the visual preview.':'Controls are provided by the connected field engine.'}</p></div>${PARAMETERS.filter(p=>p.group==='physics').map(p=>paramControl(p,s,c.preview)).join('')}`)}
 ${group('Continuous resonance',`<p class="control-note">One medium. A continuous band. Seven resonant stations—not seven pictures.</p><div class="resonance-band"><span></span>${['I','II','III','IV','V','VI','VII'].map(n=>`<i>${n}</i>`).join('')}</div>${keys('frequency','dominance','resonanceDamping','excitation')}<div class="engine-note"><p>${c.preview?'Your resonator connects here. Physical cymatics are intentionally unavailable in this shell preview.':'Continuous resonator supplied by the engine adapter.'}</p></div>`)}
 `;
}
function objects(c:InspectorContext,e:Entity|undefined){const s=c.scene;return `${heading('Entities',String(s.entities.length).padStart(2,'0'))}
 <div class="object-list">${s.entities.map(o=>`<button class="object-row ${c.selected.includes(o.id)?'selected':''}" data-action="select-entity" data-id="${o.id}" title="${esc(o.name)}"><span class="object-symbol" style="--tint:${o.tintWeight?o.tint:'var(--ink)'}">${o.kind==='pin'?icon('pin'):esc(o.shape==='text'?o.text:o.shape==='ring'?'◯':o.shape==='triangle'?'△':'◇')}</span><span><strong>${esc(o.name)}</strong><small>${o.kind==='pin'?'Force centre':o.sequence.enabled?'Formation · sequenced':'Formation'}</small></span>${o.locked?icon('lock'):'<i class="selection-dot"></i>'}</button>`).join('')}</div>
 <div class="button-row">${button('tool-formation','Formation','plus')}${button('tool-pin','Pin','pin')}${s.entities.length>1?button('select-all','All'):''}</div>
 ${c.selected.length>1?`<div class="selection-summary">${c.selected.length} centres selected · Shift-click to change selection.</div>`:''}
 ${e&&c.selected.length===1?entityControls(c,e):!s.entities.length?'<div class="empty-note">Choose a formation or pin, then click where it belongs.</div>':''}
 ${group('Arrangement',`<p class="control-note">Applies to ${c.selected.length?'the selected '+c.selected.length+' centre'+(c.selected.length>1?'s':''):'all unlocked centres'}. Identities, tints and sequences stay intact.</p><div class="layout-grid">${['line','column','ring','grid','spiral'].map(l=>`<button data-action="arrange" data-value="${l}">${l}</button>`).join('')}</div><div class="button-row">${button('chakra-add','Add seven centres','plus')}</div>${select('Layout plane','composition.plane',s.composition.plane,[['XY','XY'],['XZ','XZ'],['YZ','YZ']])}`,c.selected.length>1,'arrange')}`;}
function entityControls(c:InspectorContext,e:Entity){const s=c.scene;const total=s.entities.filter(x=>x.kind==='formation').reduce((n,x)=>n+x.share,0)||1;return `${heading(e.kind==='pin'?'Pin settings':'Formation settings')}
 ${text('Name','entity.name',e.name,'maxlength="160"')}
 <div class="three-col">${numeric('X','entity.position.x',e.position.x,-100,100,.01)}${numeric('Y','entity.position.y',e.position.y,-100,100,.01)}${numeric('Z','entity.position.z',e.position.z,-100,100,.01)}</div>
 ${toggle('Lock editing','entity.locked',e.locked,'Does not pause its motion')}
 ${e.kind==='formation'?`
 ${select('Form','entity.shape',e.shape,shapeOptions)}
 ${e.shape==='text'?`<label class="glyph-draft"><span>Glyph or word</span><input aria-label="Glyph or word" data-bind="entity.text" value="${esc(e.text)}" maxlength="120" placeholder="O"><small>Type freely. Enter or blur commits.</small></label><div class="glyph-shortcuts">${['O','I','&','∞','✧','◯'].map(g=>`<button data-action="set-glyph" data-value="${esc(g)}">${esc(g)}</button>`).join('')}</div>`:''}
 <div class="two-col">${numeric('Width','entity.size.x',e.size.x,.01,20,.01)}${numeric('Height','entity.size.y',e.size.y,.01,20,.01)}</div>
 ${range('Rotation','entity.rotation',e.rotation,-180,180,1)}
 ${range('Particle share','entity.share',e.share,0,10,.1)}<p class="control-note">${Math.round(e.share/total*100)}% of formation particles. Pins take no allocation.</p>
 <label class="colour-field"><span>Local tint</span><input type="color" data-bind="entity.tint" value="${e.tint}"></label>${range('Tint contribution','entity.tintWeight',e.tintWeight,0,1)}
 <div class="button-row">${button('entity-sequence','Edit its sequence','wave')}</div>
 `:''}
 ${group('Force profile',`<div class="segmented">${(['attract','repel','vortex']as const).map(k=>`<button data-action="force-kind" data-value="${k}" class="${e.force.kind===k?'active':''}">${k[0].toUpperCase()+k.slice(1)}</button>`).join('')}</div>${range('Strength','entity.force.strength',e.force.strength,0,5)}${range('Falloff radius','entity.force.radius',e.force.radius,.02,2)}${range('Spin','entity.force.spin',e.force.spin,-3,3)}<p class="control-note">${c.preview?'A spatial deformation preview. Production forces will act through your shared particle medium.':'Force profiles sum over the shared medium.'}</p>`,e.kind==='pin','influence')}
 ${e.kind==='formation'?group('Station assignment',`${select('Station link','entity.station',e.station===null?'none':String(e.station),[['none','No station link'],...Array.from({length:7},(_,i)=>[String(i),'Station '+(i+1)]as [string,string])])}<p class="control-note">A stored association, not a local frequency generator. Selecting this entity does not tune the shared field.</p>`):''}
 <div class="button-row">${button('duplicate-entity','Duplicate','copy')}${button('delete-entity','Remove','trash')}</div>`;}
function motion(c:InspectorContext,e:Entity|undefined){const s=c.scene;const tab=c.motionTab;let out=`<div class="motion-tabs">${(['sequence','morph','focus','automation']as const).map(t=>`<button data-action="motion-tab" data-value="${t}" class="${t===tab?'active':''}">${t[0].toUpperCase()+t.slice(1)}</button>`).join('')}</div>`;
 if(tab==='sequence'){e=e??s.entities.find(e=>e.kind==='formation');if(!e)return out+'<div class="empty-note">Place a formation to edit its sequence.</div>';
 const k=e.sequence.steps[Math.min(c.stepIndex,e.sequence.steps.length-1)];out+=`${heading('Sequence editor')}
 <label class="control"><span>Formation</span><select data-action="sequence-entity">${s.entities.filter(e=>e.kind==='formation').map(o=>`<option value="${o.id}" ${o.id===e!.id?'selected':''}>${esc(o.name)}</option>`).join('')}</select></label>
 ${toggle('Sequence enabled','entity.sequence.enabled',e.sequence.enabled)}
 ${select('Advance with','entity.sequence.clock',e.sequence.clock,[['seconds','Seconds · individual holds & transitions'],['morph','Morph clock · one θ cycle per link']])}
 <p class="control-note">${e.sequence.clock==='morph'?'One toroidal cycle advances one link. Dwell reserves the hold portion.':'Every entity can keep its own sequence on the shared simulation clock.'}</p>
 <div class="sequence-chain">${e.sequence.steps.map((k,i)=>`<button data-action="select-step" data-index="${i}" class="${i===c.stepIndex?'active':''}" data-step-live="${i}"><span>${esc(k.shape==='text'?k.text:k.shape==='ring'?'◯':k.shape==='triangle'?'△':'◇')}</span><small>${String(i+1).padStart(2,'0')}</small></button>`).join('')}<button data-action="add-step" aria-label="Add sequence step">${icon('plus')}</button></div>
 ${k?`${heading('Step '+(c.stepIndex+1))}${select('Form','step.shape',k.shape,shapeOptions)}${text('Glyph / word','step.text',k.text,'maxlength="120"')}<div class="two-col">${numeric('Hold · s','step.hold',k.hold,0,120,.1)}${numeric('Transition · s','step.transition',k.transition,.05,120,.1)}</div>
 <div class="button-row">${button('place-keyframe',k.position?'Move keyframe':'Place a keyframe','pin')}${button('delete-step','Remove link','trash')}</div>${k.position?`<div class="three-col">${numeric('Offset X','step.position.x',k.position.x,-100,100,.01)}${numeric('Offset Y','step.position.y',k.position.y,-100,100,.01)}${numeric('Offset Z','step.position.z',k.position.z,-100,100,.01)}</div>${button('clear-keyframe','Clear position keyframe')}`:''}`:''}
 <p class="control-note">Keyframes are offsets from the entity centre. Moving the entity moves its whole path. Editing a link never seeks or resets the simulation.</p>`;
 }else if(tab==='morph'){out+=`${heading('Morph timing')}<div class="phase-instrument"><div><svg viewBox="0 0 100 100"><circle cx="50" cy="50" r="38"/><line data-phase="theta" x1="50" y1="50" x2="50" y2="16"/><text x="50" y="57">θ</text></svg><span>Toroidal</span></div><div><svg viewBox="0 0 100 100"><circle cx="50" cy="50" r="38"/><line data-phase="phi" x1="50" y1="50" x2="50" y2="16"/><text x="50" y="57">φ</text></svg><span>Poloidal</span></div></div><div class="drive-track"><i id="drive-value"></i></div><p class="control-note">Both phases follow engine simulation time. They do not acquire separate timers.</p>
 ${range('Toroidal rate · Hz','morph.thetaRate',s.morph.thetaRate,0,1,.01)}${range('Poloidal rate · Hz','morph.phiRate',s.morph.phiRate,0,1,.01)}
 ${range('Dwell ratio','morph.dwell',s.morph.dwell,0,.95,.01)}${range('Drive depth','morph.depth',s.morph.depth,0,2,.01)}
 ${select('Interference law','morph.law',s.morph.law,[['theta','θ only'],['product','Product · θ × φ'],['sum','Sum · θ + φ'],['beat','Beat · θ − φ']])}
 ${group('Phase offsets',`${range('θ offset · turns','morph.thetaOffset',s.morph.thetaOffset,-2,2,.01)}${range('φ offset · turns','morph.phiOffset',s.morph.phiOffset,-2,2,.01)}`)}
 <div class="engine-note"><p>The phase instrument and sequence clock are live here. Hopf geometry and physical morph response belong to the production adapter.</p></div>`;
 }else if(tab==='focus'){out+=`${heading('Focus route')}${select('Orchestration','composition.focus',s.composition.focus,[['parallel','Parallel · all centres together'],['travelling','Travelling focus · follow the route']])}${range('Seconds per centre','composition.focusDuration',s.composition.focusDuration,.2,20,.1)}${toggle('Carry local tint','composition.carryTint',s.composition.carryTint)}${toggle('Follow station links','composition.carryStation',s.composition.carryStation,c.preview?'Stored for the resonant engine':'Drives the shared resonator when focus owns tuning')}
 <div class="focus-route">${s.entities.filter(e=>e.kind==='formation').map((e,i)=>`<div data-focus-entity="${e.id}"><span class="route-number">${i+1}</span><i style="background:${e.tint}"></i><strong>${esc(e.name)}</strong><button data-action="route-up" data-id="${e.id}" aria-label="Move ${esc(e.name)} earlier">↑</button><button data-action="route-down" data-id="${e.id}" aria-label="Move ${esc(e.name)} later">↓</button></div>`).join('')}</div><p class="control-note">Reordering attention does not rearrange positions. Station association and spatial centre remain separate.</p>`;
 }else{out+=`${heading('Automation lanes')}<p class="control-note">Lanes evaluate over base values. They never overwrite them. Open a lane from the wave icon beside a parameter.</p>
 ${s.automation.map((l,i)=>`<div class="automation-lane"><div class="lane-heading"><span>LANE ${String(i+1).padStart(2,'0')}</span><button data-action="delete-lane" data-id="${l.id}" aria-label="Remove lane">${icon('close')}</button></div>
 ${toggle('Active','lane.'+l.id+'.enabled',l.enabled)}
 ${select('Target','lane.'+l.id+'.target',l.target,PARAMETERS.filter(p=>!c.preview||p.preview).map(p=>['field.'+p.key,p.label]))}
 ${select('Behaviour','lane.'+l.id+'.type',l.type,[['lfo','Continuous oscillator'],['ramp','One-shot ramp']])}
 ${l.type==='lfo'?select('Wave','lane.'+l.id+'.wave',l.wave,[['sine','Sine'],['triangle','Triangle'],['square','Square'],['saw','Saw'],['steps','Stepped'],['smooth','Smooth irregular']]):''}
 <div class="two-col">${numeric('Minimum','lane.'+l.id+'.min',l.min,-100000,100000,.01)}${numeric('Maximum','lane.'+l.id+'.max',l.max,-100000,100000,.01)}</div>
 ${l.type==='lfo'?`<div class="two-col">${numeric('Rate · Hz','lane.'+l.id+'.rate',l.rate,0,20,.01)}${numeric('Phase','lane.'+l.id+'.phase',l.phase,-100,100,.01)}</div>`:`<div class="two-col">${numeric('Duration · s','lane.'+l.id+'.duration',l.duration,.05,300,.1)}${numeric('Delay · s','lane.'+l.id+'.delay',l.delay,0,300,.1)}</div>${select('Repeat','lane.'+l.id+'.loop',l.loop,[['once','Once'],['loop','Loop'],['pingpong','Ping-pong']])}${button('fire-lane','Fire ramp','play',`data-id="${l.id}"`)}`}
 ${select('Combine','lane.'+l.id+'.blend',l.blend,[['replace','Replace evaluated value'],['add','Add to base'],['multiply','Multiply base']])}
 </div>`).join('')}${button('add-lane','Add automation','plus')}`;
 }return out;
}
