import {stateLabel,stateSource,stateThumbnail} from './sourceState';
import {isShared,POINTER_PATHS} from './sharedSettings';
import {automationEditor} from './automationEditor';
import {resolvedAutomation,automationLeader} from './automationLinks';
import {formationSummary} from './workspacePreferences';
import {Scene,Journey,Entity,SequenceStep} from './model.js';
import {PARAMETERS,Parameter} from './registry.js';
import {baseValue,nativeBinding,entityTargets,automationTargets,automationTarget,AutomationTarget,entityCycleGroups,pinCycleClockId} from './nativeParameters.js';
import {CANONICAL_CHAKRAS} from '../../src/engine/chakraSystem';
import {CHAKRA_DEFINITIONS} from '../../src/engine/semantics/chakraSemantics';
import {FONT_OPTIONS,CUSTOM_SENTINEL,resolveFontOption} from './fontCatalog.js';
import {esc,icon} from './icons.js';
export interface InspectorContext {scene:Scene;journey:Journey;selected:string[];textId:string|null;tab:'scene'|'objects'|'field'|'motion';motionTab:'sequence'|'morph'|'focus'|'automation';stepIndex:number;preview:boolean;search:string;customFont?:boolean;supported?:string[];pinned?:string[];stations?:{id?:string;index:number;name:string;frequencyHz:number;m:number;n:number;color:string;energy?:number;semanticNodeId?:string;affinity?:number}[];automationLoop?:boolean;fieldPaused?:boolean}
const button=(action:string,label:string,ico?:string,extra='')=>`<button class="secondary" data-action="${action}" ${extra}>${ico?icon(ico):''}${label}</button>`;
const heading=(s:string,sub='')=>`<div class="section-heading"><h3>${s}</h3>${sub?`<span>${sub}</span>`:''}</div>`;
export const text=(label:string,path:string,value:string,options='')=>`<label class="control"><span>${label}</span><input type="text" data-bind="${path}" value="${esc(value)}" ${options}></label>`;
export const area=(label:string,path:string,value:string)=>`<label class="control"><span>${label}</span><textarea data-bind="${path}" rows="3">${esc(value)}</textarea></label>`;
export const numeric=(label:string,path:string,value:number,min:number,max:number,step=.1)=>`<label class="number-field"><span>${label}</span><input type="number" data-bind="${path}" value="${Number(value.toPrecision(12))}" min="${min}" max="${max}" step="${step}"></label>`;
export const toggle=(label:string,path:string,value:boolean,sub='')=>`<label class="toggle-row"><span>${label}${sub?`<small>${sub}</small>`:''}</span><input type="checkbox" data-bind="${path}" ${value?'checked':''}><i aria-hidden="true"></i></label>`;
export const select=(label:string,path:string,value:string,options:[string,string][])=>`<label class="control"><span>${label}</span><select data-bind="${path}">${options.map(([v,l])=>`<option value="${esc(v)}" ${v===value?'selected':''}>${esc(l)}</option>`).join('')}</select></label>`;
export function range(label:string,path:string,value:number,min:number,max:number,step=.01,extra='',disabled=false,hardMin=min,hardMax=max,scale?:string){
 const log=scale==='log'&&min>0,fill=Math.max(0,Math.min(1,log?(Math.log(Math.max(min,value))-Math.log(min))/(Math.log(max)-Math.log(min)):(value-min)/(max-min)));
 return `<div class="range-control ${disabled?'engine-required':''}" data-control="${esc(path)}"><div class="range-label"><label for="${esc(path)}">${label}</label><span class="number-wrap"><input aria-label="${label} value" type="number" data-bind="${esc(path)}" value="${Number(value.toPrecision(12))}" min="${hardMin}" max="${hardMax}" step="${step}" ${disabled?'disabled':''}>${extra}</span></div><div class="range-track"><input id="${esc(path)}" aria-label="${label}" type="range" data-bind="${esc(path)}" value="${log?fill:value}" min="${log?0:min}" max="${log?1:max}" step="${log?.001:step}" ${log?`data-log-min="${min}" data-log-max="${max}" data-value-step="${step}"`:''} style="--fill:${fill*100}%" ${disabled?'disabled':''}></div></div>`;
}
function automationTools(target:string,label:string,s:Scene,shared=false){const lanes=s.automation.map(a=>resolvedAutomation(s.automation,a)).filter(a=>a.enabled&&a.target===target);return `<button class="automate-mini ${lanes.length?'has-driver':''}" data-action="automate" data-target="${esc(target)}" aria-label="Automate ${esc(label)}" title="${shared?'Use local mode to automate this parameter in a scene':'Open automation for this parameter'}" ${shared?'disabled':''}>${icon('wave')}</button>`;}
function driver(target:string,s:Scene){const t=automationTarget(s,target),lanes=s.automation.map(a=>resolvedAutomation(s.automation,a)).filter(a=>a.enabled&&a.target===target);if(!t||!lanes.length)return '';return `<div class="driver-note">Drag to offset range · Current <span data-live-target="${esc(target)}">—</span> · ${lanes.length>1?'last of '+lanes.length+' lanes':lanes[0].type==='lfo'?(lanes[0].wave==='morph'?'Morph drive':'LFO'):'Ramp'}<button data-action="take-manual" data-target="${esc(target)}">Take manual control</button></div>`;}
export function paramControl(p:Parameter,c:InspectorContext){const s=c.scene,unsupported=!p.preview?'Retained preview parameter':c.supported&&!c.supported.includes(p.key)?'The connected adapter does not implement this parameter.':undefined;const target='field.'+p.key;
 const shared=isShared(c.journey,s,p.bind);const extra=!unsupported?`<button class="global-mini" data-action="toggle-global" data-path="${p.bind}" aria-pressed="${shared}" aria-label="${shared?'Use local':'Share'} ${esc(p.label)} ${shared?'value':'across expression'}" title="${shared?'Shared across the expression; overrides scene automation':'Make this property global across the expression'}" ${POINTER_PATHS.includes(p.bind)?'disabled':''}>${icon('globe')}</button>`+automationTools(target,p.label,s,shared)+`<button class="favourite-mini" data-action="favourite" data-key="${p.key}" aria-label="${c.pinned?.includes(p.key)?'Remove':'Add'} ${p.label} ${c.pinned?.includes(p.key)?'from':'to'} toolbelt" title="Add to or remove from toolbelt">${c.pinned?.includes(p.key)?'★':'☆'}</button>`:'';
 const grainOff=p.bind.startsWith('field.params.')&&nativeBinding(p.key)?.path.startsWith('material.')&&s.engine.grainProfile===false;
 return range(p.label+(p.unit?' · '+p.unit:''),p.bind,baseValue(s,p.key),p.min,p.max,p.step,extra,!!unsupported||grainOff,p.hardMin,p.hardMax,p.scale)+driver(target,s)+(unsupported||p.note?`<p class="control-note">${esc(unsupported??p.note??'')}</p>`:'');
}
export function entityControl(c:InspectorContext,path:string,label?:string){const t=entityTargets(c.scene).find(t=>t.entityId===c.selected[0]&&t.bind===path);if(!t)return '';const l=label??t.label.split(' · ').at(-1)!;return range(l,path,t.value,t.min,t.max,t.step,automationTools(t.target,l,c.scene)+`<button class="favourite-mini" data-action="pin-entity" data-key="${esc(t.key)}" aria-label="Add ${esc(l)} to toolbelt" title="Add to toolbelt">☆</button>`,false,t.hardMin,t.hardMax)+driver(t.target,c.scene);}
function group(name:string,content:string,open=false,id=name){return `<details class="control-group" data-detail="${id}" ${open?'open':''}><summary>${name}${icon('plus')}</summary><div class="group-content">${content}</div></details>`;}
const shapeOptions:[string,string][]=[['text','Glyph or word'],['ring','Ring'],['disc','Disc'],['triangle','Triangle'],['square','Plane'],['yantra','Canonical yantra'],['cymatic','Authored cymatic template']];
function shapeFields(shape:Pick<Entity,'shape'|'text'|'yantraId'|'templateFrequency'>,prefix:string){return select('Formation',prefix+'.shape',shape.shape,shapeOptions)+(shape.shape==='text'?text('Glyph or word',prefix+'.text',shape.text,'maxlength="120"') : shape.shape==='yantra'?select('Yantra',prefix+'.yantraId',shape.yantraId??'anahata',CANONICAL_CHAKRAS.map(ch=>[ch.id,ch.name])):shape.shape==='cymatic'?numeric('Authored template frequency · Hz',prefix+'.templateFrequency',shape.templateFrequency??396,1,100000,1)+'<p class="control-note">A sampled target geometry, not an independent physical resonator. Shared frequency remains in Field → Resonance.</p>':'');}
const keys=(c:InspectorContext,...ks:string[])=>ks.map(k=>PARAMETERS.find(p=>p.key===k)).filter((p):p is Parameter=>!!p).map(p=>paramControl(p,c)).join('');
const inGroup=(c:InspectorContext,g:string,except:string[]=[])=>PARAMETERS.filter(p=>p.group===g&&!except.includes(p.key)).map(p=>paramControl(p,c)).join('');
/** Glyph sampling: a curated typeface chooser over device font stacks, with a free-text escape
 *  hatch that only exists while the custom entry is chosen, plus a live preview of the stack. */
function glyphSamplingControls(s:Scene,customChosen:boolean){
 const resolved=resolveFontOption(s.engine.fontFamily),active=customChosen?CUSTOM_SENTINEL:resolved.optionId,weight=String(s.engine.fontWeight??900);
 const chooser=`<label class="control"><span>Typeface · installed on this device</span><select data-action="font-family" aria-label="Typeface">${FONT_OPTIONS.map(o=>`<option value="${esc(o.id)}" ${o.id===active?'selected':''}>${esc(o.note?o.label+' · '+o.note:o.label)}</option>`).join('')}<option value="${CUSTOM_SENTINEL}" ${active===CUSTOM_SENTINEL?'selected':''}>Custom stack…</option></select></label>`;
 const custom=active===CUSTOM_SENTINEL?text('Custom font stack','engine.fontFamily',s.engine.fontFamily??'','maxlength="200"'):'';
 const preview=`<p class="control-note" style="font-family:${esc(resolved.stack)};font-weight:${esc(weight)}">O · I · &amp; · Open 0123 — the quick brown ink</p>`;
 return `${chooser}${custom}${select('Font weight','engine.fontWeight',String(s.engine.fontWeight??900),[['400','Regular'],['600','Semibold'],['700','Bold'],['900','Heavy']])}${preview}<p class="control-note">The typeface is a stack of fonts already installed here; nothing is downloaded. Text and font edits renormalise state sizes around the new glyph while auto-fit is on. Family and weight changes rebuild target geometry only — particle positions and simulation time are retained.</p>`;
}
export function inspectorHTML(c:InspectorContext){const s=c.scene,e=s.entities.find(e=>e.id===c.selected[0]);
 if(c.search.trim()){
  const query=c.search.trim().toLowerCase(),matches=PARAMETERS.filter(p=>(p.label+' '+p.group+' '+p.key).toLowerCase().includes(query));
  const targets=entityTargets(s).filter(t=>(t.label+' '+t.key).toLowerCase().includes(query));
  return heading('Find a control',`${matches.length+targets.length} results`)+matches.map(p=>paramControl(p,c)).join('')+targets.map(t=>`<section data-entity-id="${esc(t.entityId!)}"><p class="control-note">${esc(s.entities.find(e=>e.id===t.entityId)!.name)}</p>${entityControl({...c,selected:[t.entityId!]},t.bind).replaceAll(`id="${t.bind}"`,`id="search-${esc(t.entityId!)}-${t.bind}"`).replaceAll(`for="${t.bind}"`,`for="search-${esc(t.entityId!)}-${t.bind}"`)}</section>`).join('');
 }
 if(c.tab==='scene'){const t=s.text.find(t=>t.id===c.textId)??s.text[0];return `
 ${heading('Scene settings','Scene '+(c.journey.scenes.indexOf(s)+1))}
 ${text('Scene name','name',s.name,'maxlength="160"')}
 ${area('Character','character',s.character)}
 <div class="two-col">${numeric('Duration (seconds)','duration',s.duration,1,3600,1)}${numeric('Transition (seconds)','transition',s.transition,0,30,.1)}</div>
 <p class="control-note">The scene name belongs to the whole composition. Duration includes transition timing; field, objects, motion and text stay together.</p>
 ${group('Text layers',`
 <div class="text-layer-list">${s.text.map(t=>`<button data-action="select-text" data-id="${t.id}" class="layer-choice ${t.id===(c.textId??s.text[0]?.id)?'active':''}">${icon('text')} ${esc(t.title||'Text block')}${!t.visible?' · hidden':''}</button>`).join('')}</div>
 ${t?`${toggle('Show this text block','text.visible',t.visible)}${text('Small heading','text.kicker',t.kicker,'maxlength="300"')}${text('Title','text.title',t.title,'maxlength="300"')}${text('Italic line','text.italic',t.italic,'maxlength="300"')}${area('Supporting text','text.body',t.body)}
 <div class="two-col">${numeric('Type size','text.size',t.size,14,150,1)}${numeric('Block width','text.width',t.width,60,1000,5)}</div>
 ${select('Alignment','text.align',t.align,[['left','Left'],['center','Centre'],['right','Right']])}
 <div class="two-col">${numeric('Page X · 0–1','text.x',t.x,-.5,1.5,.01)}${numeric('Page Y · 0–1','text.y',t.y,-.5,1.5,.01)}</div>
 <div class="button-row">${button('move-text','Position on stage','pointer')}${button('delete-text','Remove','trash')}</div>`:''}
 ${button('add-text','Add a text block','plus')}
 <p class="control-note">Text is part of the scene, not the editor chrome. It can remain visible in presentations and captures.</p>`,true,'page-text')}
 ${group('Scene view',`<p class="control-note">Store this camera setup for this scene only. Working planes and guides stay editor-only.</p><div class="button-row">${button('keep-view','Set scene view','check')}${button('restore-view','Reset scene view','undo')}</div>`)}
 ${group('Expression settings',`${text('Expression title','journey.name',c.journey.name,'maxlength="160"')}${area('Description','journey.description',c.journey.description)}${toggle('Loop the expression','journey.loop',c.journey.loop)}<div class="button-row">${button('open-timeline','Scene strip','layers')}${button('new-scene','Add scene','plus')}</div>`,false,'journey')}
 `;}

 if(c.tab==='objects')return objects(c,e);
 if(c.tab==='motion')return motion(c,e);
 const stations=c.stations??[],min=stations.length?Math.max(1,stations[0].frequencyHz*.65):20,max=stations.length?stations.at(-1)!.frequencyHz*1.15:4000;
 return `${heading('The shared field')}
 ${s.favourites?.length?`<div class="favourites-strip" aria-label="Favourite controls">${s.favourites.map(k=>`<button data-action="reveal-param" data-key="${esc(k)}">${esc(PARAMETERS.find(p=>p.key===k)?.label??k)}</button>`).join('')}</div>`:''}
 <div class="material-cards">${(['ink','print','round']as const).map(m=>`<button data-action="material" data-value="${m}" class="material-card ${s.field.material===m?'active':''}"><span class="grain-swatch ${m}"></span>${m==='ink'?'Ink':m==='print'?'Print':'Rounded'}</button>`).join('')}</div>
 ${keys(c,'size','opacity')}
 ${group('Palette and paper',`<div class="colour-swatches">${s.field.palette.map((col,i)=>`<label title="Palette stop ${i+1}"><input aria-label="Palette stop ${i+1}" type="color" value="${col}" data-palette="${i}"><span>${String(i+1).padStart(2,'0')}</span></label>`).join('')}${s.field.palette.length<8?button('add-palette','+'):''}${s.field.palette.length>2?button('remove-palette','−'):''}</div>
 <label class="colour-field"><span>Paper / background</span><input type="color" data-bind="field.background" value="${s.field.background}"></label>
 ${select('Atmosphere','engine.backgroundMode',s.engine.backgroundMode??'solid',[['solid','Solid paper'],['vignette','Vignette'],['ambientGlow','Ambient glow'],['adaptive','Adaptive glow']])}
 ${toggle('Palette field','engine.colorEnabled',s.engine.colorEnabled,'When off, the native monochrome ink remains')}
 ${select('Colour distribution','engine.colorMode',s.engine.colorMode,[['monochrome','One ink'],['linearGradient','Linear gradient'],['radialGradient','Radial gradient'],['angularSweep','Angular sweep'],['velocityThermal','Velocity thermal'],['densityDepth','Density / depth'],['waveInterference','Wave interference'],['rainbowSpectral','Spectral rainbow']])}
 ${group('Palette dynamics',inGroup(c,'color'))}${s.semanticField?.bindings.length?`<div class="semantic-field-summary"><label class="toggle-row"><span>Semantic spatial colour field</span><input type="checkbox" data-semantic-global="enabled" ${s.semanticField.enabled?'checked':''}><i></i></label><label class="control"><span>Global semantic colour gain</span><input type="number" data-semantic-global="globalColorGain" min="0" max="100" step=".01" value="${s.semanticField.globalColorGain}"></label><p class="control-note">This downstream field is spatial and independent of particle ownership. Ordinary palette, local tint and focus tint remain intact.</p></div>`:''}<p class="control-note">Field palette → entity tint → travelling-focus contribution → optional semantic spatial colour. These layers remain independent.</p>`,false,'palette')}
 ${group('Mark profile',`${keys(c,'count','native_particleSize__min')}${toggle('Extended grain profile','engine.grainProfile',s.engine.grainProfile!==false,'Uses the native mark shader, not another simulation')}${select('Native dot shape','engine.dotShape',s.engine.dotShape??'circle',[['circle','Circle'],['square','Square']])}<p class="control-note">With the extended profile enabled, Roundness continuously shapes the mark; the basic dot shape is used by the classic profile. Very large marks are capped by this device’s GPU point-size limit.</p>${inGroup(c,'material',['count','size','opacity','native_particleSize__min'])}${group('Glyph sampling',glyphSamplingControls(s,c.customFont===true))}`,false,'material')}
 ${group('3D body & depth',`${toggle('True 3D body — glyphs & sources','engine.volumeEnabled',s.engine.volumeEnabled===true,'Builds every planar mark — letterforms, yantras, primitives, cymatic plates, image masks and ASCII drawings — as a solid with real thickness instead of a flat card with depth noise')}<p class="control-note">With the volume on, a glyph or a sampled source is a solid body: extruded flanks at its contour, front and back sheets, and an interior band. Depth is then real geometry — the physics stops flattening it and the collision wall becomes the boundary of the extruded solid. Switching this on re-derives every loaded image and ASCII source, so existing masks gain their bodies without re-uploading.</p>${inGroup(c,'volume')}${select('Depth profile','engine.volumeProfile',s.engine.volumeProfile??'round',[['slab','Slab · constant thickness'],['bevel','Bevel · chamfered from the contour'],['round','Round · pillow, steep shoulders'],['dome','Dome · convex bulge'],['taper','Taper · knife-edge sliver']])}<p class="control-note">Presets that seed the body: slab is a straight extrusion; bevel chamfers from the contour like an embossed die; round and dome inflate it. Profile Reach renormalizes the stroke width the profile is measured against.</p>${range('Depth in the swirl','engine.vortex3d',s.engine.vortex3d??0,0,1,.01)}${range('Depth in the bridge','engine.dispersion3d',s.engine.dispersion3d??0,0,1,.01)}<p class="control-note">The global vortex and the inter-glyph dispersion act in the picture plane by default. Raising these turns them through the body's depth axis — a helical swirl and a bridge that opens in depth. Only active while the volume is on.</p>${group('Projection & aerial depth',`${toggle('Perspective projection','engine.depthPerspective',s.engine.depthPerspective===true,'Real convergence. Off is the original parallel drawing instrument')}${select('Surfaces occlude','engine.depthOcclusion',s.engine.depthOcclusion?'on':'off',[['off','No · every mark draws'],['on','Yes · near bodies occlude far']])}<p class="control-note">An orthographic camera has no convergence, so distance cannot change a mark's size or tone. Perspective plus the attenuation and aerial-perspective controls below are what make depth legible.</p>${inGroup(c,'depth')}`)}`,false,'volume')}
 ${group('Physics',`<label class="toggle-row"><span>Pause physics<small>Hold the field's motion — particles, forces and morph freeze; every control and the playhead keep working</small></span><input type="checkbox" id="pause-physics" aria-label="Pause physics" ${c.fieldPaused?'checked':''}><i aria-hidden="true"></i></label>${inGroup(c,'motion')}${select('Physical medium plane','engine.mediumPlane',s.engine.mediumPlane,[['vertical','XY · vertical'],['horizontal','XZ · horizontal']])}<p class="control-note">Changes target and resonator orientation. It is independent of the camera and working plane.</p>${inGroup(c,'physics')}`,false,'physics')}
 ${group('Pointer',`<label class="control"><span>Pointer settings</span><select id="pointer-scope" aria-label="Pointer scope"><option value="global" ${s.pointerScope!=='local'?'selected':''}>Expression override · global</option><option value="local" ${s.pointerScope==='local'?'selected':''}>Local to this scene</option></select></label>${select('Temporary pointer force','engine.pointerMode',s.engine.pointerMode,[['attract','Attract'],['repel','Repel'],['vortex','Vortex']])}${inGroup(c,'pointer')}${select('Click effect','engine.pointerClick',s.engine.pointerClick??'pulse',[['pulse','Pulse · shockwave outward'],['implode','Implode · gather inward'],['vortex','Vortex · whirl around the click'],['shove','Shove · random burst'],['off','Off · clicks stay quiet']])}<p class="control-note">Active only with Interact. Holding the button applies the temporary force; a click fires the chosen effect at the pointer, with its own strength and radius. Scroll zooms the view.</p>`,false,'pointer')}
 ${group('Continuous resonance',`${toggle('Resonant medium','engine.resonanceEnabled',s.engine.resonanceEnabled)}<p class="resonance-readout"><strong data-resonance-live>— Hz</strong><span data-resonance-driver>${esc(s.composition.frequencyDriver)}</span></p>
 ${select('Shared frequency is driven by','composition.frequencyDriver',s.composition.frequencyDriver,[['manual','Manual tuning'],['focus','Travelling focus'],['automation','Automation / station sweep']])}
 <div class="tuning-instrument">${range('Continuous tuning band · Hz','field.params.frequency',baseValue(s,'frequency'),min,max,1,automationTools('field.frequency','Shared frequency',s),false,1,100000)}<div class="station-ticks">${stations.map(st=>`<button data-action="tune-station" data-index="${st.index}" title="${esc(st.name)} · ${st.frequencyHz.toFixed(1)} Hz · (${st.m}, ${st.n})${st.affinity!==undefined?' · affinity '+(st.affinity*100).toFixed(1)+'%':''}" aria-label="Tune ${esc(st.name)} station ${st.index+1}" style="--station-row:${st.index%2};--station:${Math.max(0,Math.min(100,(st.frequencyHz-min)/(max-min)*100))}%"><i></i><small>${st.index+1}</small></button>`).join('')}</div></div>
 <p class="control-note">Anchors come from the active modal plate. When a semantic profile is active, its names and colours are projected onto those physical anchors; the resonator itself remains semantically ignorant. Tuning preserves its evolving envelopes.</p>
 ${driver('field.frequency',s)}${keys(c,'dominance')}${toggle('Sweep linked stations','engine.autoSweep',s.engine.autoSweep,'Runs only while Automation owns the shared frequency')}
 ${select('Sweep direction','engine.sweepDirection',s.engine.sweepDirection,[['ascent','Ascending'],['descent','Descending'],['pingpong','There and back']])}
 ${inGroup(c,'resonance',['frequency','dominance'])}${group('Compatibility',select('Medium implementation','engine.resonatorMode',s.engine.resonatorMode??'resonator',[['resonator','Continuous modal resonator'],['template','Legacy templates · no live medium']])+'<p class="control-note">Legacy template mode disables modal transport. Authored templates are still ordinary formation geometry.</p>')}`,false,'resonance')}
 ${group('Relational forces',`${toggle('Dynamic relational centres','engine.relationalEnabled',s.engine.relationalEnabled)}${select('Relational law','engine.relationalMode',s.engine.relationalMode,[['orbital','Orbital'],['nbody','N-body'],['chaos','Chaotic']])}${inGroup(c,'relational')}<p class="control-note">These are the native dynamic attractors acting on the shared field, not implied links between your named entities.</p>`,false,'relational')}
 ${group('Shared collision medium',`${toggle('Collision medium','engine.mediumEnabled',s.engine.mediumEnabled===true)}${inGroup(c,'medium')}<p class="control-note">A coarse Eulerian pressure field that particles charge with their own motion and are then pushed around by: crowds repel, wakes propagate, opposing flows collide, and bursts travel as pressure waves. Every force in the field stirs it. Off preserves the classic field exactly.</p>`,false,'medium')}
 ${group('Glyph colliders',`${toggle('Glyph walls','engine.collisionEnabled',s.engine.collisionEnabled===true)}${select('Wall law','engine.collisionMode',s.engine.collisionMode??'obstacle',[['obstacle','Obstacle · strokes are solid to visitors'],['vessel','Vessel · strokes contain their own grain']])}${inGroup(c,'collision')}<p class="control-note">Each formation's letterforms become physical boundaries sampled from a signed distance field, with restitution and friction. Integrity lets energetic particles buy passage — the wall weakens under impact and heals as things calm. A wall never fights a particle whose own home lies inside it.</p>`,false,'collision')}
 ${group('Pairwise contacts',`${toggle('Particle contacts','engine.pairwiseEnabled',s.engine.pairwiseEnabled===true)}${inGroup(c,'pairwise')}<p class="control-note">True particle-particle contact resolved on a GPU sorted grid: relaxed separation, restitution and tangential smoothing. Radius should sit near the baked slot spacing — a few pixels at typical counts. Large radii at dense packings bulge the strokes; the contacts cost nothing while off.</p>`,false,'pairwise')}`;
}
function objects(c:InspectorContext,e:Entity|undefined){const s=c.scene;return `${heading('Objects',`${s.entities.filter(e=>e.kind==='formation').length}/10 forms · ${s.entities.filter(e=>e.kind==='pin').length}/8 pins`)}
 <div class="object-list">${s.entities.map(o=>`<button class="object-row ${c.selected.includes(o.id)?'selected':''}" data-action="select-entity" data-id="${o.id}" title="${esc(o.name)}"><span class="object-symbol" style="--tint:${o.tintWeight?o.tint:'var(--ink)'}">${o.kind==='pin'?icon('pin'):stateThumbnail(o,0)}</span><span><strong>${esc(o.name)}</strong><small>${o.enabled===false?'Disabled · ':''}${o.kind==='pin'?'Force only · no allocation':'Formation · '+esc(formationSummary(o))}</small></span>${o.locked?icon('lock'):'<i class="selection-dot"></i>'}</button>`).join('')}</div>
 <div class="button-row">${button('tool-formation','Formation','plus')}${button('tool-pin','Pin','pin')}${s.entities.length>1?button('select-all','Select all'):''}</div>
 ${c.selected.length>1?`<div class="selection-summary">${c.selected.length} centres selected · Shift-click to change selection.</div>`:''}
 ${e&&c.selected.length===1?entityControls(c,e):!s.entities.length?'<div class="empty-note">Choose a formation or pin, then click where it belongs.</div>':''}
 ${group('Arrangement',`<p class="control-note">Applies only to the selected, unlocked centres. Their identities, tints, forces and sequences stay intact.</p><div class="layout-grid">${['line','column','ring','grid','spiral','align-x','align-y','distribute-x','distribute-y'].map(l=>`<button data-action="arrange" data-value="${l}" ${!c.selected.length?'disabled':''}>${l.replace('-',' ')}</button>`).join('')}</div>${select('Layout plane','composition.plane',s.composition.plane,[['XY','XY'],['XZ','XZ'],['YZ','YZ']])}<div class="button-row">${button('preset-browser','Add a composition','plus')}</div>`,c.selected.length>1,'arrange')}`;}
/** A pin's cycle clock: its force (or position) automation groups on one shared clock, either raw scene time or the pin's own stable cycle. */
function pinCycle(c:InspectorContext,e:Entity){const s=c.scene,own=pinCycleClockId(e.id),groups=entityCycleGroups(s,e.id);
 if(!groups.length)return group('Cycle clock','<p class="control-note">Automate one of this centre’s parameters with its wave icon and the motion source appears here. It can then run on this pin’s own cycle clock instead of raw scene time.</p>',false,'pin-cycle');
 return group('Cycle clock',groups.map(g=>{const leader=g.leader,clock=leader.clockId??'';
  return `<div class="pin-cycle"><p class="control-note">One motion source drives ${esc(g.targets.map(l=>automationTarget(s,l.target)?.label.split(' · ').at(-1)??l.target).join(', '))}.</p>
  ${select('Clock','lane.'+leader.id+'.clockId',clock,([['','Scene clock · raw engine time'],[own,'Own cycle'],...(clock&&clock!==own?[[clock,'Linked clock · '+clock]]:[])] as [string,string][]))}
  ${clock?`${range('Cycle rate · Hz','lane.'+leader.id+'.rate',leader.rate,0,2,.001,'',false,0,10)}${range('Cycle phase · turns','lane.'+leader.id+'.phase',leader.phase,0,1,.001)}
  ${select('Motion character','lane.'+leader.id+'.wave',leader.wave,[['sine','Breathe'],['triangle','Sway'],['square','Pulse'],['saw','Urge · build and release'],['steps','Flicker'],['smooth','Drift'],['morph','Morph drive · the field’s θ/φ']])}
  ${g.targets.map(l=>{const t=automationTarget(s,l.target),name=t?.label.split(' · ').at(-1)??l.target;return `${range(name+' · low','lane.'+l.id+'.min',l.min,t?.min??0,t?.max??1,.001,'',false,t?.hardMin??-1e10,t?.hardMax??1e10)}${range(name+' · high','lane.'+l.id+'.max',l.max,t?.min??0,t?.max??1,.001,'',false,t?.hardMin??-1e10,t?.hardMax??1e10)}`;}).join('')}
  <p class="control-note">Every linked parameter rides one stable clock (pin:${esc(e.id)}), so radius, spin and position can swell and turn together. Rate edits keep their phase, and lanes linked later join the running cycle without restarting it.</p>`:''}</div>`;}).join(''),groups.some(g=>!!g.leader.clockId),'pin-cycle');}
function semanticControls(c:InspectorContext,e:Entity){const s=c.scene,binding=s.semanticField?.bindings.find(b=>b.enabled&&b.carriers.some(x=>x.kind==='entity'&&x.id===e.id)),color=binding?.color;
 const node=binding?.semanticNodeId??'none',fieldEnabled=s.semanticField?.enabled===true,station=c.stations?.find(st=>st.semanticNodeId===node),mods=binding?.modulations??[];
 const modulation=mods.map((m,i)=>`<div class="semantic-modulation" data-semantic-modulation="${i}"><label class="control"><span>Signal</span><select data-semantic-mod-field="source.kind" data-semantic-mod-index="${i}" data-entity-id="${esc(e.id)}">${([['resonanceAffinity','Resonant affinity'],['focus','Travelling focus'],['carrierSpeed','Carrier speed'],['forceStrength','Force strength'],['forceSpin','Force spin']] as [string,string][]).map(([v,l])=>`<option value="${v}" ${m.source.kind===v?'selected':''}>${l}</option>`).join('')}</select></label><label class="control"><span>Modulates</span><select data-semantic-mod-field="target" data-semantic-mod-index="${i}" data-entity-id="${esc(e.id)}">${([['color.gain','Colour gain'],['color.radius','Colour radius'],['color.hueShift','Hue phase']] as [string,string][]).map(([v,l])=>`<option value="${v}" ${m.target===v?'selected':''}>${l}</option>`).join('')}</select></label><div class="two-col"><label class="number-field"><span>Amount</span><input type="number" min="-100" max="100" step=".01" value="${m.amount}" data-semantic-mod-field="amount" data-semantic-mod-index="${i}" data-entity-id="${esc(e.id)}"></label><label class="number-field"><span>Offset</span><input type="number" min="-100" max="100" step=".01" value="${m.offset??0}" data-semantic-mod-field="offset" data-semantic-mod-index="${i}" data-entity-id="${esc(e.id)}"></label></div><button class="secondary" data-action="semantic-remove-modulation" data-index="${i}" data-entity-id="${esc(e.id)}">Remove mapping</button></div>`).join('');
 return group('Semantic binding',`<label class="control"><span>Meaning</span><select data-semantic-node data-entity-id="${esc(e.id)}"><option value="none" ${node==='none'?'selected':''}>No semantic binding</option>${CHAKRA_DEFINITIONS.map(n=>`<option value="${n.id}" ${node===n.id?'selected':''}>${esc(n.name)}</option>`).join('')}</select></label>
 ${binding?`<p class="control-note">Meaning is attached by stable entity identity. Moving, reshaping or reordering this centre does not change the binding.</p>
 ${station?`<p class="control-note">Mapped physical resonance anchor · (${station.m}, ${station.n}) · ${station.frequencyHz.toFixed(1)} Hz. <span data-semantic-live="${esc(node)}">Live affinity —</span></p>`:`<p class="control-note"><span data-semantic-live="${esc(node)}">Live affinity —</span> · Physical anchor becomes available with the resonator.</p>`}
 <label class="toggle-row"><span>Semantic layer enabled</span><input type="checkbox" data-semantic-global="enabled" ${fieldEnabled?'checked':''}><i></i></label>
 <label class="toggle-row"><span>Spatial colour contribution</span><input type="checkbox" data-semantic-bind="color.enabled" data-entity-id="${esc(e.id)}" ${color?.enabled?'checked':''}><i></i></label>
 <label class="control"><span>Colour identity</span><select data-semantic-bind="color.colorSource" data-entity-id="${esc(e.id)}"><option value="canonical" ${color?.colorSource==='canonical'?'selected':''}>Canonical semantic colour</option><option value="entityTint" ${color?.colorSource==='entityTint'?'selected':''}>Entity tint</option><option value="override" ${color?.colorSource==='override'?'selected':''}>Override</option></select></label>
 ${color?.colorSource==='override'?`<label class="colour-field"><span>Override colour</span><input type="color" data-semantic-bind="color.overrideColor" data-entity-id="${esc(e.id)}" value="${color.overrideColor??'#ffffff'}"></label>`:''}
 <label class="control"><span>Activation</span><select data-semantic-bind="color.activation" data-entity-id="${esc(e.id)}"><option value="constant" ${color?.activation==='constant'?'selected':''}>Authored / constant</option><option value="resonanceAffinity" ${color?.activation==='resonanceAffinity'?'selected':''}>Live resonant affinity</option><option value="focus" ${color?.activation==='focus'?'selected':''}>Travelling focus</option></select></label>
 <div class="two-col"><label class="control"><span>Colour gain</span><input type="number" data-semantic-bind="color.gain" data-entity-id="${esc(e.id)}" min="0" max="100" step=".01" value="${color?.gain??1}"></label><label class="control"><span>Resonance gain</span><input type="number" data-semantic-bind="resonance.gain" data-entity-id="${esc(e.id)}" min="0" max="100" step=".01" value="${binding.resonance?.gain??1}"></label></div>
 <label class="control"><span>Colour radius</span><select data-semantic-bind="color.radius.source" data-entity-id="${esc(e.id)}"><option value="force" ${color?.radius.source==='force'?'selected':''}>Follow physical force radius</option><option value="independent" ${color?.radius.source==='independent'?'selected':''}>Independent</option></select></label>
 ${color?.radius.source==='independent'?`<label class="control"><span>Independent radius · native px</span><input type="number" data-semantic-bind="color.radius.value" data-entity-id="${esc(e.id)}" min="1" max="100000" step="1" value="${color.radius.value??220}"></label>`:''}
 <div class="two-col"><label class="control"><span>Falloff</span><select data-semantic-bind="color.falloff" data-entity-id="${esc(e.id)}"><option value="gaussian" ${color?.falloff==='gaussian'?'selected':''}>Gaussian</option><option value="compact" ${color?.falloff==='compact'?'selected':''}>Compact</option></select></label><label class="control"><span>Metric</span><select data-semantic-bind="color.metric" data-entity-id="${esc(e.id)}"><option value="compositionPlane" ${color?.metric==='compositionPlane'?'selected':''}>Composition plane</option><option value="world3d" ${color?.metric==='world3d'?'selected':''}>World 3D</option></select></label></div>
 <label class="control"><span>Mix law</span><select data-semantic-bind="color.blend" data-entity-id="${esc(e.id)}"><option value="weighted" ${color?.blend==='weighted'?'selected':''}>Weighted · order independent</option><option value="additive" ${color?.blend==='additive'?'selected':''}>Additive</option></select></label>
 ${group('Explicit modulation',`${modulation||'<p class="control-note">No physical signal currently modulates this semantic colour contribution.</p>'}<button class="secondary" data-action="semantic-add-modulation" data-entity-id="${esc(e.id)}">Add signal mapping</button><p class="control-note">Mappings are data: resonance, focus, motion or force can modulate colour gain/radius/hue without rewriting the stored base values.</p>`,mods.length>0,'semantic-modulation')}
 <p class="control-note">Force and colour remain separate. “Follow force radius” is an explicit coupling only; strength, polarity and spin do not recolour the field unless authored as modulation.</p>`:'<p class="control-note">Assigning meaning does not change this entity’s force, tint, shape, sequence or resonance by itself.</p>'}`,!!binding,'semantic-binding');}
function entityControls(c:InspectorContext,e:Entity){const s=c.scene,active=s.entities.filter(x=>x.kind==='formation'&&x.enabled!==false),total=active.reduce((n,x)=>n+x.share,0)||1;
 return `${heading(e.kind==='pin'?'Force centre':'Formation')}${text('Name','entity.name',e.name,'maxlength="160"')}
 ${toggle('Lock editing','entity.locked',e.locked,'Does not pause the sequence or remove its forces')}
 ${toggle('Enabled in the field','entity.enabled',e.enabled!==false,'A deliberate runtime change, unlike locking editing')}
 ${group('Position',`${entityControl(c,'entity.position.x','X · stage units')}${entityControl(c,'entity.position.y','Y · stage units')}${entityControl(c,'entity.position.z','Z · stage units')}<p class="control-note">400 native world units = one stage unit. Ordinary dragging preserves Z. Numeric coordinates deliberately change depth.</p>`,true,'entity-position')}
 ${e.kind==='formation'?`${e.source?`<p class="formation-summary">${esc(formationSummary(e))}</p>`:e.sequence.steps.length>1?`<p class="formation-summary">${esc(formationSummary(e))}</p>${group('Held target',shapeFields(e,'entity')+'<p class="control-note">This base geometry is used when the sequence is held. Edit the sequence states to change a playing or manually blended formation.</p>')}`:shapeFields(e,'entity')}
 <div class="two-col">${numeric(e.native&&!e.native.extent?'Width multiplier':'Width · stage units','entity.size.x',e.size.x,.001,100,.01)}${numeric(e.native&&!e.native.extent?'Height multiplier':'Height · stage units','entity.size.y',e.size.y,.001,100,.01)}</div>
 ${button('image-suite','Edit image / ASCII state','frame')}
 ${entityControl(c,'entity.scale','Uniform scale')}${range('Rotation · degrees','entity.rotation',e.rotation,-180,180,1,'',false,-36000,36000)}
 ${range('Particle share','entity.share',e.share,0,10,.1,'',false,0,1000)}<p class="control-note">${e.enabled===false?'Disabled':Math.round(e.share/total*100)+'%'} · ${Math.round(baseValue(s,'count')*e.share/total).toLocaleString()} nominal particles. Shares normalize over enabled formations. Pins own none.</p>
 <label class="colour-field"><span>Stored local tint</span><input type="color" data-bind="entity.tint" value="${e.tint}"></label>${entityControl(c,'entity.tintWeight','Local tint contribution')}
 <p class="control-note" data-focus-contribution>Palette → this stored tint → focus contribution. Selection is inspection, not activation.</p>
 <div class="button-row">${button('entity-sequence','Edit its sequence','wave')}</div>`:''}
 ${group('Influence',`<div class="segmented">${(['none','attract','repel','vortex']as const).map(k=>`<button data-action="force-kind" data-value="${k}" class="${e.force.kind===k?'active':''}">${k==='none'?'Off':k[0].toUpperCase()+k.slice(1)}</button>`).join('')}</div>${entityControl(c,'entity.force.strength','Strength')}${entityControl(c,'entity.force.radius','Falloff radius · stage units')}${entityControl(c,'entity.force.spin','Spin')}
 <p class="control-note">Gaussian influence fades beyond its characteristic radius. Forces sum across all particles, not just an owned allocation. Strength is signed — the sign is the polarity, so Attract below zero pushes outward and Repel below zero pulls inward. Spin adds the same tangential swirl under every law; automate radius and spin together on the cycle clock below to widen and sharpen the whirl as one.</p>`,e.kind==='pin','influence')}
 ${e.kind==='pin'?pinCycle(c,e):''}
 ${semanticControls(c,e)}
 ${e.station!==null&&!s.semanticField?.enabled?group('Legacy station link',`${select('Station association','entity.station',String(e.station),[['none','No station link'],...(c.stations?.length?c.stations.map(st=>[String(st.index),`${st.index+1} · ${st.name} · ${Math.round(st.frequencyHz)} Hz`] as [string,string]):Array.from({length:7},(_,i)=>[String(i),'Station '+(i+1)] as [string,string]))])}<p class="control-note">Schema-4 compatibility only. New resonance following resolves through semantic bindings.</p>`,false,'legacy-station'):''}
 <div class="button-row">${button('duplicate-entity','Duplicate','copy')}${button('delete-entity','Remove','trash')}</div>`;
}
function motion(c:InspectorContext,e:Entity|undefined){const s=c.scene,tab=c.motionTab;const tabs=`<div class="motion-tabs">${(['sequence','morph','focus','automation']as const).map(t=>`<button data-action="motion-tab" data-value="${t}" class="${t===tab?'active':''}">${t[0].toUpperCase()+t.slice(1)}</button>`).join('')}</div>`;
 if(tab==='sequence'){
  e=e?.kind==='formation'?e:undefined;if(!e)return tabs+'<div class="empty-note">Choose a formation to edit its sequence.</div>'+s.entities.filter(v=>v.kind==='formation').map(v=>`<button class="secondary" data-action="choose-sequence-entity" data-id="${v.id}">${esc(v.name)} · ${esc(formationSummary(v))}</button>`).join('');
  const k=e.sequence.steps[Math.min(c.stepIndex,e.sequence.steps.length-1)];
  return tabs+`<div class="motion-content"><section>${heading('Entity sequence')}
   <label class="control"><span>Formation</span><select data-action="sequence-entity">${s.entities.filter(e=>e.kind==='formation').map(o=>`<option value="${o.id}" ${o.id===e!.id?'selected':''}>${esc(o.name)}</option>`).join('')}</select></label>
   ${toggle('Advance the sequence','entity.sequence.enabled',e.sequence.enabled)}${!e.sequence.enabled?toggle('Use links for manual morph','entity.sequence.manual',e.sequence.manual===true,'Otherwise this is the base formation only'):''}
   ${select('Clock','entity.sequence.clock',e.sequence.clock,[['seconds','Seconds · hold and transition'],['morph','Morph cycles · one θ cycle per link']])}
   <p class="control-note">One engine clock. No playhead here seeks particle state. A position keyframe is an offset from the base centre.</p>
   ${select('Order','entity.sequence.order',e.sequence.order??'loop',[['loop','Loop'],['pingpong','Ping-pong'],['random','Deterministic random']])}
   ${select('Transition easing','entity.sequence.easing',e.sequence.easing??'smoothstep',[['smoothstep','Smooth'],['linear','Linear Geodesic'],['kineticSnap','Kinetic snap'],['whip','Whip']])}
   ${entityControl(c,'entity.sequence.rateMul','Sequence rate multiplier')}${entityControl(c,'entity.sequence.phaseOffset','Sequence phase · cycles')}
   ${toggle('Refit state sizes to new glyphs','engine.autoFitSizes',s.engine.autoFitSizes!==false,'Text and font edits renormalise every state box around its glyph')}
   </section><section>${heading('Shapes and intervals')}${button('refit-sequence','Refit all states to their glyphs')}
   <div class="sequence-chain">${e.sequence.steps.map((step,i)=>`<button data-action="select-step" data-index="${i}" class="${i===c.stepIndex?'active':''}" data-step-live="${i}" title="${esc(stateLabel({...step,source:stateSource(e!,i)}))} · ${step.hold}s hold / ${step.transition}s transition"><span>${stateThumbnail(e!,i)}</span><small>${i+1} · ${step.hold}/${step.transition}s</small></button>`).join('')}<button data-action="add-step" aria-label="Add sequence step">${icon('plus')}</button></div>
   ${k?`${heading('Editing step '+(c.stepIndex+1))}${stateSource(e,c.stepIndex)?button('image-suite','Edit '+esc(stateLabel({...k,source:stateSource(e,c.stepIndex)}))):shapeFields(k,'step')}${!k.objectState?`<div class="button-row">${button('capture-step-state','Give this state its own size & presence')}</div><p class="control-note">Without its own state, this link shares the held target’s size and presence.</p>`:''}${k.objectState?group('Object state',`${range('State width','step.objectState.size.x',k.objectState.size.x,.01,4,.01)}${range('State height','step.objectState.size.y',k.objectState.size.y,.01,4,.01)}${range('State rotation','step.objectState.rotation',k.objectState.rotation,-180,180,1)}${range('State scale','step.objectState.scale',k.objectState.scale??1,.01,5,.01)}${range('State tint weight','step.objectState.tintWeight',k.objectState.tintWeight,0,1,.01)}${range('State force','step.objectState.force.strength',k.objectState.force.strength,-5,5,.05)}${range('State spin','step.objectState.force.spin',k.objectState.force.spin,-5,5,.05)}${button('release-step-state','Return to the held target’s size')}`):''}<div class="two-col">${numeric('Hold · seconds','step.hold',k.hold,0,3600,.05)}${numeric('Transition · seconds','step.transition',k.transition,0,3600,.05)}</div><div class="button-row">${button('step-earlier','Earlier')}${button('step-later','Later')}${button('duplicate-step','Duplicate')}${button('delete-step','Remove','trash')}</div>`:''}
   </section><section>${heading('Spatial target')}
   ${k?`<div class="button-row">${button('place-keyframe',k.position?'Edit this step’s position':'Place this step’s position','pin')}</div>${k.position?`<p class="control-note">Step ${c.stepIndex+1} offsets. Ordinary centre dragging still edits the whole entity.</p><div class="three-col">${numeric('Offset X','step.position.x',k.position.x,-50,50,.01)}${numeric('Offset Y','step.position.y',k.position.y,-50,50,.01)}${numeric('Offset Z','step.position.z',k.position.z,-50,50,.01)}</div>${button('clear-keyframe','Clear this offset')}`:'<p class="control-note">No position offset. This link uses the entity’s base placement.</p>'}`:''}
   ${group('Timing detail',`${entityControl(c,'entity.sequence.hold','Common hold · seconds')}${entityControl(c,'entity.sequence.transition','Common transition · seconds')}${range('Timing jitter','entity.sequence.jitter',e.sequence.jitter??0,0,1,.02,'',false,0,3)}${range('Transition impulse','entity.sequence.impulse',e.sequence.impulse??0,0,5,.05,'',false,0,20)}<p class="control-note">Per-link duration edits override common timing. The native sequence law applies; no separate timer is created.</p>`,true)}
   </section></div>`;
 }
 if(tab==='morph')return tabs+`<div class="motion-content"><section>${heading('Conjugate phases')}<div class="phase-instrument"><div><svg viewBox="0 0 100 100"><circle cx="50" cy="50" r="38"/><line data-phase="theta" x1="50" y1="50" x2="50" y2="16"/><text x="50" y="57">θ</text></svg><span>Toroidal</span></div><div><svg viewBox="0 0 100 100"><circle cx="50" cy="50" r="38"/><line data-phase="phi" x1="50" y1="50" x2="50" y2="16"/><text x="50" y="57">φ</text></svg><span>Poloidal</span></div></div><div class="drive-track"><i id="drive-value"></i></div>
 ${keys(c,'thetaRate','phiRate','morphDepth','morphDwell')}<p class="control-note">The phase display reads the engine’s actual accumulators.</p></section><section>${heading('Physical morph')}
 ${toggle('Morph trajectory','engine.morphEnabled',s.engine.morphEnabled)}${toggle('Oscillating drive','engine.autoOscillate',s.engine.autoOscillate,'When off, the native manifold scrub is manual')}
 ${select('Trajectory','engine.trajectory',s.engine.trajectory,[['linear','Linear Geodesic'],['toroidalHopf','Toroidal Hopf · dual fibration'],['vortexSpiral','Chiral Vortex Spiral'],['quantumInterference','Quantum Superposition']])}
 <p class="control-note">${s.engine.trajectory==='quantumInterference'?'Quantum Superposition uses interfering waves along the transition between forms.':s.engine.trajectory==='toroidalHopf'?'Dual toroidal and poloidal winding bends the transition along a Hopf trajectory.':s.engine.trajectory==='vortexSpiral'?'Chiral coupling spirals particles between the two forms.':'Linear Geodesic moves directly between form targets.'}</p>
 ${select('Interference law','morph.law',s.morph.law,[['theta','θ only'],['product','θ × φ'],['sum','θ + φ'],['beat','θ modulated by φ']])}
 ${select('Drive shaping','engine.driveShape',s.engine.driveShape,[['sine','Sine'],['triangle','Triangle'],['smooth','Smooth'],['pulse','Pulse']])}
 ${keys(c,'thetaOffset','phiOffset','native_morphProgress')}
 </section><section>${heading('Manifold detail')}${inGroup(c,'morph',['thetaRate','phiRate','morphDepth','morphDwell','thetaOffset','phiOffset','native_morphProgress'])}<p class="control-note">Breathing, winding and radius shape the live manifold trajectory. Scrubs preview control values; they do not reconstruct an earlier particle state or promise a seamless loop.</p></section></div>`;
 if(tab==='focus')return tabs+`<div class="motion-content"><section>${heading('Route through centres')}
 ${select('Orchestration','composition.focus',s.composition.focus,[['parallel','Parallel'],['travelling','Travelling focus']])}
 <div class="focus-route">${s.entities.filter(e=>e.kind==='formation').map((e,i)=>`<div data-focus-entity="${e.id}"><span class="route-number">${i+1}</span><i style="background:${e.tint}"></i><strong>${esc(e.name)}</strong><button data-action="route-up" data-id="${e.id}" aria-label="Move ${esc(e.name)} earlier">↑</button><button data-action="route-down" data-id="${e.id}" aria-label="Move ${esc(e.name)} later">↓</button></div>`).join('')}</div><p class="control-note">Reordering attention does not rearrange any position.</p>
 </section><section>${heading('Timing and direction')}${select('Traversal','engine.focusOrder',s.engine.focusOrder??'listed',[['listed','Listed order'],['reverse','Reverse order'],['pingpong','There and back']])}${keys(c,'focusDwell','focusGlide')}
 ${toggle('Carry local tint','composition.carryTint',s.composition.carryTint)}${s.semanticField?.bindings.length?'<p class="control-note">Semantic resonance follows stable bindings when Shared tuning driver is Travelling focus. The focused entity itself does not carry a physical station index.</p>':toggle('Follow linked stations · legacy','composition.carryStation',s.composition.carryStation)}
 </section><section>${heading('Visible contributions')}${select('Shared tuning driver','composition.frequencyDriver',s.composition.frequencyDriver,[['manual','Manual'],['focus','Travelling focus'],['automation','Automation']])}${keys(c,'native_composition__entityTintWeight','native_composition__orchestration__focusTintWeight')}<p class="control-note" data-focus-contribution>Focus contributes over local tint and the field palette. It never replaces the stored swatches.</p><p class="control-note">Semantic focus resolves focused entity → semantic binding → physical resonance anchor. An unbound centre cannot invent a station. Selecting a centre does not activate it.</p></section></div>`;
 const targets=automationTargets(s).filter(t=>!PARAMETERS.find(p=>p.key===t.key));
 return automationEditor(s,c.automationLoop===true);
}
