import {stateLabel,stateSource,stateThumbnail} from './sourceState';
import {GLYPH_CATEGORIES} from './nativeFeatures';
import {esc,icon} from './icons';
import {paramControl,entityControl,InspectorContext} from './inspector';
import {PARAMETERS} from './registry';
import {entityTargets} from './nativeParameters';
import {formationSummary,WorkspacePreferences} from './workspacePreferences';

export function liveWorkspaceHTML(c:InspectorContext,prefs:WorkspacePreferences){
 const e=c.scene.entities.find(e=>e.id===c.selected[0]&&e.kind==='formation')??c.scene.entities.find(e=>e.kind==='formation');
 const k=e?.sequence.steps[Math.min(c.stepIndex,e.sequence.steps.length-1)];
 const sequence=e?`<section class="live-sequence" data-entity-id="${esc(e.id)}"><label class="control"><span>Formation sequence</span><select data-action="sequence-entity" aria-label="Live formation">${c.scene.entities.filter(v=>v.kind==='formation').map(v=>`<option value="${esc(v.id)}" ${e.id===v.id?'selected':''}>${esc(v.name)}</option>`).join('')}</select></label>
 <p class="formation-summary">${esc(formationSummary(e))}</p><p class="live-state" data-formation-live="${esc(e.id)}"></p>
 <div class="sequence-chain">${e.sequence.steps.map((s,i)=>`<button data-action="select-step" data-index="${i}" aria-label="Edit state ${i+1}: ${esc(stateLabel({...s,source:stateSource(e,i)}))}" aria-pressed="${i===c.stepIndex}" class="${i===c.stepIndex?'active':''}"><span>${stateThumbnail(e,i)}</span><small>${i+1}</small></button>`).join('')}<button data-action="add-step" aria-label="Add sequence step" ${e.locked||e.sequence.steps.length>=32?'disabled':''}>${icon('plus')}</button></div>
 ${k?`<label class="control"><span>State ${Math.min(c.stepIndex,e.sequence.steps.length-1)+1} · ${esc(stateLabel({...k,source:stateSource(e,c.stepIndex)}))}</span>${stateSource(e,c.stepIndex)?`<button class="secondary" data-action="image-suite">Edit image / ASCII state</button>`:k.shape==='text'?`<input data-bind="step.text" aria-label="State glyph" value="${esc(k.text)}" maxlength="120" ${e.locked?'disabled':''}>`:`<button class="secondary" data-action="entity-sequence">Edit geometry</button>`}</label>`:''}
 <details class="glyph-tree"><summary>Glyph library</summary>${GLYPH_CATEGORIES.map(cat=>`<details data-glyph-category="${esc(cat.id)}"><summary>${esc(cat.name)}</summary><div class="glyph-grid">${cat.items.map(g=>`<button data-action="native-glyph" data-prefix="step" data-value="${esc(g.char)}" title="${esc(g.name)}" aria-label="Use ${esc(g.name)}" ${e.locked?'disabled':''}>${esc(g.char)}</button>`).join('')}</div></details>`).join('')}</details><div class="button-row state-actions"><button data-action="step-earlier" ${e.locked||c.stepIndex===0?'disabled':''} aria-label="Move state earlier">←</button><button data-action="step-later" ${e.locked||c.stepIndex>=e.sequence.steps.length-1?'disabled':''} aria-label="Move state later">→</button><button data-action="duplicate-step" ${e.locked||e.sequence.steps.length>=32?'disabled':''}>Duplicate</button><button data-action="delete-step" ${e.locked||e.sequence.steps.length<=1?'disabled':''}>Remove</button><button data-action="entity-sequence">Timing</button><button data-action="place-formation">New formation</button></div>
 <div class="button-row"><button class="secondary" data-action="image-suite">Image / ASCII</button><button class="secondary" data-action="fold-state" ${c.journey.scenes.findIndex(s=>s.id===c.scene.id)<1?'disabled':''}>Add state to earlier scene…</button></div><label class="control"><span>Transition control</span><select data-action="sequence-mode" aria-label="Transition control" ${e.locked?'disabled':''}><option value="hold" ${!e.sequence.enabled&&!e.sequence.manual?'selected':''}>Hold one state</option><option value="manual" ${!e.sequence.enabled&&e.sequence.manual?'selected':''}>Manual blend</option><option value="play" ${e.sequence.enabled?'selected':''}>Play sequence</option></select></label>${e.sequence.manual&&!e.sequence.enabled?'<p class="control-note">Manual blend uses the shared A→B Scrub. Other manually driven formations share this amount.</p>':''}</section>`:'<p class="empty-note">Place a formation to start a sequence.</p><button class="secondary" data-action="tool-formation">Add formation</button>';
 const layers=e?`<section class="live-layers" data-entity-id="${esc(e.id)}"><label class="control"><span>Layers · the body in depth</span></label>
 <p class="control-note">Layers are the object itself — front and back, cores and shells, each its own glyph, drawing or image at its own depth. The whole layered body then runs through the sequence as one object.</p>
 ${(e.layers??[]).map((l,i)=>`<div class="layer-row"><input data-layer-text data-layer-index="${i}" value="${esc(l.text)}" aria-label="Layer ${i+1} glyph" maxlength="8" ${e.locked?'disabled':''}>${l.source?.kind==='image'?`<small class="layer-source" title="${esc(l.source.image.name??'image')}">${esc(l.source.image.name??'image')}</small>`:l.source?.kind==='ascii'?`<textarea data-layer-ascii data-layer-index="${i}" rows="2" aria-label="Layer ${i+1} ASCII drawing" ${e.locked?'disabled':''}>${esc(l.source.ascii.text)}</textarea>`:''}<label class="layer-depth"><span>Depth</span><input type="number" data-layer-depth data-layer-index="${i}" value="${Number(l.z.toPrecision(12))}" step=".01" aria-label="Depth of layer ${i+1} · stage units" ${e.locked?'disabled':''}></label><div class="layer-tools"><button data-action="layer-move" data-index="${i}" data-dir="-1" ${i===0?'disabled':''} aria-label="Move layer toward the camera">↑</button><button data-action="layer-move" data-index="${i}" data-dir="1" ${i===(e.layers?.length??1)-1?'disabled':''} aria-label="Move layer away">↓</button><button data-action="layer-remove" data-index="${i}" ${(e.layers?.length??1)<=1?'disabled':''} aria-label="Remove layer">×</button></div></div>`).join('')}
 <div class="button-row"><button class="secondary" data-action="layer-add" data-kind="glyph" ${e.locked||(e.layers?.length??0)>=6?'disabled':''}>Glyph layer</button><button class="secondary" data-action="layer-add" data-kind="ascii" ${e.locked||(e.layers?.length??0)>=6?'disabled':''}>ASCII layer</button><button class="secondary" data-action="layer-add" data-kind="image" ${e.locked||(e.layers?.length??0)>=6?'disabled':''}>Image layer</button></div>
 <p class="control-note">Depth is in stage units, positive toward the camera. Layers with an image or drawing sample it exactly like the sequence states do.</p></section>`:'';
 const controls=prefs.entries.map((entry,index)=>{
  let control='',label='',entityId='';
  if(entry.scope==='field'){const p=PARAMETERS.find(p=>p.key===entry.key);if(p){label=p.label;control=paramControl(p,c);}}
  else {
   const subject=entry.scope==='selected'?(c.scene.entities.find(v=>v.id===c.selected[0])??e):c.scene.entities.find(v=>v.id===entry.entityId);
   const target=subject&&entityTargets(c.scene).find(t=>t.entityId===subject.id&&t.key===entry.key);
   if(target){entityId=subject!.id;label=target.label;control=entityControl({...c,selected:[entityId]},target.bind);}
  }
  // Every control keeps the same binding, but each surface owns unique label IDs.
  control=control.replace(/\bid="([^"]+)"/g,(_,id)=>`id="belt-${esc(entry.id)}-${id}"`).replace(/\bfor="([^"]+)"/g,(_,id)=>`for="belt-${esc(entry.id)}-${id}"`);
  return `<article class="belt-entry" data-belt-id="${esc(entry.id)}" ${entityId?`data-entity-id="${esc(entityId)}"`:''}><div class="belt-entry-tools">${entry.scope==='field'?'':`<small>${entry.scope==='selected'?'Selected formation':esc(c.scene.entities.find(v=>v.id===entry.entityId)?.name??'Formation')}</small>`}<button data-action="belt-up" data-id="${esc(entry.id)}" aria-label="Move ${esc(label||entry.key)} up" ${index===0?'disabled':''}>↑</button><button data-action="belt-down" data-id="${esc(entry.id)}" aria-label="Move ${esc(label||entry.key)} down" ${index===prefs.entries.length-1?'disabled':''}>↓</button>${entry.scope!=='field'?`<button data-action="belt-scope" data-id="${esc(entry.id)}" title="${entry.scope==='selected'?'Bind to this named formation':'Follow the selected formation'}">${entry.scope==='selected'?'Bind':'Follow'}</button>`:''}<button data-action="belt-remove" data-id="${esc(entry.id)}" aria-label="Remove ${esc(label||entry.key)} from toolbelt">×</button></div>${control||`<p class="control-note">${esc(entry.key)} · unavailable in this scene</p>`}</article>`;
 }).join('');
 return {sequence:sequence+(layers?'<div class="panel-gap"></div>'+layers:''),controls:`<section aria-label="Pinned parameters">${controls||'<p class="empty-note">Use the star beside a control to keep it here.</p>'}${c.scene.favourites?.length?'<button class="secondary" data-action="import-favourites">Import scene favourites</button>':''}</section>`};
}
