import {baseValue,entityTargets,nativeBinding} from './nativeParameters';
import {clone,Scene,Journey} from './model';
export interface PropertyTrack {id:string;bind:string;entityId?:string;points:Array<{time:number;value:number}>}
const safePath=/^(field\.params\.[A-Za-z0-9_]+|entity\.(position\.[xyz]|scale|tintWeight|force\.(strength|radius|spin)|sequence\.(hold|transition|rateMul|phaseOffset)))$/;
export function validateTracks(value:unknown):PropertyTrack[]{if(!Array.isArray(value)||value.length>2048)throw new Error('Invalid property tracks');const ids=new Set<string>(),targets=new Set<string>();for(const t of value){if(!t||typeof t.id!=='string'||(!safePath.test(t.bind)||t.bind.split('.').some((k:string)=>['__proto__','prototype','constructor'].includes(k)))||t.bind.startsWith('entity.')&&typeof t.entityId!=='string'||!Array.isArray(t.points)||t.points.length>72000)throw new Error('Invalid property track');const target=t.bind+':'+(t.entityId??'');if(ids.has(t.id)||targets.has(target))throw new Error('Duplicate property track');ids.add(t.id);targets.add(target);let last=-1;for(const p of t.points){if(!p||!Number.isFinite(p.time)||p.time<0||p.time>3600||p.time<=last||!Number.isFinite(p.value))throw new Error('Invalid property keyframe');last=p.time;}}return clone(value);}
export function valueAt(points:PropertyTrack['points'],time:number):number|undefined{if(!points.length||time<points[0].time)return undefined;let i=points.findIndex(p=>p.time>time);if(i<0)return points.at(-1)!.value;const a=points[i-1],b=points[i];return a.value+(b.value-a.value)*(time-a.time)/(b.time-a.time);}
export function readTrackValue(s:Scene,t:Pick<PropertyTrack,'bind'|'entityId'>):number|undefined{if(t.bind.startsWith('field.params.')){const key=t.bind.slice(13);if(nativeBinding(key))return baseValue(s,key);}if(t.bind.startsWith('entity.')){const target=entityTargets(s).find(v=>v.entityId===t.entityId&&v.bind===t.bind);if(target)return target.value;}const root=t.bind.startsWith('entity.')?s.entities.find(e=>e.id===t.entityId):s;const path=t.bind.startsWith('entity.')?t.bind.slice(7):t.bind;let value:any=root;for(const key of path.split('.'))value=value?.[key];return typeof value==='number'&&Number.isFinite(value)?value:undefined;}
export function evaluateTracks(s:Scene,time:number):Scene{if(!s.propertyTracks?.length)return s;const out:Scene={...s,field:{...s.field,params:{...s.field.params}},entities:s.entities.map(e=>({...e,position:{...e.position},size:{...e.size},force:{...e.force},sequence:{...e.sequence}}))};for(const t of out.propertyTracks!){const value=valueAt(t.points,time);if(value===undefined)continue;let root:any=t.bind.startsWith('entity.')?out.entities.find(e=>e.id===t.entityId):out;const keys=(t.bind.startsWith('entity.')?t.bind.slice(7):t.bind).split('.');for(const k of keys.slice(0,-1))root=root?.[k];if(root&&readTrackValue(s,t)!==undefined){const binding=t.bind.startsWith('field.params.')?nativeBinding(t.bind.slice(13)):entityTargets(s).find(v=>v.entityId===t.entityId&&v.bind===t.bind);root[keys.at(-1)!]=binding?Math.max(binding.hardMin,Math.min(binding.hardMax,value)):value;}}return out;}
export function mergeTake(existing:PropertyTrack[],take:PropertyTrack[],start:number,end:number):PropertyTrack[]{const out=clone(existing);for(const t of take){const old=out.find(v=>v.bind===t.bind&&v.entityId===t.entityId);if(!old){out.push(clone(t));continue;}const points=old.points.filter(p=>p.time<start||p.time>end);old.points=[...points,...clone(t.points)].sort((a,b)=>a.time-b.time);}return out;}
export function expressionTiming(j:Journey,index:number,local:number,savedOnly=false){const duration=(s:Scene)=>savedOnly?(j.savedScenes?.[s.id]?.duration??0):s.duration;const total=j.scenes.reduce((n,s)=>n+duration(s),0),start=j.scenes.slice(0,index).reduce((n,s)=>n+duration(s),0);return {start,total,time:Math.min(total,start+local)};}

/** Keep held values flat until the gesture starts; do not invent a long ramp. */
export function sampleTrack(track:PropertyTrack,time:number,value:number,previousTime:number){const last=track.points.at(-1);if(!last){track.points.push({time:previousTime,value});return;}if(last.value===value)return;if(previousTime>last.time)track.points.push({time:previousTime,value:last.value});if(time>track.points.at(-1)!.time)track.points.push({time,value});}
