export interface Parameter {key:string;label:string;group:'material'|'density'|'motion'|'physics'|'resonance';min:number;max:number;step:number;preview:boolean;unit?:string;note?:string}
const p=(key:string,label:string,group:Parameter['group'],min:number,max:number,step:number,preview=true,note?:string):Parameter=>({key,label,group,min,max,step,preview,note});
export const PARAMETERS:Parameter[]=[
 p('count','Particle allocation','material',4000,100000,1000,true,'Preview ceiling: 100,000 marks. Production count remains engine-owned.'),
 p('size','Grain size','material',.25,3,.05),p('sizeBias','Size distribution','material',.2,4,.05),p('opacity','Opacity','material',.05,1,.01),p('roundness','Roundness','material',0,1,.01),p('softness','Edge softness','material',0,1,.01),p('irregularity','Imperfect edges','material',0,1,.01),p('elongation','Elongation','material',0,3,.01),p('orientation','Mark orientation','material',-180,180,1),p('jitter','Lattice irregularity','material',0,1,.01),p('grain','Paper grain','material',0,.2,.005),
 p('contrast','Density contrast','density',0,1,.01),p('densityScale','Density scale','density',.1,3,.01),p('densityPhase','Density phase','density',0,6.28,.01),p('edgeWeight','Edge emphasis','density',0,1,.01),p('halo','Dust halo','density',0,.6,.01),p('thickness','Form thickness','density',-.05,.12,.005),p('warp','Form warp','density',0,1,.01),
 p('speed','Motion rate','motion',0,3,.01),p('circulation','Circulation','motion',0,3,.01),p('turbulence','Restlessness','motion',0,2,.01),p('turbulenceScale','Flow scale','motion',.2,5,.05),p('dispersion','Dissolution','motion',0,1,.01),p('depth','Spatial depth','motion',0,1,.01),p('pointerStrength','Pointer strength','motion',0,3,.01),p('pointerRadius','Pointer radius','motion',.03,.8,.01),
 p('recovery','Return to formation','physics',0,12,.05,false),p('damping','Damping','physics',.05,8,.05,false),p('flow','Fluid coupling','physics',0,5,.05,false),p('snapRigidity','Snap rigidity','physics',0,5,.01,false),p('densityTether','Density tether','physics',0,5,.01,false),p('curlDepth','Curl depth','physics',0,3,.01,false),p('vortexRadius','Vortex radius','physics',.01,3,.01,false),p('gravityX','Gravity X','physics',-5,5,.01,false),p('gravityY','Gravity Y','physics',-5,5,.01,false),p('gravityZ','Gravity Z','physics',-5,5,.01,false),p('quadraticDrag','Quadratic drag','physics',0,5,.01,false),p('thermalJitter','Thermal jitter','physics',0,3,.01,false),p('speedLimit','Speed limit','physics',.1,20,.1,false),p('zConfinement','Z confinement','physics',0,1,.01,false),p('gravitySoftening','Gravity softening','physics',.01,2,.01,false),p('gravityFalloff','Gravity falloff','physics',.1,5,.01,false),p('swirlRadius','Swirl radius','physics',.01,3,.01,false),p('pointerFalloff','Pointer falloff','physics',.1,5,.01,false),p('timeScale','Time scale','physics',.1,3,.01,true),
 p('frequency','Shared frequency','resonance',80,800,1,false),p('dominance','Formation ↔ resonance','resonance',0,1,.01,false),p('resonanceDamping','Resonator damping','resonance',.005,.5,.005,false),p('excitation','Excitation','resonance',0,2,.01,false)
];
export const parameter=(key:string)=>PARAMETERS.find(p=>p.key===key);
