import {Journey,Scene,clone} from './model';
import {BeltEntry,defaultWorkspace} from './workspacePreferences';
import {NATIVE_BINDINGS,bindValue} from './nativeParameters';
import {readPath} from '../../src/engine/automation';
export const POINTER_PATHS=['engine.pointerMode','engine.pointerClick','engine.pointerClickStrength','engine.pointerClickRadius',...NATIVE_BINDINGS.filter(b=>b.group==='pointer').map(b=>b.bind)];
export type SharedSettings={toolbelt:BeltEntry[];values:Record<string,number|string|boolean>;pointer:Record<string,number|string|boolean>};
export function initialiseShared(j:Journey){if(!j.shared){const seen=new Set<string>(),entries:BeltEntry[]=[];for(const scene of j.scenes)for(const entry of scene.toolbelt??defaultWorkspace().entries){const key=[entry.scope,entry.key,entry.entityId??''].join(':');if(!seen.has(key)){seen.add(key);entries.push({...clone(entry),id:'shared-'+entries.length});}}j.shared={toolbelt:entries,values:{},pointer:{}};for(const path of POINTER_PATHS){const binding=NATIVE_BINDINGS.find(b=>b.bind===path),v=readPath(j.scenes[0],path)??(binding?binding.defaultValue:undefined);if(typeof v==='number'||typeof v==='string'||typeof v==='boolean')j.shared.pointer[path]=v;}}return j;}
export function globalPath(path:string){return /^(field\.(params\.[\w]+|background|material)|engine\.[\w]+|morph\.[\w]+|composition\.[\w]+)$/.test(path)&&!path.split('.').some(k=>['__proto__','constructor','prototype'].includes(k));}
export function isShared(j:Journey,s:Scene,path:string){return !!j.shared&&(Object.hasOwn(j.shared.values,path)||s.pointerScope!=='local'&&POINTER_PATHS.includes(path));}
export function effectiveScene(j:Journey,s:Scene):Scene{if(!j.shared)return s;const values={...j.shared.values,...(s.pointerScope!=='local'?j.shared.pointer:{})};const out={...s,field:{...s.field,params:{...s.field.params}},engine:{...s.engine},morph:{...s.morph},composition:{...s.composition}};for(const [path,value] of Object.entries(values))if(globalPath(path))bindValue(out,path,value);const sharedTargets=new Set(NATIVE_BINDINGS.filter(b=>Object.hasOwn(values,b.bind)).map(b=>'field.'+b.key));out.automation=s.automation.map(a=>sharedTargets.has(a.target)?{...a,enabled:false}:a);return out;}
export function writeShared(j:Journey,s:Scene,path:string,value:number|string|boolean){if(!isShared(j,s,path))return false;const bucket=POINTER_PATHS.includes(path)&&s.pointerScope!=='local'?j.shared!.pointer:j.shared!.values;bucket[path]=value;return true;}
export function toggleShared(j:Journey,s:Scene,path:string){if(!globalPath(path))throw new Error('This property cannot be shared.');initialiseShared(j);if(Object.hasOwn(j.shared!.values,path)){const value=j.shared!.values[path];delete j.shared!.values[path];for(const scene of j.scenes)bindValue(scene,path,value);return false;}const binding=NATIVE_BINDINGS.find(b=>b.bind===path),value=readPath(effectiveScene(j,s),path)??binding?.defaultValue;if(typeof value!=='number'&&typeof value!=='string'&&typeof value!=='boolean')throw new Error('This property has no scalar value.');j.shared!.values[path]=value;return true;}
export function useLocalPointer(j:Journey,s:Scene,local:boolean){if(local){const effective=effectiveScene(j,s);for(const path of POINTER_PATHS){const v=readPath(effective,path);if(v!==undefined)bindValue(s,path,v);}s.pointerScope='local';}else s.pointerScope='global';}
