import {icon} from './icons.js';
export const iconButton=(action:string,name:string,label:string,extra='')=>`<button class="icon-button" data-action="${action}" aria-label="${label}" title="${label}" ${extra}>${icon(name)}</button>`;
export function mountShell(){
 const ib=iconButton,root=document.getElementById('app')??document.body.appendChild(Object.assign(document.createElement('div'),{id:'app'}));
 root.innerHTML=`
 <div id="stage" role="application" aria-label="Living field canvas. Press E to edit; P to place a pin." tabindex="0"><canvas id="paper-canvas" aria-hidden="true" style="position:absolute;inset:0;pointer-events:none"></canvas><canvas id="field-canvas" aria-label="Native living particle field"></canvas><canvas id="transition-canvas" style="position:absolute;inset:0;width:100%;height:100%;pointer-events:none" hidden></canvas><div id="grain"></div><svg id="guides" aria-hidden="true"></svg><div id="text-layers"></div></div>
 <header class="masthead chrome"><div class="header-left">${ib('library','library','Expression library')}${ib('modes','modes','Starting compositions / modes','aria-expanded="false" aria-controls="modes-panel"')}</div><div class="header-actions">${ib('undo','undo','Undo edit')}${ib('redo','redo','Redo edit')}<span class="separator"></span>${ib('capture-image','camera','Capture image')}${ib('record-video','video','Record video','id="record-button" aria-pressed="false"')}${ib('capture-options','edit','Capture options','aria-expanded="false" aria-controls="capture-panel"')}</div></header>
 <nav id="tool-rail" class="tool-rail chrome" aria-label="Canvas tools">${[['interact','pointer','Interact'],['select','select','Select'],['pin','pin','Pin'],['formation','formation','Formation'],['text','text','Edit page text (T)'],['orbit','orbit','Orbit / pan camera (O)']].map(([a,i,l])=>ib('tool-'+a,i,l,`data-rail="${a}" aria-pressed="false"`)).join('')}<hr>${ib('objects','layers','Objects in this scene','data-rail="objects" aria-pressed="false"')}</nav>
 <div id="view-controls" class="view-controls chrome" hidden>${ib('grid','grid','Show working grid (G)')}<button data-action="snap" title="Snap placement to grid">Snap</button><select id="working-plane" aria-label="Working plane"><option>XY</option><option>XZ</option><option>YZ</option></select><label class="depth-field"><span id="depth-axis">Z</span><input id="working-depth" aria-label="Working-plane depth" type="number" min="-10" max="10" step="0.1" value="0"></label><button data-action="face-plane" title="Face the working plane">Face</button>${ib('guides','eye','Hide / show guides')}</div>
 <p id="coordinates" class="coordinate-readout chrome" aria-label="World coordinates">X +0.000 · Y +0.000 · Z +0.000</p><div id="tool-hint" class="tool-hint chrome" hidden></div>
 <aside id="inspector" class="inspector" aria-label="Contextual scene editor" hidden><div class="inspector-heading"><div><p class="eyebrow" id="inspector-eyebrow">SCENE EDITOR</p><h2 id="inspector-title">Scene settings</h2></div>${ib('close-inspector','close','Close inspector')}</div><div class="scope-tabs" role="tablist" aria-label="Editing scope">${['scene','objects','field','motion'].map(t=>`<button role="tab" aria-controls="inspector-content" data-action="tab" data-value="${t}" aria-selected="false">${t[0].toUpperCase()+t.slice(1)}</button>`).join('')}</div><label class="inspector-search">${icon('search')}<input id="control-search" aria-label="Find a control" placeholder="Find a control…" autocomplete="off"></label><div id="inspector-content" class="inspector-content" role="tabpanel"></div><footer class="inspector-footer"><span id="save-status">Saved locally</span><div class="history-buttons">${ib('undo','undo','Undo edit')}${ib('redo','redo','Redo edit')}</div></footer></aside>
 <div id="shape-picker" class="shape-picker" hidden></div><section id="timeline-panel" class="timeline-panel chrome" aria-label="Expression scenes" hidden></section>
 <nav class="instrument chrome" aria-label="Expression transport">${ib('previous','arrowLeft','Previous scene (←)')}<button id="scene-picker" class="study-picker" data-action="timeline" aria-expanded="false"><span id="scene-number">01</span><strong id="scene-name">Ink</strong>${icon('chevron')}</button>${ib('next','arrowRight','Next scene (→)')}<span class="dock-divider"></span>${ib('toggle-play','pause','Pause motion (Space)','id="play-button"')}${ib('play-journey','sequence','Play expression','id="journey-play" aria-pressed="false"')}<span class="dock-divider"></span>${ib('present','expand','Present the artwork (F)')}${ib('edit','edit','Edit scene','id="edit-button" aria-expanded="false"')}<div class="time-progress" aria-hidden="true"><i id="journey-progress"></i></div></nav>
 <div id="orbit-control" class="orbit-control chrome" role="group" aria-label="Orbital camera controller"></div>
 <button class="present-return icon-button" id="present-return" data-action="exit-present" aria-label="Return to the instrument (Esc)" title="Return to the instrument (Esc)" hidden>${icon('collapse')}</button>
 <div id="recording-badge" class="recording-badge" hidden><i></i><span id="record-time">00:00</span><span id="record-size"></span>${ib('stop-record','stop','Stop recording')}</div>
 <section id="modes-panel" class="modes-panel chrome" aria-label="Starting compositions" hidden></section>
 <section id="capture-panel" class="capture-panel chrome" aria-label="Capture options" hidden></section>
 <main id="library-page" class="library-page" aria-label="Expression library" tabindex="-1" hidden></main>
 <dialog id="confirm-dialog" class="modal" aria-label="Confirm change"></dialog><dialog id="video-dialog" class="modal" aria-label="Review recording"></dialog>
 <input type="file" id="source-file" accept="image/png,image/jpeg,image/webp" hidden><input type="file" id="import-file" accept="application/json,.json" hidden><div id="toast" class="toast" role="status" aria-live="polite" hidden></div>`;
}
