import './parityUI.js';
import {icon} from './icons.js';
import {installHeaderMenus} from './headerMenus.js';
export const iconButton=(action:string,name:string,label:string,extra='')=>`<button class="icon-button" data-action="${action}" aria-label="${label}" title="${label}" ${extra}>${icon(name)}</button>`;
export function mountShell(){
 const ib=iconButton,root=document.getElementById('app')??document.body.appendChild(Object.assign(document.createElement('div'),{id:'app'}));
 root.innerHTML=`
 <div id="stage" role="application" aria-label="Living field canvas. Press E to edit; P to place a pin." tabindex="0"><canvas id="paper-canvas" aria-hidden="true" style="position:absolute;inset:0;pointer-events:none"></canvas><canvas id="field-canvas" aria-label="Native living particle field"></canvas><canvas id="transition-canvas" style="position:absolute;inset:0;width:100%;height:100%;pointer-events:none" hidden></canvas><div id="grain"></div><svg id="guides" aria-hidden="true"></svg><div id="text-layers"></div></div>
 <header class="masthead chrome">
 <nav id="tool-rail" class="tool-rail" aria-label="Canvas tools">${[['interact','pointer','Interact'],['select','select','Select']].map(([a,i,l])=>ib('tool-'+a,i,l,`data-rail="${a}" aria-pressed="false"`)).join('')}${ib('pointer-options','ripple','Pointer effects','data-rail="pointer-options" aria-pressed="false"')}<span class="toolbar-divider" aria-hidden="true"></span>${[['pin','pin','Pin'],['formation','formation','Formation sequence'],['text','text','Edit page text (T)']].map(([a,i,l])=>ib('tool-'+a,i,l,`data-rail="${a}" aria-pressed="false"`)).join('')}${ib('objects','layers','Objects in this scene','data-rail="objects" aria-pressed="false"')}</nav>
 <div class="header-cluster workspace-cluster" data-compact-at="1100"><button class="header-menu-toggle" aria-label="Workspace menu" title="Workspace menu" aria-expanded="false" aria-controls="workspace-menu"><span aria-hidden="true">•••</span></button><nav id="workspace-menu" class="workspace-nav header-menu" aria-label="Workspace">${ib('library','library','Expression library')}${ib('studio','options','Studio')}${ib('modes','modes','Recent and starting compositions','aria-expanded="false" aria-controls="modes-panel"')}<button data-action="quick-guide" aria-label="How to use the instrument" title="How to use the instrument">?</button></nav></div>
 <div class="header-actions"><div class="header-cluster actions-cluster" data-compact-at="700"><button class="header-menu-toggle" aria-label="History and capture menu" title="History and capture menu" aria-expanded="false" aria-controls="header-actions-menu"><span aria-hidden="true">•••</span></button><div id="header-actions-menu" class="header-menu" role="group" aria-label="History and capture">${ib('undo','undo','Undo edit')}${ib('redo','redo','Redo edit')}${ib('capture-image','camera','Capture image')}${ib('record-video','video','Record video','id="record-button" aria-pressed="false"')}</div></div>${ib('capture-options','frame','Image suite','aria-expanded="false" aria-controls="capture-panel"')}</div></header>
 <button id="toolbelt-button" class="toolbelt-handle chrome" data-action="toolbelt" aria-label="Toolbelt" aria-expanded="false">⋮</button><div id="view-controls" class="view-controls chrome" hidden>${ib('grid','grid','Show working grid (G)')}<button data-action="snap" title="Snap placement to grid">Snap</button><select id="working-plane" aria-label="Working plane"><option>XY</option><option>XZ</option><option>YZ</option></select><label class="depth-field"><span id="depth-axis">Z</span><input id="working-depth" aria-label="Working-plane depth" type="number" min="-10" max="10" step="0.1" value="0"></label><button data-action="face-plane" title="Face the working plane">Face</button>${ib('guides','eye','Hide / show guides')}</div>
 <p id="coordinates" class="coordinate-readout chrome" aria-label="World coordinates">X +0.000 · Y +0.000 · Z +0.000</p><div id="tool-hint" class="tool-hint chrome" hidden></div>
 <aside id="inspector" class="inspector is-studio hud-panel" aria-label="Studio workspace" hidden>
 <header class="inspector-heading"><div><span class="panel-kicker">STUDIO</span><h2 id="inspector-title">Physics</h2></div><div class="inspector-center">${ib('dock-studio','collapse','Dock the studio where the toolbelt sits','id="dock-studio" aria-pressed="false"')}</div><div class="inspector-actions"><button data-action="studio-play" id="studio-play">Pause</button>${ib('close-studio','close','Close Studio')}</div></header>
 <nav class="studio-sections" aria-label="Studio sections">${[['formations','Formations'],['sequence','Glyph sequence'],['physics','Physics'],['pointer','Pointer'],['relational','Relational forces'],['collision','Collision & medium'],['motion','Morph'],['focus','Travelling focus'],['appearance','Colour & material'],['resonance','Resonance'],['automation','Automation'],['layout','Arrangement'],['text','Page text'],['scene','Scene settings']].map(([value,label])=>`<button data-action="studio-section" data-value="${value}">${label}</button>`).join('')}<label>Interface<select id="workspace-appearance" aria-label="Interface appearance"><option value="scene">Follow scene</option><option value="dark">Dark</option><option value="light">Light</option></select></label></nav>
 <label class="inspector-search">${icon('search')}<input id="control-search" aria-label="Find a control" placeholder="Find and pin a parameter…" autocomplete="off"></label>
 <div id="inspector-content" class="inspector-content"></div><footer class="inspector-footer"><span id="save-status" role="status">Draft backed up locally</span></footer><button class="panel-resize" data-resize="studio" aria-label="Resize Studio" title="Drag to resize. Arrow keys adjust width and height.">⌟</button></aside>
 <aside id="live-workspace" class="live-workspace hud-panel chrome" aria-label="Formation sequence" hidden><header><h2>Formation sequence</h2><button data-action="sequence-panel" aria-label="Close formation sequence">×</button></header><div id="live-content"></div><button class="panel-resize" data-resize="left" aria-label="Resize formation sequence" title="Drag to resize. Arrow keys adjust width and height.">⌟</button></aside>
 <aside id="toolbelt-panel" class="toolbelt-panel hud-panel chrome" aria-label="Toolbelt" hidden><header><h2>Toolbelt</h2><div>${ib('browse-controls','plus','Add properties')}${ib('record-properties','record','Record property keyframes','id="property-record" aria-pressed="false"')}${ib('take-mode','history','Recording mode: replace last take','id="take-mode"')}${ib('pointer-options','ripple','Pointer effects')}<button data-action="toolbelt" aria-label="Close toolbelt">×</button></div></header><div id="take-status" role="status" hidden></div><div id="belt-content"></div><button class="panel-resize" data-resize="belt" aria-label="Resize toolbelt" title="Drag to resize. Arrow keys adjust width and height.">⌞</button></aside>
 <aside id="automation-assignment" class="automation-assignment chrome" aria-label="Choose automation" hidden></aside><aside id="automation-monitor" class="automation-monitor chrome" aria-label="Automation cycle monitor" hidden></aside><aside id="belt-picker" class="hud-panel chrome" aria-label="Choose toolbelt properties" hidden></aside><aside id="context-panel" class="hud-panel chrome" aria-label="Local controls" hidden></aside><div id="shape-picker" class="shape-picker" hidden></div>
 <nav class="instrument chrome" aria-label="Scene transport"><section id="timeline-panel" class="timeline-panel" aria-label="Expression scenes" hidden></section><div class="transport-row">${ib('previous','arrowLeft','Previous scene (←)')}<button id="scene-picker" class="study-picker" data-action="timeline" aria-expanded="false"><span id="scene-number">01</span><strong id="scene-name">Ink</strong><small id="scene-state">Draft</small>${icon('chevron')}</button>${ib('next','arrowRight','Next scene (→)')}<span class="dock-divider"></span>${ib('toggle-play','pause','Pause motion (Space)','id="play-button"')}${ib('play-journey','sequence','Play saved scenes','id="journey-play" aria-pressed="false"')}<button data-action="open-timeline" class="transport-save">Save scene</button>${ib('present','expand','Present the artwork (F)')}<span id="global-time" aria-label="Expression time">0:00 / 0:00</span></div><div class="time-progress" aria-hidden="true"><i id="journey-progress"></i></div></nav>
 <div id="orbit-control" class="orbit-control chrome" role="group" aria-label="Orbital camera controller"></div>
 <button class="present-return icon-button" id="present-return" data-action="exit-present" aria-label="Return to the instrument (Esc)" title="Return to the instrument (Esc)" hidden>${icon('collapse')}</button>
 <div id="recording-badge" class="recording-badge" hidden><i></i><span id="record-time">00:00</span><span id="record-size"></span>${ib('stop-record','stop','Stop recording')}</div>
 <section id="modes-panel" class="modes-panel chrome" aria-label="Starting compositions" hidden></section>
 <section id="capture-panel" class="capture-panel chrome" aria-label="Image suite" hidden></section>
 <main id="library-page" class="library-page" aria-label="Expression library" tabindex="-1" hidden></main>
 <dialog id="guide-dialog" class="guide-dialog" aria-labelledby="guide-title"><header><h2 id="guide-title">Make a setup. Keep a scene.</h2><button data-action="close-dialog" aria-label="Close guide">×</button></header><ol><li><strong>Shape the setup</strong><p>Place a formation. Edit its glyph sequence on the left. Use the framed image icon at top right to create image or ASCII states. Pin useful controls to the expression’s shared toolbelt on the right.</p></li><li><strong>Save a scene</strong><p>Open Scenes, give this setup a name, then Save scene. This fixes a saved version of its settings, formations and camera. Later edits remain a draft until you save again.</p></li><li><strong>Make the next scene</strong><p>Save & make next copies this setup. Tweak the copy; your previous saved scene stays intact. In Formation sequence, “Add state to earlier scene” folds a refined object back into a sequence. Set duration and the incoming transition, then save.</p></li><li><strong>Play and keep the expression</strong><p>Play saved scenes in order. Glyph sequences run inside each scene. The library keeps your expression and working drafts in this browser; export JSON or living HTML for a portable copy.</p></li></ol><p class="guide-note">The globe beside a property makes it an expression override, backed up independently of scene saves. Turn it off to use local automation or record that property. Pointer settings default to the expression override; choose Local to give one scene its own pointer behaviour. Drafts, active scene, camera and driver clocks recover after reload.</p><p class="guide-note">A scene stores a configuration, not the exact positions and velocities of every particle. Numeric field transitions carry the existing simulation forward.</p><footer><button data-action="about">About O:I</button><button data-action="close-dialog">Start making →</button></footer></dialog>
 <dialog id="confirm-dialog" class="modal" aria-label="Confirm change"></dialog><dialog id="video-dialog" class="modal" aria-label="Review recording"></dialog>
 <input type="file" id="source-file" accept="image/png,image/jpeg,image/webp" hidden><input type="file" id="import-file" accept="application/json,.json" hidden><div id="toast" class="toast" role="status" aria-live="polite" hidden></div>`;
 installHeaderMenus(root);
}
