import {reorderFocus} from '../build/timeline.js';
import test from 'node:test';import assert from 'node:assert/strict';
import {fieldStudies,sevenCentres,smallLanguage,blankJourney,validateJourney,clone,entity,pin} from '../build/model.js';
import {DocumentStore} from '../build/store.js';
import {project,unproject,defaultCamera,facePlane} from '../build/camera.js';
import {sequenceAt,evaluateParameters,arrange,phases,focusAt} from '../build/timeline.js';
test('all curated journeys validate and have named, independent scenes',()=>{for(const f of [fieldStudies,sevenCentres,smallLanguage,blankJourney]){const j=f();assert.deepEqual(validateJourney(j),j);assert.ok(j.scenes.every(s=>s.name&&s.character));}});
test('opening composition preserves two persistent O/I entities',()=>{const s=fieldStudies().scenes[0];assert.deepEqual(s.entities.map(e=>e.text),['O','I']);assert.ok(s.entities[0].size.x>1.4);assert.equal(s.field.material,'ink');});
test('pins have zero particle share, without altering scene palette',()=>{const s=fieldStudies().scenes[0],before=clone(s);s.entities.push(pin({x:.2,y:.3,z:.4}));assert.equal(s.entities.at(-1).share,0);assert.deepEqual(s.field,before.field);assert.deepEqual(s.entities.slice(0,2),before.entities);});
test('projection/unprojection are inverse on 3D working planes',()=>{for(const plane of ['XY','XZ','YZ']){const c=defaultCamera();c.mode='3d';c.yaw=.54;c.pitch=.44;c.plane=plane;c.depth=.24;c.zoom=1.3;c.panX=16;c.panY=-19;const v=plane==='XY'?{x:.2,y:-.3,z:.24}:plane==='XZ'?{x:.2,y:.24,z:-.3}:{x:.24,y:.2,z:-.3};const p=project(v,c,1440,1000),back=unproject(p.x,p.y,c,1440,1000);for(const k of ['x','y','z'])assert.ok(Math.abs(v[k]-back[k])<1e-9);}});
test('edge-on working plane fails explicitly rather than placing at invented depth',()=>{const c=defaultCamera();c.plane='XZ';assert.throws(()=>unproject(500,500,c,1440,1000),/edge-on/);facePlane(c);assert.doesNotThrow(()=>unproject(500,500,c,1440,1000));});
test('grid snapping rounds only the working-plane coordinates',()=>{const c=defaultCamera();c.snap=true;c.depth=.123;const v=unproject(700,410,c,1440,1000);assert.equal(v.z,.123);assert.ok(Math.abs(v.x*10-Math.round(v.x*10))<1e-10);});
test('preview slider transactions produce one undo entry',()=>{const store=new DocumentStore(fieldStudies());store.begin();store.document.scenes[0].field.params.size=1;store.begin();store.document.scenes[0].field.params.size=2;store.finish();assert.equal(store.undoStack.length,1);store.undo();assert.equal(store.document.scenes[0].field.params.size,2.8);store.redo();assert.equal(store.document.scenes[0].field.params.size,2);});
test('entity sequence position keyframes are local offsets',()=>{const s=fieldStudies().scenes[0],e=s.entities[0];e.sequence.enabled=true;e.sequence.steps[0].position={x:.2,y:.3,z:.4};const a=sequenceAt(e,s,0);assert.equal(a.position.x,e.position.x+.2);e.position.x+=.5;assert.ok(Math.abs(sequenceAt(e,s,0).position.x-a.position.x-.5)<1e-12);});
test('morph-clock sequence advances one link per toroidal cycle',()=>{const s=fieldStudies().scenes[0],e=s.entities[0];e.sequence.enabled=true;e.sequence.clock='morph';e.sequence.steps.push({...clone(e.sequence.steps[0]),id:'second',text:'&'});s.morph.thetaRate=.5;assert.equal(sequenceAt(e,s,.1).from,0);assert.equal(sequenceAt(e,s,2.1).from,1);assert.equal(sequenceAt(e,s,4.1).from,0);});
test('automation never changes base values or the document',()=>{const s=fieldStudies().scenes[0];s.automation.push({id:'lane',enabled:true,target:'field.size',type:'lfo',wave:'sine',min:.4,max:2,rate:.25,phase:0,blend:'replace',duration:4,delay:0,loop:'once',firedAt:null});const before=JSON.stringify(s);assert.equal(evaluateParameters(s,2).size,2);assert.equal(JSON.stringify(s),before);});
test('ramp waits to be fired and respects delay',()=>{const s=fieldStudies().scenes[0];const l={id:'ramp',enabled:true,target:'field.size',type:'ramp',wave:'sine',min:.5,max:2,rate:.1,phase:0,blend:'replace',duration:2,delay:1,loop:'once',firedAt:null};s.automation.push(l);assert.equal(evaluateParameters(s,3).size,2.8);l.firedAt=3;assert.equal(evaluateParameters(s,3.5).size,2.8);assert.equal(evaluateParameters(s,6).size,2);});
test('arrangement preserves identities, sequence and tint',()=>{const s=sevenCentres().scenes[0],before=clone(s.entities);arrange(s.entities,'ring');s.entities.forEach((e,i)=>{assert.equal(e.id,before[i].id);assert.deepEqual(e.sequence,before[i].sequence);assert.equal(e.tint,before[i].tint);});});
test('focus order is independent of spatial coordinates',()=>{const s=sevenCentres().scenes[1];const before=s.entities.map(e=>clone(e.position));assert.equal(focusAt(s,.1).entity.id,s.entities[0].id);assert.equal(focusAt(s,4.1).entity.id,s.entities[1].id);assert.deepEqual(s.entities.map(e=>e.position),before);});
test('phase evaluation is pure and bounded',()=>{const s=fieldStudies().scenes[0],before=JSON.stringify(s);for(const law of ['theta','product','sum','beat']){s.morph.law=law;const p=phases(s,2.2);assert.ok(p.drive>=0&&p.drive<=1);}s.morph.law='theta';assert.equal(JSON.stringify(s),before);});
test('unknown production snapshots are rejected without silent migration',()=>{assert.throws(()=>validateJourney({schemaVersion:4,entities:[]}),/schema-4/);});
test('HTML-bearing identifiers are rejected; text remains ordinary text',()=>{const j=fieldStudies();j.scenes[0].entities[0].id='bad\" onmouseover=\"';assert.throws(()=>validateJourney(j),/entity/);const k=fieldStudies();k.scenes[0].text.push({id:'words',visible:true,kicker:'',title:'',italic:'',body:'',x:.1,y:.2,width:240,size:36,align:'left'});k.scenes[0].text[0].title='<script>alert(1)</script>';assert.equal(validateJourney(k).scenes[0].text[0].title,k.scenes[0].text[0].title);});
test('invalid numbers, duplicate scene IDs and excessive counts fail closed',()=>{const j=fieldStudies();j.scenes[0].entities[0].position.x=NaN;assert.throws(()=>validateJourney(j),/transform|Non-finite/);const a=fieldStudies();a.scenes[1].id=a.scenes[0].id;assert.throws(()=>validateJourney(a),/scene/);const b=fieldStudies();b.scenes[0].entities=Array.from({length:33},()=>entity('x'));assert.throws(()=>validateJourney(b),/limits/);});
test('round-trip includes framing and optional text',()=>{const j=fieldStudies();j.scenes[0].view={mode:'3d',yaw:.4,pitch:.2,zoom:1.2,panX:.1,panY:-.1};j.scenes[0].text.push({id:'words',visible:false,kicker:'',title:'Optional words',italic:'',body:'',x:.1,y:.2,width:240,size:36,align:'left'});assert.deepEqual(validateJourney(JSON.parse(JSON.stringify(j))),j);});

test('focus-route reordering skips interleaved pins and preserves spatial positions',()=>{const a=entity('A'),b=entity('B'),p=pin({x:.2,y:.3,z:.4});const entities=[a,p,b];const positions=entities.map(e=>({...e.position}));assert.equal(reorderFocus(entities,b.id,-1),true);assert.deepEqual(entities.map(e=>e.id),[b.id,p.id,a.id]);assert.deepEqual(a.position,positions[0]);assert.deepEqual(p.position,positions[1]);assert.deepEqual(b.position,positions[2]);});

// Review-requested workspace contracts.
import {railClick} from '../build/rail.js';
import {axisView,orbitBy} from '../build/orbitControl.js';
import {featuredExpressions,startingPoints,forkExpression} from '../build/expressions.js';
test('tool rail opens, closes, then returns to Interact for every non-default tool',()=>{for(const key of ['select','pin','formation','text','orbit','objects']){assert.equal(railClick('interact',key,false),'activate');assert.equal(railClick(key,key,true),'close');assert.equal(railClick(key,key,false),'interact');}assert.equal(railClick('select','interact',true),'interact');});
test('camera axis views and orbit preserve construction plane and physical independence',()=>{const c=defaultCamera();c.plane='XZ';c.depth=.3;c.grid=true;c.snap=true;c.panX=20;c.zoom=1.2;for(const a of ['X','-X','Y','-Y','Z','-Z']){axisView(c,a);assert.equal(c.plane,'XZ');assert.equal(c.depth,.3);assert.equal(c.panX,20);assert.equal(c.zoom,1.2);}orbitBy(c,55,5);assert.ok(Math.abs(c.yaw)<=Math.PI);assert.equal(c.pitch,Math.PI/2);});
test('all material, composition and native starting modes are validated editable expressions',()=>{const modes=startingPoints();assert.equal(modes.filter(m=>m.group==='Material').length,8);assert.equal(modes.filter(m=>m.group==='Composition').length,5);assert.ok(modes.filter(m=>m.group==='Native').length>10);for(const m of modes){assert.deepEqual(validateJourney(m.expression),m.expression);assert.equal(m.expression.scenes.length,1);const copy=forkExpression(m.expression);assert.notEqual(copy.id,m.expression.id);copy.scenes[0].name='Changed';assert.notEqual(m.expression.scenes[0].name,copy.scenes[0].name);}});
test('starter expressions and blank scenes contain no compulsory editorial text',()=>{for(const j of [...featuredExpressions(),blankJourney()])assert.ok(j.scenes.every(s=>s.text.length===0));});
