async () => {
 const T=window.NATIVE_TEST;const results=[];
 const assert=(condition,message)=>{if(!condition)throw new Error(message);};
 const near=(a,b,epsilon=1e-7)=>Math.abs(a-b)<epsilon;
 const test=async(name,fn)=>{try{results.push({name,ok:true,evidence:await fn()});}catch(error){results.push({name,ok:false,error:error.stack});}};
 const canvas=()=>document.body.appendChild(Object.assign(document.createElement('canvas'),{width:480,height:360}));
 const bare=()=>{const s=T.blankScene('GPU test');s.field.params.count=1024;s.entities=[];const cfg=T.toNativeConfig(s);Object.assign(cfg.fluid,{returnSpeed:0,turbulence:0,vortexStrength:0,thermalJitter:0,gravityX:0,gravityY:0,gravityZ:0,quadraticDrag:0,viscosity:1,zConfinement:0});cfg.cymatics.enabled=false;cfg.relational.enabled=false;cfg.toroidalMorph.enabled=false;return cfg;};
 function seededEngine(config){const old=Math.random;let seed=1337;Math.random=()=>((seed=Math.imul(seed,1664525)+1013904223)>>>0)/4294967296;try{return new T.PointCloudField(canvas(),config,true);}finally{Math.random=old;}}
 function force(mode,spin=0,radius=120,second=false){const cfg=bare();const p=T.pin({x:.05,y:-.08,z:.1});p.force={kind:mode,strength:2,radius:radius/400,spin};const s=T.blankScene();s.entities=[p];cfg.entities=T.toNativeConfig(s).entities;if(second)cfg.entities.push({...structuredClone(cfg.entities[0]),id:'second'});const engine=seededEngine(cfg);const before=engine.inspectState(true);engine.advance(1/60);const after=engine.inspectState(true);const centre=cfg.entities[0];let radial=0,tangent=0,outside=0,finite=true;for(let i=0;i<after.velocities.length;i+=4){const d=[before.positions[i]-centre.x,before.positions[i+1]-centre.y,before.positions[i+2]-centre.z],v=after.velocities.slice(i,i+3),length=Math.hypot(...d);radial+=d.reduce((n,x,j)=>n+x*v[j],0)/(length||1);tangent+=(-d[1]*v[0]+d[0]*v[1])/(Math.hypot(d[0],d[1])||1);if(length>radius*1.05&&length<radius*1.8)outside+=Math.hypot(...v);finite&&=v.every(Number.isFinite);}const evidence={radial:radial/1024,tangent:tangent/1024,outside,finite,steps:after.steps,seeds:after.seeds};engine.destroy();return evidence;}
 await test('GPU pins attract / repel / vortex, independent spin, Gaussian exterior and shared summation',()=>{const a=force('attract'),r=force('repel'),v=force('vortex'),spin=force('none',2),two=force('attract',0,120,true);assert(a.radial<-.01,'attraction must move inward');assert(r.radial>.01,'repulsion must move outward');assert(v.tangent>.01&&spin.tangent>.01,'vortex and independent spin must rotate');assert(a.outside>.001,'Gaussian influence must continue outside displayed radius');assert(near(two.radial/a.radial,2,.0005),'overlapping pins must sum');assert([a,r,v,spin,two].every(x=>x.finite),'no nonfinite velocity');return {attract:a,repel:r,vortex:v,spin,overlap:two};});
 await test('Native external clock, zero-step inspection, uniform-only movement and count-only reseed',()=>{const s=T.fieldStudies().scenes[0];s.field.params.count=1024;s.engine.resonanceEnabled=false;const e=new T.ProductionAdapter(canvas());e.resize(480,360,1);const f={scene:s,simTime:0,delta:0,params:s.field.params,camera:T.defaultCamera(),pointer:{active:false,world:{x:0,y:0,z:0}},selectedIds:[]};e.render(f);const a=e.inspect(true);e.render({...f,selectedIds:[s.entities[0].id]});let b=e.inspect(true);assert(JSON.stringify(a.positions)===JSON.stringify(b.positions)&&a.simTime===b.simTime&&a.steps===b.steps,'selection at zero delta must not integrate');s.entities[0].position.x+=.2;s.entities[0].size.x*=1.3;s.entities[0].rotation=40;e.render(f);b=e.inspect(true);assert(a.seeds===b.seeds&&a.bakes===b.bakes,'transforms must not reseed or rebake');assert(JSON.stringify(a.positions)===JSON.stringify(b.positions),'editing transform must not teleport particles');e.render({...f,delta:1/30});b=e.inspect();assert(near(b.simTime,1/30)&&b.steps-a.steps===2,'one external 1/30 command must do two 1/60 substeps');s.field.params.count=2048;e.render(f);const c=e.inspect();assert(c.seeds===a.seeds+1&&c.particleCount===2048,'count change is an explicit reseed');e.dispose();return {before:{time:a.simTime,steps:a.steps,seeds:a.seeds,bakes:a.bakes},after:{time:b.simTime,steps:b.steps,seeds:b.seeds,bakes:b.bakes},countChange:{seeds:c.seeds,count:c.particleCount}};});
 await test('Two independent sequences, overlapping pins, focus and continuous resonator share one clock',()=>{const s=T.fieldStudies().scenes[0];s.field.params.count=2048;s.field.params.dominance=.7;s.engine.resonanceEnabled=true;s.composition.focus='travelling';s.composition.frequencyDriver='focus';s.composition.carryStation=true;s.composition.focusDuration=.3;s.composition.focusDwell=.1;s.entities.forEach((e,i)=>{e.station=i*4;e.sequence.enabled=true;e.sequence.hold=.1;e.sequence.transition=.3;e.sequence.rateMul=i+1;e.sequence.steps.push({...structuredClone(e.sequence.steps[0]),id:'extra'+i,text:i?'&':'I'});});s.entities.push(T.pin({x:0,y:0,z:0}),T.pin({x:.1,y:.1,z:.05}));s.entities.at(-1).force.kind='repel';const e=new T.ProductionAdapter(canvas());e.resize(480,360,1);const f={scene:s,simTime:0,delta:1/60,params:s.field.params,camera:T.defaultCamera(),pointer:{active:false,world:{x:0,y:0,z:0}},selectedIds:[]};e.render({...f,delta:0});const a=e.inspect();let frequencies=[],independent=false;for(let i=0;i<45;i++){e.render(f);const t=e.telemetry();frequencies.push(t.cymatic.frequencyHz);independent||=t.sequences[0].linkIndex!==t.sequences[1].linkIndex;}const b=e.inspect(true);assert(independent,'independent sequences must diverge');assert(new Set(frequencies.map(x=>x.toFixed(3))).size>8,'focus must continuously change shared frequency');assert(b.seeds===a.seeds,'combined dynamics must not reseed');assert(b.positions.every(Number.isFinite),'combined GPU state must be finite');const oldFreq=e.telemetry().cymatic.frequencyHz;e.render({...f,delta:0,selectedIds:[s.entities[1].id]});assert(near(oldFreq,e.telemetry().cymatic.frequencyHz),'selection must not retune');const out={clock:b.simTime,seeds:b.seeds,steps:b.steps,frequencyRange:[Math.min(...frequencies),Math.max(...frequencies)],distinctFrequencies:new Set(frequencies).size,sequenceStates:e.telemetry().sequences};e.dispose();return out;});
 await test('Native image capture re-renders clean state at output resolution without stepping',()=>{const s=T.fieldStudies().scenes[0];s.field.params.count=2048;const c=canvas(),e=new T.ProductionAdapter(c);e.resize(480,360,1);const f={scene:s,simTime:0,delta:0,params:s.field.params,camera:T.defaultCamera(),pointer:{active:false,world:{x:0,y:0,z:0}},selectedIds:[]};e.render(f);const before=e.inspect(true);const plain=e.capture(800,600);const data=plain.getContext('2d').getImageData(0,0,800,600).data;let marked=0;for(let i=3;i<data.length;i+=4)if(data[i]>16)marked++;assert(marked>50,'native capture must contain actual GPU marks');e.render({...f,selectedIds:[s.entities[0].id]});const selected=e.capture(800,600);assert(selected.toDataURL()===plain.toDataURL(),'PNG must exclude selection shading');const after=e.inspect(true);assert(JSON.stringify(before.positions)===JSON.stringify(after.positions)&&before.simTime===after.simTime&&before.steps===after.steps,'capture must not change particle state');window.__gpuCapture=plain.toDataURL();e.dispose();return {width:800,height:600,markedPixels:marked,steps:after.steps,seeds:after.seeds};});
 await test('Semantic spatial colour is render-only, world-spatial and independent of particle ownership',()=>{const s=T.fieldStudies().scenes[0];s.field.params.count=2048;s.engine.colorEnabled=false;s.entities[0].position.x=-.45;s.entities[1].position.x=.45;s.entities.forEach(e=>{e.tintWeight=0;e.force.kind='none';});const c=canvas(),e=new T.ProductionAdapter(c);e.resize(640,440,1);const f={scene:s,simTime:0,delta:0,params:s.field.params,camera:T.defaultCamera(),pointer:{active:false,world:{x:0,y:0,z:0}},selectedIds:[]};e.render(f);const before=e.inspect(true),plain=e.capture(640,440),plainData=plain.getContext('2d').getImageData(0,0,640,440).data;
 s.semanticField={enabled:true,profile:{kind:'chakra',profileId:'chakra-seven-v1'},affinity:{method:'modalProjection',bandwidth:.14},globalColorGain:1,bindings:[{id:'heart-binding',semanticNodeId:'anahata',enabled:true,resonance:{gain:1},carriers:[{kind:'entity',id:s.entities[0].id}],color:{enabled:true,colorSource:'canonical',gain:1,radius:{source:'independent',value:1400},falloff:'gaussian',metric:'world3d',blend:'weighted',activation:'constant'}}]};
 e.render(f);const after=e.inspect(true),t=e.telemetry(),coloured=e.capture(640,440),data=coloured.getContext('2d').getImageData(0,0,640,440).data;let changed=0,chromatic=0;for(let i=0;i<data.length;i+=4){if(data[i]!==plainData[i]||data[i+1]!==plainData[i+1]||data[i+2]!==plainData[i+2])changed++;if(data[i]!==data[i+1]||data[i+1]!==data[i+2])chromatic++;}assert(JSON.stringify(before.positions)===JSON.stringify(after.positions)&&JSON.stringify(before.velocities)===JSON.stringify(after.velocities),'semantic colour must not alter GPU physics');assert(before.steps===after.steps&&before.seeds===after.seeds&&before.bakes===after.bakes,'semantic colour must not step, reseed or rebake');assert(changed>50&&chromatic>50,'semantic field must change actual rendered particle colour');assert(t.semantic?.colorFields?.length===1,'semantic runtime must expose one spatial field');assert(t.semantic.colorFields[0].radius===1400,'independent colour radius must remain independent from force radius');e.dispose();return{changedPixels:changed,chromaticPixels:chromatic,physicsUnchanged:true,colorField:t.semantic.colorFields[0]};});
 await test('Native ortho projection matches editor in 3D, resized and high-DPR views',()=>{const s=T.fieldStudies().scenes[0];s.field.params.count=1024;const e=new T.ProductionAdapter(canvas());const cams=[T.defaultCamera(),{...T.defaultCamera(),mode:'3d',yaw:.65,pitch:.4,zoom:1.8,panX:20,panY:-8}];let maxError=0;for(const camera of cams)for(const [w,h,dpr]of [[640,440,1],[880,600,2]]){e.resize(w,h,dpr);e.render({scene:s,simTime:0,delta:0,params:s.field.params,camera,pointer:{active:false,world:{x:0,y:0,z:0}},selectedIds:[]});for(const point of [{x:.2,y:.3,z:.4},{x:-.7,y:-.2,z:.15}]){const a=T.project(point,camera,w,h),b=e.projectNative(point);maxError=Math.max(maxError,Math.hypot(a.x-b.x,a.y-b.y));}}assert(maxError<.001,'editor/native projection mismatch '+maxError);e.dispose();return {maxPixelError:maxError};});
 await test('Pointer click effects: pulse pushes outward, implode gathers, vortex whirls — each within its own radius',()=>{const cfg=bare();const engine=seededEngine(cfg);
  const measure=(kind)=>{engine.triggerPointerEffect(kind,0,0,2,180);const before=engine.inspectState(true);engine.advance(1/60);const after=engine.inspectState(true);let radial=0,tangent=0,inside=0,total=0,finite=true;for(let i=0;i<after.velocities.length;i+=4){const d=[before.positions[i],before.positions[i+1]],dist=Math.hypot(...d),v=after.velocities.slice(i,i+3);if(dist>180)continue;total++;inside+=Math.hypot(v[0],v[1]);radial+=(d[0]*v[0]+d[1]*v[1])/(dist||1);tangent+=(-d[1]*v[0]+d[0]*v[1])/(dist||1);finite&&=v.every(Number.isFinite);}engine.resetField();return {radial:radial/(total||1),tangent:tangent/(total||1),meanSpeed:inside/(total||1),total,finite};};
  const pulse=measure('pulse'),implode=measure('implode'),vortex=measure('vortex');
  assert(pulse.total>100,'the effect radius must cover part of the fixture');
  assert(pulse.radial>.01,'pulse must push particles outward');
  assert(implode.radial<-.01,'implode must pull particles inward');
  assert(Math.abs(vortex.tangent)>.01,'vortex must whirl tangentially');
  assert(vortex.radial<.005,'vortex must stay tangential');
  assert([pulse,implode,vortex].every(e=>e.finite&&e.meanSpeed>.001),'every effect must move particles finitely');
  engine.destroy();return {pulse,implode,vortex};});
 return results;
}
