import assert from 'node:assert/strict';
import {test} from './harness.ts';
import {fieldStudies,validateJourney} from '../field-studies-journeys/src/model.ts';
import {linkAutomation,removeAutomation,resolvedAutomation} from '../field-studies-journeys/src/automationLinks.ts';
import {toNativeConfig,nativeExport,nativeSnapshotToJourney} from '../field-studies-journeys/src/nativeBridge.ts';
import {applyAutomations,createAutomationRuntime} from '../src/engine/automation.ts';
import {sliderPosition} from '../field-studies-journeys/src/liveValues.ts';
function setup(){const j=fieldStudies(),s=j.scenes[0];s.automation=[{id:'a',target:'field.size',enabled:true,type:'lfo',wave:'sine',min:1,max:3,rate:.25,phase:0,blend:'replace',duration:4,delay:0,loop:'once',firedAt:null},{id:'b',target:'field.opacity',enabled:true,type:'lfo',wave:'square',min:1,max:0,rate:2,phase:.2,blend:'replace',duration:1,delay:0,loop:'once',firedAt:null}];linkAutomation(s.automation,'b','a');return {j,s};}
test('linked production cycles share phase and reverse ranges without mutating scene bases',()=>{const {s}=setup(),before=JSON.stringify(s),rt=createAutomationRuntime();for(const wave of ['sine','steps','smooth'] as const){s.automation[0].wave=wave;const cfg=toNativeConfig(s);for(const time of [0,.5,1,2,4,7]){const out=applyAutomations(cfg,cfg.automations,time,rt);assert.equal(out.live.length,2);assert.equal(out.live[0].phase,out.live[1].phase);const lanes=cfg.automations;const a=(out.live[0].value-lanes[0].min!)/(lanes[0].max!-lanes[0].min!);const b=(out.live[1].value-lanes[1].min!)/(lanes[1].max!-lanes[1].min!);assert.ok(Math.abs(a-b)<1e-10);}}s.automation[0].wave='sine';assert.equal(JSON.stringify(s),before);});
test('a late linked ramp joins the running clock and group trigger restarts both',()=>{const {s}=setup();s.automation[0].type='ramp';s.automation[0].easing='linear';const rt=createAutomationRuntime();let cfg=toNativeConfig(s);applyAutomations(cfg,[cfg.automations[0]],10,rt);let out=applyAutomations(cfg,cfg.automations,12,rt);assert.deepEqual(out.live.map(v=>v.phase),[.5,.5]);s.automation[0].firedAt=1;cfg=toNativeConfig(s);out=applyAutomations(cfg,cfg.automations,13,rt);assert.deepEqual(out.live.map(v=>v.phase),[0,0]);s.automation[0].enabled=false;cfg=toNativeConfig(s);assert.equal(applyAutomations(cfg,cfg.automations,14,rt).live.length,0);});
test('links survive native export and scene serialization',()=>{const {j,s}=setup();assert.equal(validateJourney(JSON.parse(JSON.stringify(j))).scenes[0].automation[1].syncWith,'a');const imported=nativeSnapshotToJourney(nativeExport(s)).scenes[0];assert.equal(imported.automation[1].syncWith,imported.automation[0].id);assert.equal(toNativeConfig(imported).automations[1].clockId,toNativeConfig(imported).automations[0].id);});
test('unlink and leader removal retain timing, invalid links roll back',()=>{const {s}=setup();assert.throws(()=>linkAutomation(s.automation,'a','b'),/cycle/);assert.equal(s.automation[0].syncWith,undefined);assert.throws(()=>linkAutomation(s.automation,'b','missing'),/missing/);assert.equal(s.automation[1].syncWith,'a');const effective=resolvedAutomation(s.automation,s.automation[1]);s.automation=removeAutomation(s.automation,'a');assert.equal(s.automation[0].syncWith,undefined);assert.equal(s.automation[0].rate,effective.rate);assert.equal(s.automation[0].wave,effective.wave);});
test('live slider mapping clamps only the thumb and preserves logarithmic positions',()=>{assert.deepEqual(sliderPosition(3,0,2),{position:2,fill:100});const p=sliderPosition(10,0,1,1,100);assert.ok(Math.abs(p.position-.5)<1e-10);assert.ok(Math.abs(p.fill-50)<1e-10);});

import {automationGroups,removeGroupTarget,offsetAutomatedTarget} from '../field-studies-journeys/src/automationLinks.ts';
import {computeMorphDrive} from '../src/engine/morphSignal.ts';
import {evaluateLane} from '../src/engine/automation.ts';
import {NATIVE_BINDINGS} from '../field-studies-journeys/src/nativeParameters.ts';
import {automationEditor} from '../field-studies-journeys/src/automationEditor.ts';
import {monitorHTML} from '../field-studies-journeys/src/automationMonitor.ts';
test('group editor and monitor contain every target under one oscillator',()=>{const {s}=setup();assert.equal(automationGroups(s.automation).length,1);assert.equal((automationEditor(s).match(/class="automation-lane"/g)??[]).length,1);for(const lane of s.automation){assert.ok(automationEditor(s).includes(`data-target-id="${lane.id}"`));assert.ok(monitorHTML(s,'a').includes(`data-live-target="${lane.target}"`));}s.automation=removeGroupTarget(s.automation,'a');assert.equal(automationGroups(s.automation).length,1);assert.equal(s.automation[0].id,'b');assert.equal(s.automation[0].rate,.25);assert.equal(s.automation[0].syncWith,undefined);});
test('LFO frequency edits preserve phase at the edit timestamp and apply the new rate afterwards',()=>{const rt=createAutomationRuntime(),lane={id:'rate',path:'fluid.returnSpeed',enabled:true,type:'lfo' as const,rateHz:.1,min:0,max:1};const first=evaluateLane(lane,103,rt)!;lane.rateHz=2;const edited=evaluateLane(lane,103,rt)!;assert.equal(edited.phase,first.phase);assert.equal(edited.value,first.value);const later=evaluateLane(lane,103.1,rt)!;assert.ok(Math.abs(later.phase-(first.phase+.2))<1e-10);});
test('direct automated manipulation offsets the target range without shifting the shared clock or sibling',()=>{const {s}=setup(),sibling=JSON.stringify(s.automation[1]);assert.equal(offsetAutomatedTarget(s.automation,'field.size',.75),true);assert.equal(s.automation[0].min,1.75);assert.equal(s.automation[0].max,3.75);assert.equal(s.automation[0].rate,.25);assert.equal(JSON.stringify(s.automation[1]),sibling);assert.equal(offsetAutomatedTarget(s.automation,'field.unknown',1),false);});
test('morph-source automation uses the real conjugate drive for every target and survives export',()=>{const {s}=setup();s.automation[0].wave='morph';s.morph.law='product';s.engine.driveShape='smooth';const cfg=toNativeConfig(s),rt=createAutomationRuntime();for(const theta of [0,.4,1.2,3.2,7]){const drive=computeMorphDrive(cfg.toroidalMorph,theta,.73),out=applyAutomations(cfg,cfg.automations,7,rt,drive);assert.equal(out.live.length,2);for(let i=0;i<2;i++){const l=cfg.automations[i];assert.equal(out.live[i].value,l.min!+(l.max!-l.min!)*drive.progress);assert.equal(out.live[i].phase,drive.cycleFraction);}}const restored=nativeSnapshotToJourney(nativeExport(s)).scenes[0];assert.equal(restored.automation[0].wave,'morph');assert.equal(restored.automation[1].syncWith,restored.automation[0].id);});
test('all numeric controls from the legacy morph panel remain mapped into native configuration',()=>{const {s}=setup();for(const key of ['oscillationSpeed','poloidalRate','toroidalPhase','poloidalPhase','driveDepth','holdRatio','progress','toroidalWinding','poloidalWinding','fiberPhaseOffset','chiralCoupling','oscillationAmplitude','manifoldRadius','volumetricDepthScale']){const b=NATIVE_BINDINGS.find(b=>b.path==='toroidalMorph.'+key);assert.ok(b,`Missing morph control ${key}`);}s.engine.trajectory='quantumInterference';assert.equal(toNativeConfig(s).toroidalMorph.trajectory,'quantumInterference');assert.equal(nativeSnapshotToJourney(nativeExport(s)).scenes[0].engine.trajectory,'quantumInterference');});
test('removing the first target preserves the running group clock and exported membership',()=>{const {s}=setup();const rt=createAutomationRuntime();let cfg=toNativeConfig(s);applyAutomations(cfg,cfg.automations,103,rt);s.automation[0].rate=.7;cfg=toNativeConfig(s);const before=applyAutomations(cfg,cfg.automations,104,rt).live[1];s.automation=removeGroupTarget(s.automation,'a');cfg=toNativeConfig(s);const after=applyAutomations(cfg,cfg.automations,104,rt).live[0];assert.equal(after.phase,before.phase);assert.equal(after.value,before.value);const restored=nativeSnapshotToJourney(nativeExport(s)).scenes[0];assert.equal(restored.automation.length,1);assert.equal(restored.automation[0].syncWith,undefined);assert.equal(toNativeConfig(restored).automations[0].clockId,'a');});
