import assert from 'node:assert/strict';
import {test} from './harness';
import {fieldStudies,blankJourney,blankScene,entity,pin,clone,validateJourney} from '../field-studies-journeys/src/model';
import {toNativeConfig,toNativeEntity,fromNativeEntity,nativeSnapshotToJourney,nativeExport,importDocuments,nativeChakras,assertSafe} from '../field-studies-journeys/src/nativeBridge';
import {NATIVE_BINDINGS,baseValue,bindValue,automationTarget,entityTargets} from '../field-studies-journeys/src/nativeParameters';
import {DocumentStore,readLibraryDetailed,saveToLibrary,STORAGE_KEY} from '../field-studies-journeys/src/store';
import {DEFAULT_CONFIG} from '../src/engine/PointCloudField';
import {PARAM_REGISTRY} from '../src/engine/paramRegistry';
import {readPath,applyAutomations,createAutomationRuntime,writePath} from '../src/engine/automation';
import {makeFormation,makePin,resolveSequence,DEFAULT_SEQUENCE} from '../src/engine/fieldModel';
import {arrange,reorderFocus} from '../field-studies-journeys/src/timeline';

test('native handoff: every static registry number has one reversible authored owner',()=>{
 assert.equal(NATIVE_BINDINGS.length,PARAM_REGISTRY.length);assert.equal(new Set(NATIVE_BINDINGS.map(b=>b.key)).size,NATIVE_BINDINGS.length);
 const s=fieldStudies().scenes[0];
 for(const b of NATIVE_BINDINGS){const value=Math.max(b.hardMin,Math.min(b.hardMax,(b.min+b.max)*.43));bindValue(s,b.bind,value);const cfg=toNativeConfig(s);const expected=b.path==='particleCount'?Math.floor(value*b.factor):value*b.factor;assert.ok(Math.abs(Number(readPath(cfg,b.path))-expected)<1e-8,`${b.path} did not reach its native owner`);}
});
test('native handoff: pin placement is force-only, attraction default, no unrelated mutations',()=>{const s=fieldStudies().scenes[0],before=clone(s);s.entities.push(pin({x:.2,y:-.3,z:.4}));const c=toNativeConfig(s),p=c.entities!.at(-1)!;assert.equal(p.kind,'pin');assert.equal(p.forces.mode,'attract');assert.equal(p.share,0);assert.deepEqual([p.x,p.y,p.z],[80,-120,160]);assert.deepEqual(s.field,before.field);assert.deepEqual(s.entities.slice(0,2),before.entities);});
test('native handoff: pin spin survives Off radial force and migration',()=>{const e=pin({x:0,y:0,z:0});e.force.kind='none';e.force.spin=3;const a=toNativeEntity(e),b=fromNativeEntity(a);assert.equal(a.forces.spin,3);assert.equal(a.forces.mode,'none');assert.equal(b.force.spin,3);assert.equal(b.force.kind,'none');});
test('native handoff: formation extents, scale, rotation and source round-trip independently',()=>{const s=fieldStudies().scenes[0],e=s.entities[0];e.scale=2.4;e.source={kind:'ascii',ascii:{text:'O : I',invert:true}};const n=toNativeEntity(e),back=toNativeEntity(fromNativeEntity(n));for(const k of ['scale','x','y','z','extent','authoringSource'] as const)assert.deepEqual(back[k],n[k],k);});
test('native handoff: native entity automation follows IDs after focus route reorder',()=>{const s=fieldStudies().scenes[0],e=s.entities[1];const target=entityTargets(s).find(t=>t.entityId===e.id&&t.key==='x')!;s.automation=[{id:'x',target:target.target,enabled:true,type:'lfo',wave:'sine',min:.1,max:.3,rate:.5,phase:0,blend:'replace',duration:2,delay:0,loop:'once',firedAt:null}];reorderFocus(s.entities,e.id,-1);const cfg=toNativeConfig(s);assert.equal(cfg.automations![0].path,'entities.0.x');assert.equal(cfg.entities![0].id,e.id);assert.equal(cfg.automations![0].min,40);assert.equal(cfg.automations![0].max,120);});
test('native handoff: two independently timed links and per-link offsets retain native contracts',()=>{const s=fieldStudies().scenes[0],e=s.entities[0];e.sequence.enabled=true;e.sequence.hold=2;e.sequence.transition=.5;e.sequence.steps[0].holdOverride=true;e.sequence.steps[0].hold=3;e.sequence.steps[0].position={x:.2,y:.3,z:.4};e.sequence.steps.push({...clone(e.sequence.steps[0]),id:'second',hold:1,holdOverride:true,text:'&',position:null});const native=toNativeEntity(e);assert.equal(native.sequence.links[0].x,80);assert.equal(native.sequence.links[0].hold,3);assert.equal(native.sequence.links[1].hold,1);assert.equal(resolveSequence(native,3.25,0,0,0).linkIndex,0);assert.equal(resolveSequence(native,3.75,0,0,0).linkIndex,1);});
test('native handoff: manual tuning bypasses frequency lanes without erasing them',()=>{const s=fieldStudies().scenes[0];s.automation=[{id:'f',target:'field.frequency',enabled:true,type:'lfo',wave:'sine',min:80,max:1040,rate:.1,phase:0,blend:'replace',duration:2,delay:0,loop:'once',firedAt:null}];s.composition.frequencyDriver='manual';assert.equal(toNativeConfig(s).automations![0].enabled,false);s.composition.frequencyDriver='automation';assert.equal(toNativeConfig(s).automations![0].enabled,true);assert.equal(s.automation.length,1);});
test('native handoff: scene view and physical/layout planes remain separate',()=>{const s=fieldStudies().scenes[0];s.composition.plane='XZ';s.view.mode='2d';s.engine.mediumPlane='vertical';assert.equal(toNativeConfig(s).composition!.plane,'vertical');s.view.mode='3d';assert.equal(toNativeConfig(s).composition!.plane,'vertical');});
test('native handoff: native payload retains original, unknown safe fields and camera',()=>{const raw={schemaVersion:4,name:'original',config:{...clone(DEFAULT_CONFIG),futureExtension:{value:17}},view:{camera:{pitch:.4,yaw:.8,panX:12,panY:-25,zoom:1.4}}};const j=nativeSnapshotToJourney(raw);assert.deepEqual(j.scenes[0].native!.original,raw);assert.deepEqual(j.scenes[0].view.nativeCamera,raw.view.camera);assert.deepEqual((toNativeConfig(j.scenes[0]) as any).futureExtension,{value:17});});
test('native handoff: importing multiple entries reports failure separately and leaves inputs unchanged',()=>{const good=nativeExport(fieldStudies().scenes[0]),raw=[good,{schemaVersion:999,config:DEFAULT_CONFIG},null],before=JSON.stringify(raw);const result=importDocuments(raw);assert.equal(result.journeys.length,1);assert.equal(result.errors.length,2);assert.match(result.errors[0].message,/newer/);assert.equal(JSON.stringify(raw),before);});
test('native handoff: native capacity is checked before migration can truncate',()=>{const s=fieldStudies().scenes[0];const native=toNativeConfig(s);native.entities=Array.from({length:11},(_,i)=>({...native.entities![0],id:'f'+i}));assert.throws(()=>nativeSnapshotToJourney({schemaVersion:4,config:native}),/capacity/);const p=pin({x:0,y:0,z:0});s.entities.push(...Array.from({length:9},(_,i)=>({...clone(p),id:'pin'+i})));assert.throws(()=>toNativeConfig(s),/8 pins/);});
test('native handoff: proto paths are rejected and failed edit transactions roll back',()=>{assert.throws(()=>assertSafe(JSON.parse('{"__proto__":{"bad":true}}')),/Unsafe/);assert.throws(()=>assertSafe({path:'entities.0.__proto__.bad'}),/Unsafe/);const original=fieldStudies(),store=new DocumentStore(original);assert.throws(()=>store.change(d=>{d.name='partial';throw new Error('stop');}));assert.deepEqual(store.document,original);assert.equal(store.undoStack.length,0);});
test('native handoff: canonical chakra composition remains seven ordinary native formations',()=>{const forms=nativeChakras();assert.equal(forms.length,7);assert.deepEqual(forms.map(e=>e.station),[0,1,2,3,4,5,6]);assert.ok(forms.every(e=>e.kind==='formation'&&e.shape==='yantra'));assert.ok(forms[0].position.y<forms[6].position.y);});
test('native handoff: arrange operations preserve everything except selected-plane positions',()=>{const entities=fieldStudies().scenes[0].entities;const before=clone(entities);arrange(entities,'align-x','YZ');assert.equal(entities[0].position.y,entities[1].position.y);for(let i=0;i<entities.length;i++)assert.deepEqual({...entities[i],position:before[i].position},before[i]);});
test('native handoff: native snapshot export keeps authored view and removes deleted legacy sources',()=>{const s=nativeSnapshotToJourney({schemaVersion:4,config:{...clone(DEFAULT_CONFIG),sourceType:'ascii',asciiGlyph:{text:'O : I'}}}).scenes[0];assert.equal(s.entities[0].source!.kind,'ascii');delete s.entities[0].source;const exported=nativeExport(s);assert.equal(exported.config.asciiGlyph,undefined);assert.deepEqual(exported.authoringView,s.view);assert.equal(nativeSnapshotToJourney(exported).scenes[0].entities[0].source,undefined);});

test('native handoff: empty authored scenes never revive a legacy main formation',()=>{const s=blankScene();assert.deepEqual(toNativeConfig(s).entities,[]);assert.deepEqual(nativeSnapshotToJourney(nativeExport(s)).scenes[0].entities,[]);});
test('native handoff: legacy density gradient keeps its native primary/accent/secondary law',()=>{const raw={...clone(DEFAULT_CONFIG),color:{...DEFAULT_CONFIG.color!,customPaletteColors:undefined,primaryColor:'#112233',accentColor:'#aa7755',secondaryColor:'#eeffdd',mode:'densityDepth' as const}};const s=nativeSnapshotToJourney({schemaVersion:4,config:raw}).scenes[0],cfg=toNativeConfig(s);assert.equal(s.engine.paletteSource,'legacy');assert.equal(cfg.color!.customPaletteColors,undefined);assert.equal(cfg.color!.accentColor,'#aa7755');assert.equal(cfg.color!.primaryColor,'#112233');assert.equal(cfg.color!.secondaryColor,'#eeffdd');});
test('native handoff: old placed-point capacity rejects before truncation',()=>{const cfg=clone(DEFAULT_CONFIG);delete cfg.entities;cfg.interaction.placedPoints=Array.from({length:9},(_,i)=>({id:'old'+i,x:i,y:0,z:0,radius:100,strength:1,mode:'attract' as const,active:true}));assert.throws(()=>nativeSnapshotToJourney({config:cfg}),/capacity/);});

test('native handoff: library writes retain unreadable entries and more than 24 journeys',()=>{const original=Object.getOwnPropertyDescriptor(globalThis,'localStorage');const data:Record<string,string>={};Object.defineProperty(globalThis,'localStorage',{configurable:true,value:{getItem:(k:string)=>data[k]??null,setItem:(k:string,v:string)=>data[k]=v}});try{const all=Array.from({length:26},(_,i)=>({...blankJourney(),id:'keep'+i})),future={schema:'oi.journey',version:999,id:'future'};data[STORAGE_KEY]=JSON.stringify([...all,future]);saveToLibrary({...blankJourney(),id:'new'});assert.equal(JSON.parse(data[STORAGE_KEY]).length,28);assert.deepEqual(JSON.parse(data[STORAGE_KEY]).at(-1),future);assert.equal(readLibraryDetailed().errors.length,1);data[STORAGE_KEY]='malformed';assert.throws(()=>saveToLibrary(blankJourney()),/not been overwritten/);assert.equal(data[STORAGE_KEY],'malformed');}finally{if(original)Object.defineProperty(globalThis,'localStorage',original);else delete (globalThis as any).localStorage;}});
