/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Factory presets (built-in reference profiles). These are pinned to the bottom of the
 * Presets menu; user snapshots always list first.
 */

import { PointCloudConfig } from './types';
import { CANONICAL_CHAKRAS } from './chakraSystem';

export interface FactoryPreset {
  id: string;
  name: string;
  description: string;
  config: Partial<PointCloudConfig>;
}


interface SavedState {
  id: string;
  name: string;
  timestamp: number;
  config: PointCloudConfig;
}

export const FACTORY_PRESETS: FactoryPreset[] = [
  {
    id: 'toroidal_hopf_conjugate',
    name: 'Toroidal Hopf Fibration Conjugates',
    description: 'Two inverse Hopf fibration manifolds intersecting on an S³ hypersphere with dynamic chiral coupling and interference oscillations',
    config: {
      glyph: ['⏣', '☯'],
      style: 'stipple',
      dotShape: 'circle',
      particleSize: { min: 1.2, max: 4.2 },
      colorMode: 'whiteOnBlack',
      backgroundColor: '#05050f',
      toroidalMorph: {
        enabled: true,
        trajectory: 'toroidalHopf',
        progress: 0.5,
        autoOscillate: true,
        oscillationSpeed: 0.9,
        oscillationAmplitude: 1.3,
        fiberPhaseOffset: 0.0,
        toroidalWinding: 3.0,
        poloidalWinding: 2.0,
        chiralCoupling: 0.85,
        manifoldRadius: 210,
      },
      color: {
        enabled: true,
        mode: 'waveInterference',
        primaryColor: '#00f0ff',
        secondaryColor: '#8a2be2',
        accentColor: '#ff007f',
        cycleSpeed: 1.5,
        waveFrequency: 2.2,
        angle: 45,
        fieldCenterOffset: [0, 0],
        turbulenceModulation: 0.45,
        speedReactiveIntensity: 1.2,
        densityWeight: 0.6,
        contrast: 1.2,
        hueShiftSpeed: 0.1,
      },
      fluid: {
        curlScale: 1.8,
        curlSpeed: 0.9,
        vortexStrength: 2.0,
        viscosity: 0.94,
        returnSpeed: 1.2,
        turbulence: 1.1,
        dispersion: 0.8,
      },
      interaction: {
        radius: 200,
        strength: 1.5,
        mode: 'vortex',
      },
      autoMorph: false,
    },
  },
  {
    id: 'reference_oi',
    name: 'O ⇄ I Vortex Bridge',
    description: 'Canonical reference: orbital vorticity pulling O boundary into I bar with fine stipple spray',
    config: {
      glyph: ['O', 'I'],
      style: 'stipple',
      dotShape: 'circle',
      particleSize: { min: 1.5, max: 3.5 },
      fluid: {
        curlScale: 1.2,
        curlSpeed: 0.6,
        vortexStrength: 1.45,
        viscosity: 0.94,
        returnSpeed: 1.15,
        turbulence: 1.0,
        dispersion: 0.75,
      },
      interaction: {
        radius: 190,
        strength: 1.3,
        mode: 'repel',
      },
      relational: {
        enabled: false,
        mode: 'orbital',
        attractorCount: 2,
        attractorGravity: 1.6,
        orbitSpeed: 0.8,
        orbitRadius: 240,
        relationalSpin: 1.4,
        chaosFactor: 0.2,
        wanderSpeed: 0.5,
      },
      autoMorph: true,
      autoMorphDuration: 3.8,
    },
  },
  {
    id: 'binary_star_orbit',
    name: 'Binary Star Relational Orbits',
    description: 'Two relational attractor poles dynamically orbiting each other, transferring stipple particles along gravitational bridges',
    config: {
      glyph: ['✦', '✧'],
      style: 'stipple',
      dotShape: 'circle',
      particleSize: { min: 1.2, max: 4.0 },
      relational: {
        enabled: true,
        mode: 'orbital',
        attractorCount: 2,
        attractorGravity: 3.2,
        orbitSpeed: 1.2,
        orbitRadius: 280,
        relationalSpin: 2.5,
        chaosFactor: 0.4,
        wanderSpeed: 0.6,
      },
      fluid: {
        curlScale: 1.4,
        curlSpeed: 0.8,
        vortexStrength: 1.5,
        viscosity: 0.94,
        returnSpeed: 0.6,
        turbulence: 0.8,
        dispersion: 0.5,
      },
      interaction: {
        radius: 200,
        strength: 1.5,
        mode: 'vortex',
      },
      autoMorph: false,
    },
  },
  {
    id: 'chaotic_strange_attractor',
    name: 'Harmonic Strange Attractor',
    description: '3 multi-pole non-linear harmonic wanderers perturbing typographic symbols into turbulent filament streams',
    config: {
      glyph: ['Ω', '∞'],
      style: 'stipple',
      dotShape: 'circle',
      particleSize: { min: 1.0, max: 3.8 },
      relational: {
        enabled: true,
        mode: 'chaos',
        attractorCount: 3,
        attractorGravity: 4.5,
        orbitSpeed: 0.5,
        orbitRadius: 320,
        relationalSpin: -3.0,
        chaosFactor: 2.2,
        wanderSpeed: 1.8,
      },
      fluid: {
        curlScale: 2.2,
        curlSpeed: 1.2,
        vortexStrength: 2.2,
        viscosity: 0.93,
        returnSpeed: 0.4,
        turbulence: 1.8,
        dispersion: 1.0,
      },
      interaction: {
        radius: 250,
        strength: 2.0,
        mode: 'attract',
      },
      autoMorph: false,
    },
  },
  {
    id: 'nbody_lemniscate',
    name: 'N-Body Lemniscate Rosette',
    description: 'Keplerian figure-8 orbit with 4 dynamic centers interweaving mathematical glyph forms in continuous motion',
    config: {
      glyph: ['∑', '∫'],
      style: 'halftone',
      dotShape: 'circle',
      particleSize: { min: 1.2, max: 5.0 },
      relational: {
        enabled: true,
        mode: 'nbody',
        attractorCount: 4,
        attractorGravity: 2.8,
        orbitSpeed: 1.4,
        orbitRadius: 260,
        relationalSpin: 2.0,
        chaosFactor: 0.3,
        wanderSpeed: 0.4,
      },
      fluid: {
        curlScale: 0.9,
        curlSpeed: 0.5,
        vortexStrength: 1.2,
        viscosity: 0.95,
        returnSpeed: 0.9,
        turbulence: 0.5,
        dispersion: 0.3,
      },
      interaction: {
        radius: 220,
        strength: 1.4,
        mode: 'vortex',
      },
      autoMorph: false,
    },
  },
  {
    id: 'explosive_antigravity',
    name: 'Anti-Spring Kinetic Dispersal',
    description: 'Negative spring constant (k = -0.6) and high kinetic speed propelling stipple points outward in unrestrained fluid dissipation',
    config: {
      glyph: ['&', '@'],
      style: 'stipple',
      dotShape: 'circle',
      particleSize: { min: 1.4, max: 4.5 },
      relational: {
        enabled: true,
        mode: 'chaos',
        attractorCount: 2,
        attractorGravity: -2.5,
        orbitSpeed: 2.0,
        orbitRadius: 300,
        relationalSpin: 5.0,
        chaosFactor: 3.5,
        wanderSpeed: 2.0,
      },
      fluid: {
        curlScale: 3.0,
        curlSpeed: 2.5,
        vortexStrength: 4.5,
        viscosity: 0.97,
        returnSpeed: -0.6,
        turbulence: 3.0,
        dispersion: 2.5,
      },
      interaction: {
        radius: 350,
        strength: 3.5,
        mode: 'repel',
      },
      autoMorph: true,
      autoMorphDuration: 3.0,
    },
  },
  {
    id: 'halftone_matrix',
    name: 'Ordered Halftone Matrix',
    description: 'Structured dot-matrix grid with radius directly modulated by typographical stroke density',
    config: {
      glyph: ['O', 'I'],
      style: 'halftone',
      dotShape: 'circle',
      particleSize: { min: 1.2, max: 5.2 },
      fluid: {
        curlScale: 0.8,
        curlSpeed: 0.4,
        vortexStrength: 0.6,
        viscosity: 0.96,
        returnSpeed: 1.8,
        turbulence: 0.4,
        dispersion: 0.2,
      },
      interaction: {
        radius: 160,
        strength: 1.1,
        mode: 'vortex',
      },
      relational: {
        enabled: false,
      },
      autoMorph: true,
      autoMorphDuration: 4.5,
    },
  },
  {
    id: 'risograph_spray',
    name: 'Risograph Ink Spray',
    description: 'Organic high-turbulence curl dispersion with micro-droplet perimeter scatter',
    config: {
      glyph: ['&', '@'],
      style: 'stipple',
      dotShape: 'circle',
      particleSize: { min: 1.2, max: 3.8 },
      fluid: {
        curlScale: 1.8,
        curlSpeed: 0.85,
        vortexStrength: 1.1,
        viscosity: 0.93,
        returnSpeed: 0.85,
        turbulence: 1.6,
        dispersion: 0.9,
      },
      interaction: {
        radius: 220,
        strength: 1.5,
        mode: 'repel',
      },
      relational: {
        enabled: false,
      },
      autoMorph: true,
      autoMorphDuration: 4.2,
    },
  },
  {
    id: 'square_dither',
    name: 'Square Dither Grid',
    description: 'Typographic square dither matrix with geometric halftone compression',
    config: {
      glyph: ['8', '∞'],
      style: 'halftone',
      dotShape: 'square',
      particleSize: { min: 1.4, max: 4.8 },
      fluid: {
        curlScale: 1.0,
        curlSpeed: 0.5,
        vortexStrength: 0.8,
        viscosity: 0.95,
        returnSpeed: 1.5,
        turbulence: 0.6,
        dispersion: 0.4,
      },
      interaction: {
        radius: 180,
        strength: 1.2,
        mode: 'attract',
      },
      relational: {
        enabled: false,
      },
      autoMorph: true,
      autoMorphDuration: 4.0,
    },
  },
  {
    id: 'chain_polygons',
    name: 'Platonic Polygon Sequence',
    description: 'Continuous geometric evolution traversing triangle, square, pentagon, hexagon, octagon, and circle',
    config: {
      style: 'stipple',
      dotShape: 'circle',
      particleSize: { min: 1.5, max: 3.5 },
      fluid: {
        curlScale: 1.6,
        curlSpeed: 0.9,
        vortexStrength: 1.8,
        viscosity: 0.94,
        returnSpeed: 1.4,
        turbulence: 1.2,
        dispersion: 0.8,
      },
      interaction: {
        radius: 200,
        strength: 1.5,
        mode: 'vortex',
      },
      relational: {
        enabled: false,
      },
      chaining: {
        enabled: true,
        chain: ['▲', '■', '⬟', '⬢', '⯎', '◉'],
        mode: 'loop',
        stepHoldDuration: 1.2,
        transitionDuration: 2.2,
        easing: 'smoothstep',
        timingJitter: 0.1,
        disperseImpulse: 0.6,
        paused: false,
      },
      autoMorph: false,
    },
  },
  {
    id: 'chain_zodiac',
    name: '12 Zodiac Constellations',
    description: 'Astronomical transit through the full 12 zodiac symbols with orbital multi-attractor dynamics',
    config: {
      style: 'stipple',
      dotShape: 'circle',
      particleSize: { min: 1.2, max: 3.2 },
      fluid: {
        curlScale: 1.8,
        curlSpeed: 1.2,
        vortexStrength: 2.0,
        viscosity: 0.95,
        returnSpeed: 1.5,
        turbulence: 1.4,
        dispersion: 0.9,
      },
      interaction: {
        radius: 220,
        strength: 1.6,
        mode: 'vortex',
      },
      relational: {
        enabled: true,
        mode: 'orbital',
        attractorCount: 3,
        attractorGravity: 1.4,
        orbitSpeed: 0.9,
        orbitRadius: 260,
        relationalSpin: 1.8,
        chaosFactor: 0.3,
        wanderSpeed: 0.8,
      },
      chaining: {
        enabled: true,
        chain: ['♈', '♉', '♊', '♋', '♌', '♍', '♎', '♏', '♐', '♑', '♒', '♓'],
        mode: 'loop',
        stepHoldDuration: 1.0,
        transitionDuration: 2.0,
        easing: 'kineticSnap',
        timingJitter: 0.15,
        disperseImpulse: 0.9,
        paused: false,
      },
      autoMorph: false,
    },
  },
  {
    id: 'cyberpunk_chroma',
    name: 'Cyberpunk Neon Wave',
    description: 'Electric cyan, hot pink and solar amber propagating in diagonal waves with kinetic velocity ignition',
    config: {
      glyph: ['Ω', '✦'],
      style: 'stipple',
      dotShape: 'circle',
      particleSize: { min: 1.5, max: 4.0 },
      colorMode: 'whiteOnBlack',
      color: {
        enabled: true,
        mode: 'linearGradient',
        primaryColor: '#00f0ff',
        secondaryColor: '#ff007f',
        accentColor: '#ffe600',
        cycleSpeed: 1.8,
        waveFrequency: 2.2,
        angle: 45,
        fieldCenterOffset: [0, 0],
        turbulenceModulation: 0.45,
        speedReactiveIntensity: 1.2,
        densityWeight: 0.6,
        hueShiftSpeed: 0.1,
        contrast: 1.2,
        paletteId: 'cyberpunk_neon',
      },
      fluid: {
        curlScale: 1.6,
        curlSpeed: 0.9,
        vortexStrength: 1.8,
        viscosity: 0.94,
        returnSpeed: 1.3,
        turbulence: 1.2,
        dispersion: 0.8,
      },
      interaction: {
        radius: 220,
        strength: 1.6,
        mode: 'vortex',
      },
      relational: {
        enabled: false,
      },
      autoMorph: true,
      autoMorphDuration: 3.8,
    },
  },
  {
    id: 'aurora_borealis_spectral',
    name: 'Aurora Borealis Spectral',
    description: 'Bioluminescent emerald and cyan curtains rippling with cymatic wave interference across runic chain',
    config: {
      style: 'stipple',
      dotShape: 'circle',
      particleSize: { min: 1.2, max: 3.6 },
      colorMode: 'whiteOnBlack',
      color: {
        enabled: true,
        mode: 'waveInterference',
        primaryColor: '#00ff87',
        secondaryColor: '#60efff',
        accentColor: '#bf55ec',
        cycleSpeed: 1.4,
        waveFrequency: 2.6,
        angle: 120,
        fieldCenterOffset: [0, -0.2],
        turbulenceModulation: 0.7,
        speedReactiveIntensity: 1.5,
        densityWeight: 0.4,
        hueShiftSpeed: 0.05,
        contrast: 1.1,
        paletteId: 'aurora_borealis',
      },
      chaining: {
        enabled: true,
        chain: ['᚛', '᚜', 'ᚠ', 'ᚢ', 'ᚦ', 'ᚨ'],
        mode: 'loop',
        stepHoldDuration: 1.0,
        transitionDuration: 2.0,
        easing: 'smoothstep',
        timingJitter: 0.1,
        disperseImpulse: 0.9,
        paused: false,
      },
      fluid: {
        curlScale: 2.0,
        curlSpeed: 1.0,
        vortexStrength: 2.0,
        viscosity: 0.94,
        returnSpeed: 1.1,
        turbulence: 1.4,
        dispersion: 0.85,
      },
      interaction: {
        radius: 200,
        strength: 1.4,
        mode: 'vortex',
      },
      relational: {
        enabled: false,
      },
      autoMorph: false,
    },
  },
  {
    id: 'solar_plasma_thermal',
    name: 'Solar Corona Thermal',
    description: 'Incandescent plasma with kinetic velocity ignition and convective rotational sweeps around orbital attractors',
    config: {
      glyph: ['☉', '☼'],
      style: 'stipple',
      dotShape: 'circle',
      particleSize: { min: 1.4, max: 4.2 },
      colorMode: 'whiteOnBlack',
      color: {
        enabled: true,
        mode: 'velocityThermal',
        primaryColor: '#ff2200',
        secondaryColor: '#ff8800',
        accentColor: '#ffffaa',
        cycleSpeed: 2.0,
        waveFrequency: 2.0,
        angle: 90,
        fieldCenterOffset: [0, 0],
        turbulenceModulation: 0.55,
        speedReactiveIntensity: 2.0,
        densityWeight: 0.7,
        hueShiftSpeed: 0.0,
        contrast: 1.3,
        paletteId: 'solar_plasma',
      },
      fluid: {
        curlScale: 2.2,
        curlSpeed: 1.3,
        vortexStrength: 2.4,
        viscosity: 0.95,
        returnSpeed: 1.2,
        turbulence: 1.8,
        dispersion: 1.1,
      },
      interaction: {
        radius: 250,
        strength: 2.0,
        mode: 'repel',
      },
      relational: {
        enabled: true,
        mode: 'orbital',
        attractorCount: 3,
        attractorGravity: 2.5,
        orbitSpeed: 1.4,
        orbitRadius: 260,
        relationalSpin: 2.0,
        chaosFactor: 0.3,
        wanderSpeed: 0.8,
      },
      autoMorph: true,
      autoMorphDuration: 3.5,
    },
  },
  {
    id: 'editorial_parchment_stipple',
    name: 'Editorial Parchment & Sumi Ink',
    description: 'Crisp warm parchment canvas with deep vermilion and sumi ink particles and subtle paper vignette',
    config: {
      glyph: ['字', '道'],
      style: 'stipple',
      dotShape: 'circle',
      particleSize: { min: 1.2, max: 3.8 },
      colorMode: 'blackOnWhite',
      backgroundColor: '#f5f0e6',
      backgroundMode: 'vignette',
      color: {
        enabled: true,
        mode: 'linearGradient',
        primaryColor: '#c0392b',
        secondaryColor: '#1c1917',
        accentColor: '#d35400',
        cycleSpeed: 0.8,
        waveFrequency: 1.5,
        angle: 60,
        fieldCenterOffset: [0, 0],
        turbulenceModulation: 0.3,
        speedReactiveIntensity: 0.6,
        densityWeight: 0.5,
        hueShiftSpeed: 0.0,
        contrast: 1.3,
        paletteId: 'editorial_vermilion',
        backgroundColor: '#f5f0e6',
        backgroundMode: 'vignette',
        backgroundGlowIntensity: 0.3,
      },
      fluid: {
        curlScale: 1.1,
        curlSpeed: 0.5,
        vortexStrength: 1.2,
        viscosity: 0.95,
        returnSpeed: 1.4,
        turbulence: 0.8,
        dispersion: 0.6,
      },
      interaction: {
        radius: 190,
        strength: 1.4,
        mode: 'repel',
      },
      autoMorph: true,
      autoMorphDuration: 3.5,
    },
  },
  {
    id: 'chakral_body_constellation',
    name: 'Chakral Body — 7 Subtle Centers Constellation',
    description: 'Spatial constellation of all 7 chakras positioned along the vertical spine with localized attractor vortices and spectral colors',
    config: {
      style: 'stipple',
      dotShape: 'circle',
      particleSize: { min: 1.2, max: 3.6 },
      colorMode: 'whiteOnBlack',
      fluid: {
        curlScale: 1.4,
        curlSpeed: 0.6,
        vortexStrength: 1.6,
        viscosity: 0.95,
        returnSpeed: 1.3,
        turbulence: 0.9,
        dispersion: 0.6,
      },
      spatialChakra: {
        enabled: true,
        playbackMode: 'simultaneousBody',
        glyphType: 'both',
        cycleDirection: 'ascent',
        holdDuration: 1.2,
        transitionDuration: 2.4,
        attractorInfluence: 1.8,
        particlePartitionSpread: 0.9,
        nodes: CANONICAL_CHAKRAS.map((c) => ({ ...c })),
      },
      color: {
        enabled: true,
        mode: 'linearGradient',
        primaryColor: '#ff1744',
        secondaryColor: '#00e676',
        accentColor: '#b388ff',
        cycleSpeed: 0.8,
        waveFrequency: 1.5,
        angle: 90,
        fieldCenterOffset: [0, 0],
        turbulenceModulation: 0.3,
        speedReactiveIntensity: 1.0,
        densityWeight: 0.5,
        hueShiftSpeed: 0.05,
        contrast: 1.2,
        backgroundColor: '#0a0515',
        backgroundMode: 'ambientGlow',
        backgroundGlowIntensity: 0.4,
      },
      autoMorph: false,
    },
  },
  {
    id: 'kundalini_spinal_ascent',
    name: 'Kundalini Ascent — Sequential Spine Transit',
    description: 'Energetic Kundalini ascent: particles dynamically morph both shape and spatial position climbing from root chakra to crown lotus',
    config: {
      style: 'stipple',
      dotShape: 'circle',
      particleSize: { min: 1.4, max: 4.0 },
      fluid: {
        curlScale: 1.8,
        curlSpeed: 0.9,
        vortexStrength: 2.2,
        viscosity: 0.94,
        returnSpeed: 1.4,
        turbulence: 1.2,
        dispersion: 0.8,
      },
      spatialChakra: {
        enabled: true,
        playbackMode: 'sequentialMorph',
        glyphType: 'both',
        cycleDirection: 'ascent',
        holdDuration: 1.4,
        transitionDuration: 2.6,
        attractorInfluence: 2.2,
        particlePartitionSpread: 0.85,
        nodes: CANONICAL_CHAKRAS.map((c) => ({ ...c })),
      },
      autoMorph: false,
    },
  },
  {
    id: 'cymatic_chladni_harmonics',
    name: 'Chladni Cymatics — Harmonic Attractor Spectrum',
    description: 'Chakra Mode 2: Continuous acoustic frequency spectrum with deterministic Chladni standing wave nodal attractors and in-between Faraday chaos',
    config: {
      style: 'stipple',
      dotShape: 'circle',
      particleSize: { min: 1.2, max: 3.4 },
      colorMode: 'whiteOnBlack',
      fluid: {
        curlScale: 1.2,
        curlSpeed: 0.5,
        vortexStrength: 1.2,
        viscosity: 0.96,
        returnSpeed: 1.5,
        turbulence: 0.8,
        dispersion: 0.5,
      },
      spatialChakra: {
        enabled: true,
        geometryMode: 'cymatics',
        playbackMode: 'sequentialMorph',
        glyphType: 'both',
        cycleDirection: 'ascent',
        plane: 'horizontal',
        cymatics: {
          plateGeometry: 'square',
          dimension: '2D',
          frequencyHz: 528,
          autoSweep: true,
          sweepSpeed: 10.0,
          chaosIntensity: 1.4,
          nodalAttraction: 3.0,
          dampingQFactor: 4.5,
        },
        nodes: CANONICAL_CHAKRAS.map((c) => ({ ...c })),
      },
      color: {
        enabled: true,
        mode: 'linearGradient',
        primaryColor: '#00f0ff',
        secondaryColor: '#bf55ec',
        accentColor: '#00ff87',
        cycleSpeed: 1.2,
        waveFrequency: 2.0,
        angle: 45,
        fieldCenterOffset: [0, 0],
        turbulenceModulation: 0.4,
        speedReactiveIntensity: 1.2,
        densityWeight: 0.6,
        hueShiftSpeed: 0.05,
        contrast: 1.3,
        backgroundColor: '#050814',
        backgroundMode: 'ambientGlow',
        backgroundGlowIntensity: 0.4,
      },
      autoMorph: false,
    },
  },
  {
    id: 'cymatic_volumetric_3d',
    name: 'Volumetric 3D Cymatic Standing Wave',
    description: 'Chakra Mode 2 (3D): Volumetric modal wave nodal surfaces forming spatial acoustic standing cages with frequency sweeping',
    config: {
      style: 'stipple',
      dotShape: 'circle',
      particleSize: { min: 1.4, max: 3.8 },
      colorMode: 'whiteOnBlack',
      fluid: {
        curlScale: 1.0,
        curlSpeed: 0.4,
        vortexStrength: 1.0,
        viscosity: 0.97,
        returnSpeed: 1.6,
        turbulence: 0.6,
        dispersion: 0.4,
      },
      spatialChakra: {
        enabled: true,
        geometryMode: 'cymatics',
        playbackMode: 'simultaneousBody',
        glyphType: 'both',
        cycleDirection: 'ascent',
        plane: 'horizontal',
        cymatics: {
          plateGeometry: 'volumetric3D',
          dimension: '3D',
          frequencyHz: 417,
          autoSweep: true,
          sweepSpeed: 12.0,
          chaosIntensity: 1.2,
          nodalAttraction: 3.2,
          dampingQFactor: 5.0,
        },
        nodes: CANONICAL_CHAKRAS.map((c) => ({ ...c })),
      },
      color: {
        enabled: true,
        mode: 'radialGradient',
        primaryColor: '#8a2be2',
        secondaryColor: '#00ffff',
        accentColor: '#ffffff',
        cycleSpeed: 0.8,
        waveFrequency: 1.8,
        angle: 0,
        fieldCenterOffset: [0, 0],
        turbulenceModulation: 0.3,
        speedReactiveIntensity: 1.0,
        densityWeight: 0.5,
        hueShiftSpeed: 0.02,
        contrast: 1.2,
        backgroundColor: '#090514',
        backgroundMode: 'vignette',
        backgroundGlowIntensity: 0.3,
      },
      autoMorph: false,
    },
  },
];
