/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

export interface GlyphItem {
  char: string;
  name: string;
  category: string;
}

export interface GlyphCategory {
  id: string;
  name: string;
  description: string;
  items: GlyphItem[];
}

export interface ChainPreset {
  id: string;
  name: string;
  description: string;
  chain: string[];
  recommendedHold?: number;
  recommendedTransition?: number;
  recommendedEasing?: 'smoothstep' | 'linear' | 'kineticSnap' | 'whip';
}

export const GLYPH_CATEGORIES: GlyphCategory[] = [
  {
    id: 'polygons',
    name: 'Polygons & Sacred Geometry',
    description: 'Geometric primitives from 3-sided delta polygons to 8-gons and sacred polyhedra',
    items: [
      { char: '▲', name: 'Trigon / Triangle', category: 'polygons' },
      { char: '▼', name: 'Inverted Delta', category: 'polygons' },
      { char: '△', name: 'Open Delta', category: 'polygons' },
      { char: '■', name: 'Tetragon / Square', category: 'polygons' },
      { char: '◆', name: 'Rhombus / Diamond', category: 'polygons' },
      { char: '◈', name: 'Nested Diamond', category: 'polygons' },
      { char: '⬟', name: 'Pentagon / 5-Gon', category: 'polygons' },
      { char: '⬠', name: 'Hollow Pentagon', category: 'polygons' },
      { char: '⛤', name: 'Pentagram Sigil', category: 'polygons' },
      { char: '⬢', name: 'Hexagon / 6-Gon', category: 'polygons' },
      { char: '⬡', name: 'Hollow Hexagon', category: 'polygons' },
      { char: '✡', name: 'Hexagram / Star', category: 'polygons' },
      { char: '⯎', name: 'Octagon / 8-Gon', category: 'polygons' },
      { char: '✵', name: '8-Pointed Star', category: 'polygons' },
      { char: '◉', name: 'Concentric Monad', category: 'polygons' },
      { char: '◎', name: 'Bullseye Ring', category: 'polygons' },
      { char: '◯', name: 'Perfect Circle', category: 'polygons' },
      { char: '⎊', name: 'Merkaba Polyhedron', category: 'polygons' },
      { char: '⏣', name: 'Benzene Hex Grid', category: 'polygons' },
      { char: '⯐', name: 'Star Octahedron', category: 'polygons' },
      { char: '⌬', name: 'Fused Hex Core', category: 'polygons' },
      { char: '⊛', name: 'Circled Asterisk', category: 'polygons' },
      { char: '⊕', name: 'Sun Cross / Quadrant', category: 'polygons' },
      { char: '⊗', name: 'Tensor Matrix', category: 'polygons' },
    ],
  },
  {
    id: 'zodiac',
    name: 'Zodiac & Astrological Signs',
    description: 'The complete classical 12 ecliptic zodiac constellations plus Ophiuchus',
    items: [
      { char: '♈', name: 'Aries (Ram)', category: 'zodiac' },
      { char: '♉', name: 'Taurus (Bull)', category: 'zodiac' },
      { char: '♊', name: 'Gemini (Twins)', category: 'zodiac' },
      { char: '♋', name: 'Cancer (Crab)', category: 'zodiac' },
      { char: '♌', name: 'Leo (Lion)', category: 'zodiac' },
      { char: '♍', name: 'Virgo (Maiden)', category: 'zodiac' },
      { char: '♎', name: 'Libra (Scales)', category: 'zodiac' },
      { char: '♏', name: 'Scorpio (Scorpion)', category: 'zodiac' },
      { char: '♐', name: 'Sagittarius (Archer)', category: 'zodiac' },
      { char: '♑', name: 'Capricorn (Sea Goat)', category: 'zodiac' },
      { char: '♒', name: 'Aquarius (Water Bearer)', category: 'zodiac' },
      { char: '♓', name: 'Pisces (Fishes)', category: 'zodiac' },
      { char: '⛎', name: 'Ophiuchus (Serpent)', category: 'zodiac' },
    ],
  },
  {
    id: 'planetary',
    name: 'Planetary & Celestial',
    description: 'Astronomical planet glyphs, lunar phases, and stellar luminaries',
    items: [
      { char: '☉', name: 'Sol / Sun', category: 'planetary' },
      { char: '☽', name: 'Waxing Crescent', category: 'planetary' },
      { char: '☾', name: 'Waning Crescent', category: 'planetary' },
      { char: '☿', name: 'Mercury', category: 'planetary' },
      { char: '♀', name: 'Venus', category: 'planetary' },
      { char: '♁', name: 'Terra / Earth', category: 'planetary' },
      { char: '♂', name: 'Mars', category: 'planetary' },
      { char: '♃', name: 'Jupiter', category: 'planetary' },
      { char: '♄', name: 'Saturn', category: 'planetary' },
      { char: '♅', name: 'Uranus', category: 'planetary' },
      { char: '♆', name: 'Neptune', category: 'planetary' },
      { char: '♇', name: 'Pluto', category: 'planetary' },
      { char: '✦', name: 'Four-Point Flare', category: 'planetary' },
      { char: '✧', name: 'Sparkle Luminary', category: 'planetary' },
      { char: '★', name: 'Five-Point Star', category: 'planetary' },
      { char: '❂', name: 'Radiant Solar Disc', category: 'planetary' },
    ],
  },
  {
    id: 'alchemical',
    name: 'Alchemical Elements',
    description: 'Classical alchemical principles, element triangles, and hermetic symbols',
    items: [
      { char: '🜂', name: 'Ignis (Fire)', category: 'alchemical' },
      { char: '🜄', name: 'Aqua (Water)', category: 'alchemical' },
      { char: '🜁', name: 'Aer (Air)', category: 'alchemical' },
      { char: '🜃', name: 'Terra (Earth)', category: 'alchemical' },
      { char: '🜀', name: 'Quintessence / Aether', category: 'alchemical' },
      { char: '🜍', name: 'Sulphur (Soul)', category: 'alchemical' },
      { char: '🜔', name: 'Sal (Salt / Body)', category: 'alchemical' },
      { char: '🜎', name: 'Hydrargyrum (Mercury / Mind)', category: 'alchemical' },
      { char: '🝤', name: 'Aurum (Gold)', category: 'alchemical' },
      { char: '🝢', name: 'Argentum (Silver)', category: 'alchemical' },
      { char: '🜞', name: 'Sublimation', category: 'alchemical' },
      { char: '🝁', name: 'Distillation Crucible', category: 'alchemical' },
    ],
  },
  {
    id: 'runes',
    name: 'Elder Futhark Runes',
    description: 'Ancient Germanic and Norse stave inscriptions',
    items: [
      { char: 'ᚠ', name: 'Fehu (Wealth)', category: 'runes' },
      { char: 'ᚢ', name: 'Uruz (Strength)', category: 'runes' },
      { char: 'ᚦ', name: 'Thurisaz (Thorn / Giant)', category: 'runes' },
      { char: 'ᚨ', name: 'Ansuz (Breath / Voice)', category: 'runes' },
      { char: 'ᚱ', name: 'Raidho (Journey / Wheel)', category: 'runes' },
      { char: 'ᚲ', name: 'Kenaz (Torch / Fire)', category: 'runes' },
      { char: 'ᚷ', name: 'Gebo (Gift / Exchange)', category: 'runes' },
      { char: 'ᚹ', name: 'Wunjo (Joy / Harmony)', category: 'runes' },
      { char: 'ᚺ', name: 'Hagalaz (Hail / Tempest)', category: 'runes' },
      { char: 'ᚾ', name: 'Nauthiz (Need / Friction)', category: 'runes' },
      { char: 'ᛁ', name: 'Isa (Ice / Stasis)', category: 'runes' },
      { char: 'ᛃ', name: 'Jera (Harvest / Cycle)', category: 'runes' },
      { char: 'ᛇ', name: 'Eihwaz (Yew / Axis)', category: 'runes' },
      { char: 'ᛉ', name: 'Algiz (Elk / Protection)', category: 'runes' },
      { char: 'ᛊ', name: 'Sowilo (Sun Lightning)', category: 'runes' },
      { char: 'ᛏ', name: 'Tiwaz (Justice / Sky)', category: 'runes' },
      { char: 'ᛒ', name: 'Berkana (Birch / Birth)', category: 'runes' },
      { char: 'ᛖ', name: 'Ehwaz (Steed / Momentum)', category: 'runes' },
      { char: 'ᛗ', name: 'Mannaz (Humanity)', category: 'runes' },
      { char: 'ᛚ', name: 'Laguz (Water / Tide)', category: 'runes' },
      { char: 'ᛜ', name: 'Ingwaz (Seed / Core)', category: 'runes' },
      { char: 'ᛞ', name: 'Dagaz (Dawn / Awakening)', category: 'runes' },
      { char: 'ᛟ', name: 'Othala (Ancestry / Hearth)', category: 'runes' },
    ],
  },
  {
    id: 'math',
    name: 'Physics & Operators',
    description: 'Vector calculus operators, continuum mechanics integrals, and constants',
    items: [
      { char: '∞', name: 'Lemniscate / Infinity', category: 'math' },
      { char: '∑', name: 'Summation Sigma', category: 'math' },
      { char: '∏', name: 'Product Pi', category: 'math' },
      { char: '∫', name: 'Continuous Integral', category: 'math' },
      { char: '∬', name: 'Surface Integral', category: 'math' },
      { char: '∮', name: 'Circulation Contour', category: 'math' },
      { char: '∇', name: 'Del / Nabla Gradient', category: 'math' },
      { char: '∂', name: 'Partial Derivative', category: 'math' },
      { char: '√', name: 'Radical / Square Root', category: 'math' },
      { char: 'λ', name: 'Lambda / Eigenvalue', category: 'math' },
      { char: 'Ω', name: 'Ohm / Terminal Omega', category: 'math' },
      { char: 'ℏ', name: 'Reduced Planck Constant', category: 'math' },
      { char: 'ℵ', name: 'Aleph Cardinality', category: 'math' },
    ],
  },
  {
    id: 'greek',
    name: 'Classical Greek & Esoteric',
    description: 'Hellenic letters used across metaphysics, quantum systems, and geometry',
    items: [
      { char: 'Ω', name: 'Omega', category: 'greek' },
      { char: 'Δ', name: 'Delta', category: 'greek' },
      { char: 'Σ', name: 'Sigma', category: 'greek' },
      { char: 'Φ', name: 'Phi / Golden Ratio', category: 'greek' },
      { char: 'Ψ', name: 'Psi / Wavefunction', category: 'greek' },
      { char: 'α', name: 'Alpha', category: 'greek' },
      { char: 'β', name: 'Beta', category: 'greek' },
      { char: 'γ', name: 'Gamma', category: 'greek' },
      { char: 'θ', name: 'Theta', category: 'greek' },
      { char: 'π', name: 'Pi', category: 'greek' },
      { char: 'φ', name: 'Phi (lowercase)', category: 'greek' },
      { char: 'ψ', name: 'Psi (lowercase)', category: 'greek' },
      { char: '☯', name: 'Taijitu / Dualism', category: 'greek' },
      { char: '§', name: 'Section Mark', category: 'greek' },
      { char: '¶', name: 'Pilcrow', category: 'greek' },
    ],
  },
  {
    id: 'chakras',
    name: 'Chakras & Sacred Bija Syllables',
    description: 'Canonical Sanskrit seed mantras and tantric sacred symbols for the 7 primary subtle centers',
    items: [
      { char: 'ॐ', name: 'AUM / Crown & Ajna Cosmic Monad', category: 'chakras' },
      { char: 'हं', name: 'HAM / Vishuddha Throat Mantra', category: 'chakras' },
      { char: 'यं', name: 'YAM / Anahata Heart Mantra', category: 'chakras' },
      { char: 'रं', name: 'RAM / Manipura Solar Plexus Mantra', category: 'chakras' },
      { char: 'वं', name: 'VAM / Svadhisthana Sacral Mantra', category: 'chakras' },
      { char: 'लं', name: 'LAM / Muladhara Root Mantra', category: 'chakras' },
      { char: '☸', name: 'Dharmachakra / 1000-Petal Sahasrara Wheel', category: 'chakras' },
      { char: '🪷', name: 'Lotus of the Heart (Padma)', category: 'chakras' },
      { char: '✡', name: 'Anahata Star Hexagram (Air Yantra)', category: 'chakras' },
      { char: '🔻', name: 'Manipura Downward Fire Triangle', category: 'chakras' },
      { char: '☽', name: 'Svadhisthana Crescent Moon (Water)', category: 'chakras' },
      { char: '■', name: 'Muladhara Golden Earth Square', category: 'chakras' },
      { char: '👁️', name: 'Ajna Divine Third Eye of Wisdom', category: 'chakras' },
      { char: '⚡', name: 'Kundalini Awakening Surge', category: 'chakras' },
    ],
  },
];

export const CHAIN_PRESETS: ChainPreset[] = [
  {
    id: 'chakra_kundalini_ascent',
    name: 'Kundalini Chakra Ascent (Root ➔ Crown)',
    description: 'Energetic spinal transit from Muladhara (लं) up through all 7 centers to Sahasrara (ॐ)',
    chain: ['लं', 'वं', 'रं', 'यं', 'हं', 'ॐ', '☸'],
    recommendedHold: 1.2,
    recommendedTransition: 2.4,
    recommendedEasing: 'smoothstep',
  },
  {
    id: 'chakra_sacred_yantras',
    name: 'Sacred Chakra Yantra Geometry',
    description: 'Geometric yantra progression: Square (Earth) ➔ Crescent ➔ Triangle (Fire) ➔ Hexagram (Air) ➔ Circle (Ether) ➔ Two Petals ➔ Lotus',
    chain: ['■', '☽', '🔻', '✡', '◯', '◉', '☸'],
    recommendedHold: 1.0,
    recommendedTransition: 2.2,
    recommendedEasing: 'kineticSnap',
  },
  {
    id: 'platonic_polygons',
    name: 'Platonic Polygon Progression',
    description: 'Iterative vertices expansion: Triangle (3) → Square (4) → Pentagon (5) → Hexagon (6) → Octagon (8) → Circle (∞)',
    chain: ['▲', '■', '⬟', '⬢', '⯎', '◉'],
    recommendedHold: 1.0,
    recommendedTransition: 2.2,
    recommendedEasing: 'kineticSnap',
  },
  {
    id: 'zodiac_ecliptic',
    name: 'Great Zodiac Constellation Orbit',
    description: 'The full 12 constellations of the celestial zodiac transitioning through fire, earth, air, and water',
    chain: ['♈', '♉', '♊', '♋', '♌', '♍', '♎', '♏', '♐', '♑', '♒', '♓'],
    recommendedHold: 0.8,
    recommendedTransition: 2.0,
    recommendedEasing: 'smoothstep',
  },
  {
    id: 'sacred_geometry',
    name: 'Sacred Polyhedra & Merkaba Matrix',
    description: 'Complex dimensional sigils from Merkaba to Hexagonal Lattice, Tensor Ring, and Monad',
    chain: ['⎊', '⏣', '✡', '⬢', '⊛', '◎', '⯐'],
    recommendedHold: 1.2,
    recommendedTransition: 2.5,
    recommendedEasing: 'kineticSnap',
  },
  {
    id: 'celestial_planets',
    name: 'Celestial Spheres Planetary Transit',
    description: 'Traversing outward from Sol through inner and outer planetary orbs to the celestial horizon',
    chain: ['☉', '☽', '☿', '♀', '♁', '♂', '♃', '♄', '♅', '♆'],
    recommendedHold: 0.9,
    recommendedTransition: 2.4,
    recommendedEasing: 'smoothstep',
  },
  {
    id: 'alchemical_elements',
    name: 'Hermetic Alchemical Transmutation',
    description: 'Triangular elemental transformations: Fire → Water → Air → Earth → Quintessence → Sulphur → Gold',
    chain: ['🜂', '🜄', '🜁', '🜃', '🜀', '🜍', '🜔', '🝤'],
    recommendedHold: 1.1,
    recommendedTransition: 2.2,
    recommendedEasing: 'whip',
  },
  {
    id: 'nordic_runes',
    name: 'Elder Futhark Stave Sequence',
    description: 'Ancestral Nordic runes radiating mystical kinetic energy through stippled vectors',
    chain: ['ᚠ', 'ᚱ', 'ᚲ', 'ᚷ', 'ᛃ', 'ᛇ', 'ᛉ', 'ᛊ', 'ᛏ', 'ᛞ', 'ᛟ'],
    recommendedHold: 0.8,
    recommendedTransition: 2.0,
    recommendedEasing: 'smoothstep',
  },
  {
    id: 'math_continuum',
    name: 'Calculus Operator Continuum',
    description: 'From infinity to contour integrals, nabla gradient, eigenvalue wavefunctions, and omega',
    chain: ['∞', '∑', '∫', '∇', '∂', 'λ', 'Ω'],
    recommendedHold: 1.0,
    recommendedTransition: 2.5,
    recommendedEasing: 'kineticSnap',
  },
  {
    id: 'binary_vortex',
    name: 'Canonical Binary Flux (O ⇄ I)',
    description: 'Extended alternation between the canonical circular void, structural bar, and cardinal cross',
    chain: ['O', 'I', 'X', '+', '0', '1'],
    recommendedHold: 0.7,
    recommendedTransition: 1.8,
    recommendedEasing: 'smoothstep',
  },
  {
    id: 'lexical_words',
    name: 'Semantics Word Stream',
    description: 'Multi-character whole word fluid morphing across abstract typographic concepts',
    chain: ['VOID', 'FORM', 'FLUID', 'FLOW', 'ECHO', 'NULL'],
    recommendedHold: 1.4,
    recommendedTransition: 2.8,
    recommendedEasing: 'smoothstep',
  },
];
